# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4c868ef8b1cd6552179d818a77218e69ef0e68bd8c0bf05b892ab55c63b7620e
# To regenerate: alef generate
# To verify freshness: alef verify
"""Public API for _native.

Version: 0.2.0
"""

from ._native import (
    AttachmentHint,
    ByteRange,
    ChildEdge,
    CoreError,
    CoreParseResult,
    NativeExtension,
    NodeRole,
    ParseBatchRequest,
    ParseBatchResult,
    ParseComment,
    ParseDiagnostic,
    ParseLimits,
    ParseNode,
    ParserCandidate,
    ParserProbeRequest,
    ParserProbeResult,
    ParserProviderDescriptor,
    ParserSelection,
    ParseSeverity,
    ProbeBatchRequest,
    ProbeBatchResult,
    SelectionReport,
    SourceEncoding,
    SourceInput,
    SourcePoint,
    SourceRole,
    SourceSpan,
)
from .api import parse_sources, register_parser_host, unregister_parser_host
from .options import (
    LineEndings,
    ParseOptions,
    ParseOutput,
    ParseRequest,
    SourceDescriptor,
)

__all__ = [
    "AttachmentHint",
    "ByteRange",
    "ChildEdge",
    "CoreError",
    "CoreParseResult",
    "LineEndings",
    "NativeExtension",
    "NodeRole",
    "ParseBatchRequest",
    "ParseBatchResult",
    "ParseComment",
    "ParseDiagnostic",
    "ParseLimits",
    "ParseNode",
    "ParseOptions",
    "ParseOutput",
    "ParseRequest",
    "ParseSeverity",
    "ParserCandidate",
    "ParserProbeRequest",
    "ParserProbeResult",
    "ParserProviderDescriptor",
    "ParserSelection",
    "ProbeBatchRequest",
    "ProbeBatchResult",
    "SelectionReport",
    "SourceDescriptor",
    "SourceEncoding",
    "SourceInput",
    "SourcePoint",
    "SourceRole",
    "SourceSpan",
    "parse_sources",
    "register_parser_host",
    "unregister_parser_host",
]

__version__ = "0.2.0"
