# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c16df648cbf26ff71f2627b3a22c10daefee7f22d823a5c359f2f8c708b93977
# To regenerate: alef generate
# To verify freshness: alef verify

import builtins

class ByteRange:
    start_byte: int
    end_byte: int
    def __init__(self, start_byte: int, end_byte: int) -> None: ...
    def is_valid(self) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def contains_byte(self, offset: int) -> bool: ...
    @staticmethod
    def from_json(json_str: str) -> ByteRange: ...

class ChildEdge:
    node_id: str
    index: int
    field_name: str | None
    extra: dict[str, str]
    def __init__(
        self,
        node_id: str,
        index: int,
        extra: dict[str, str],
        field_name: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ChildEdge: ...

class ConflictAlternative:
    revision: SourceRevision
    state: ConflictAlternativeState
    regions: list[OwnedSourceRegion]
    def __init__(
        self,
        revision: SourceRevision | str,
        state: ConflictAlternativeState | str,
        regions: list[OwnedSourceRegion],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ConflictAlternative: ...

class CoreError:
    code: str
    message: str
    def __init__(self, code: str, message: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CoreError: ...

class CoreParseResult:
    schema: str
    selection: SelectionReport
    backend: ParserProviderDescriptor
    parsed: ParseOutput
    def __init__(
        self,
        schema: str,
        selection: SelectionReport,
        backend: ParserProviderDescriptor,
        parsed: ParseOutput,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CoreParseResult: ...

class CrisprBatchOperationReport:
    operation_count: int
    operation_kinds: list[str]
    operation_profiles: list[CrisprOperationReport]
    def __init__(
        self,
        operation_count: int,
        operation_kinds: list[str],
        operation_profiles: list[CrisprOperationReport],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBatchOperationReport: ...

class CrisprBoundaryImplementation:
    language: str
    package_name: str
    import_path: str | None
    require_path: str | None
    crate_name: str | None
    def __init__(
        self,
        language: str,
        package_name: str,
        import_: str | None = None,
        require: str | None = None,
        crate_: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryImplementation: ...

class CrisprBoundaryMetadata:
    source: str
    decision: str
    def __init__(self, source: str, decision: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryMetadata: ...

class CrisprBoundaryRelationships:
    ast_merge: list[str]
    ast_crispr: list[str]
    provider_packages: list[str]
    ast_template: list[str]
    def __init__(
        self,
        ast_merge: list[str],
        ast_crispr: list[str],
        provider_packages: list[str],
        ast_template: list[str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryRelationships: ...

class CrisprBoundaryReport:
    package: str
    layer: str
    status: str
    base_contract_package: str
    relationship: CrisprBoundaryRelationships
    implementations: list[CrisprBoundaryImplementation]
    initial_exports: list[str]
    future_exports: list[str]
    metadata: CrisprBoundaryMetadata
    def __init__(
        self,
        package: str,
        layer: str,
        status: str,
        base_contract_package: str,
        relationship: CrisprBoundaryRelationships,
        implementations: list[CrisprBoundaryImplementation],
        initial_exports: list[str],
        future_exports: list[str],
        metadata: CrisprBoundaryMetadata,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryReport: ...

class CrisprDestinationReport:
    resolution_kind: str
    resolution_family: str
    known_resolution_kind: bool
    resolution_source: str
    resolution_source_family: str
    known_resolution_source: bool
    anchor_boundary: str
    anchor_boundary_family: str
    known_anchor_boundary: bool
    used_if_missing: bool
    append_fallback: bool
    anchored: bool
    def __init__(
        self,
        resolution_kind: str,
        resolution_family: str,
        known_resolution_kind: bool,
        resolution_source: str,
        resolution_source_family: str,
        known_resolution_source: bool,
        anchor_boundary: str,
        anchor_boundary_family: str,
        known_anchor_boundary: bool,
        used_if_missing: bool,
        append_fallback: bool,
        anchored: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprDestinationReport: ...

class CrisprDestinationRequest:
    resolution_kind: str
    resolution_source: str
    anchor_boundary: str
    used_if_missing: bool
    def __init__(
        self,
        resolution_kind: str,
        resolution_source: str,
        anchor_boundary: str,
        used_if_missing: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprDestinationRequest: ...

class CrisprLimitConstraint:
    operator: CrisprLimitOperator
    value: int
    def __init__(self, operator: CrisprLimitOperator | str, value: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprLimitConstraint: ...

class CrisprLimitReport:
    description: str
    counts: list[int]
    allowed: list[bool]
    def __init__(self, description: str, counts: list[int], allowed: list[bool]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprLimitReport: ...

class CrisprLimitRequest:
    constraints: list[CrisprLimitConstraint] | None
    counts: list[int]
    def __init__(
        self,
        counts: list[int],
        constraints: list[CrisprLimitConstraint] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprLimitRequest: ...

class CrisprMatchReport:
    start_boundary: str
    start_boundary_family: str
    known_start_boundary: bool
    end_boundary: str
    end_boundary_family: str
    known_end_boundary: bool
    payload_kind: str
    payload_family: str
    known_payload_kind: bool
    comment_anchored: bool
    trailing_gap_extended: bool
    def __init__(
        self,
        start_boundary: str,
        start_boundary_family: str,
        known_start_boundary: bool,
        end_boundary: str,
        end_boundary_family: str,
        known_end_boundary: bool,
        payload_kind: str,
        payload_family: str,
        known_payload_kind: bool,
        comment_anchored: bool,
        trailing_gap_extended: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprMatchReport: ...

class CrisprMatchRequest:
    start_boundary: str
    end_boundary: str
    payload_kind: str
    def __init__(self, start_boundary: str, end_boundary: str, payload_kind: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprMatchRequest: ...

class CrisprOperationReport:
    operation_kind: str
    operation_family: str
    known_operation_kind: bool
    source_requirement: str
    known_source_requirement: bool
    destination_requirement: str
    known_destination_requirement: bool
    replacement_source: str
    known_replacement_source: bool
    captures_source_text: bool
    supports_if_missing: bool
    selects_source: bool
    requires_source: bool
    supports_destination: bool
    requires_destination: bool
    explicit_replacement: bool
    may_reuse_captured_text: bool
    def __init__(
        self,
        operation_kind: str,
        operation_family: str,
        known_operation_kind: bool,
        source_requirement: str,
        known_source_requirement: bool,
        destination_requirement: str,
        known_destination_requirement: bool,
        replacement_source: str,
        known_replacement_source: bool,
        captures_source_text: bool,
        supports_if_missing: bool,
        selects_source: bool,
        requires_source: bool,
        supports_destination: bool,
        requires_destination: bool,
        explicit_replacement: bool,
        may_reuse_captured_text: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprOperationReport: ...

class CrisprOperationRequest:
    operation_kind: str
    source_requirement: str
    destination_requirement: str
    replacement_source: str
    captures_source_text: bool
    supports_if_missing: bool
    def __init__(
        self,
        operation_kind: str,
        source_requirement: str,
        destination_requirement: str,
        replacement_source: str,
        captures_source_text: bool,
        supports_if_missing: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprOperationRequest: ...

class CrisprSelectionReport:
    owner_scope: str
    owner_selector: str
    owner_selector_family: str
    known_owner_selector: bool
    selector_kind: str
    selector_kind_family: str
    known_selector_kind: bool
    selection_intent: str
    selection_intent_family: str
    known_selection_intent: bool
    comment_region: str | None
    comment_region_family: str
    known_comment_region: bool
    comment_anchored: bool
    include_trailing_gap: bool
    def __init__(
        self,
        owner_scope: str,
        owner_selector: str,
        owner_selector_family: str,
        known_owner_selector: bool,
        selector_kind: str,
        selector_kind_family: str,
        known_selector_kind: bool,
        selection_intent: str,
        selection_intent_family: str,
        known_selection_intent: bool,
        comment_region_family: str,
        known_comment_region: bool,
        comment_anchored: bool,
        include_trailing_gap: bool,
        comment_region: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprSelectionReport: ...

class CrisprSelectionRequest:
    owner_scope: str
    owner_selector: str
    selector_kind: str
    selection_intent: str
    comment_region: str | None
    include_trailing_gap: bool
    def __init__(
        self,
        owner_scope: str,
        owner_selector: str,
        selector_kind: str,
        selection_intent: str,
        include_trailing_gap: bool,
        comment_region: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprSelectionRequest: ...

class Diagnostic:
    severity: DiagnosticSeverity
    category: DiagnosticCategory
    message: str
    path: str | None
    review: ReviewDiagnosticDetail | None
    def __init__(
        self,
        severity: DiagnosticSeverity | str,
        category: DiagnosticCategory | str,
        message: str,
        path: str | None = None,
        review: ReviewDiagnosticDetail | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> Diagnostic: ...

class ExplicitSourceEdit:
    start_byte: int
    end_byte: int
    replacement: str
    def __init__(self, start_byte: int, end_byte: int, replacement: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ExplicitSourceEdit: ...

class LineEndings:
    lf: int
    crlf: int
    bare_cr: int
    def __init__(
        self,
        lf: int | None = None,
        crlf: int | None = None,
        bare_cr: int | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LineEndings: ...

class MergeConflict:
    conflict_id: str
    category: str
    path: str
    fallback_scope: str
    message: str
    alternatives: list[ConflictAlternative]
    def __init__(
        self,
        conflict_id: str,
        category: str,
        path: str,
        fallback_scope: str,
        message: str,
        alternatives: list[ConflictAlternative],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> MergeConflict: ...

class NativeAnalysisRejection:
    code: str
    source_id: str
    source_role: SourceRole
    message: str
    def __init__(
        self,
        code: str,
        source_id: str,
        source_role: SourceRole | str,
        message: str,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeAnalysisRejection: ...

class NativeExtension:
    schema: str
    namespace: str
    capabilities: list[str]
    payload: str
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        namespace: str,
        capabilities: list[str],
        payload: str,
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeExtension: ...

class NativeMergeProfile:
    id: str
    family: str
    operation: str
    entry_point: str
    analysis_crate: str
    merge_crate: str
    semantic_runtime: str
    parse_contract: str
    native_extension: str
    syntax_scope: list[str]
    limitations: list[str]
    experimental: bool
    approved_as_default: bool
    def __init__(
        self,
        id: str,  # noqa: A002
        family: str,
        operation: str,
        entry_point: str,
        analysis_crate: str,
        merge_crate: str,
        semantic_runtime: str,
        parse_contract: str,
        native_extension: str,
        syntax_scope: list[str],
        limitations: list[str],
        experimental: bool,
        approved_as_default: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeMergeProfile: ...

class NativeMergeResult:
    profile_id: str
    outcome: ThreeWayMergeOutcome
    diagnostics: list[Diagnostic]
    conflicts: list[MergeConflict]
    output: str | None
    policies: list[PolicyReference]
    rejected_parse: CoreParseResult | None
    input_parses: list[CoreParseResult]
    output_parse: CoreParseResult | None
    verification_failure: ParserFailure | None
    input_failure: ParserFailure | None
    analysis_rejections: list[NativeAnalysisRejection]
    sources: list[SourceDescriptor]
    output_source: SourceDescriptor | None
    source_segments: list[RetainedSourceSegment]
    def __init__(
        self,
        profile_id: str,
        outcome: ThreeWayMergeOutcome | str,
        diagnostics: list[Diagnostic],
        conflicts: list[MergeConflict],
        policies: list[PolicyReference],
        input_parses: list[CoreParseResult],
        analysis_rejections: list[NativeAnalysisRejection],
        sources: list[SourceDescriptor],
        source_segments: list[RetainedSourceSegment],
        output: str | None = None,
        rejected_parse: CoreParseResult | None = None,
        output_parse: CoreParseResult | None = None,
        verification_failure: ParserFailure | None = None,
        input_failure: ParserFailure | None = None,
        output_source: SourceDescriptor | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeMergeResult: ...

class OwnedSourceRegion:
    node_id: str
    region_kind: str
    start_byte: int
    end_byte: int
    start_line: int
    end_line: int
    def __init__(
        self,
        node_id: str,
        region_kind: str,
        start_byte: int,
        end_byte: int,
        start_line: int,
        end_line: int,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OwnedSourceRegion: ...

class ParseBatchRequest:
    items: list[ParseRequest]
    def __init__(self, items: list[ParseRequest]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseBatchRequest: ...

class ParseBatchResult:
    items: list[ParseOutput]
    def __init__(self, items: list[ParseOutput]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseBatchResult: ...

class ParseComment:
    node_id: str
    native_kind: str
    attachment_hint: AttachmentHint
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        node_id: str,
        native_kind: str,
        attachment_hint: AttachmentHint | str,
        metadata: dict[str, str],
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseComment: ...

class ParseDiagnostic:
    id: str
    severity: ParseSeverity
    category: str
    code: str | None
    message: str
    source_role: SourceRole
    span: SourceSpan | None
    node_id: str | None
    blocking: bool
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        id: str,  # noqa: A002
        severity: ParseSeverity | str,
        category: str,
        message: str,
        source_role: SourceRole | str,
        blocking: bool,
        metadata: dict[str, str],
        extra: dict[str, str],
        code: str | None = None,
        span: SourceSpan | None = None,
        node_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseDiagnostic: ...

class ParseLimits:
    max_batch_items: int
    max_input_bytes: int
    max_nodes: int
    max_diagnostics: int
    timeout_millis: int | None
    def __init__(
        self,
        max_batch_items: int,
        max_input_bytes: int,
        max_nodes: int,
        max_diagnostics: int,
        timeout_millis: int | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseLimits: ...

class ParseNode:
    id: str
    kind: str
    native_type: str
    role: NodeRole
    named: bool
    missing: bool
    has_error: bool
    span: SourceSpan
    parent_id: str | None
    children: list[ChildEdge]
    semantic_roles: list[str]
    unsupported_features: list[str]
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        id: str,  # noqa: A002
        type: str,  # noqa: A002
        native_type: str,
        role: NodeRole | str,
        named: bool,
        missing: bool,
        has_error: bool,
        span: SourceSpan,
        children: list[ChildEdge],
        semantic_roles: list[str],
        unsupported_features: list[str],
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        parent_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseNode: ...

class ParseOptions:
    comments: bool
    tokens: bool
    diagnostics: bool
    native_extensions: bool
    def __init__(
        self,
        comments: bool | None = None,
        tokens: bool | None = None,
        diagnostics: bool | None = None,
        native_extensions: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseOptions: ...

class ParseOutput:
    request_id: str
    source: SourceDescriptor
    ok: bool
    root_id: str | None
    nodes: list[ParseNode]
    comments: list[ParseComment]
    diagnostics: list[ParseDiagnostic]
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        request_id: str,
        source: SourceDescriptor,
        ok: bool,
        nodes: list[ParseNode],
        comments: list[ParseComment],
        diagnostics: list[ParseDiagnostic],
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        root_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseOutput: ...

class ParseRequest:
    schema: str
    request_id: str
    source: SourceInput
    language: str
    dialect: str | None
    selection: ParserSelection
    options: ParseOptions
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        request_id: str,
        source: SourceInput,
        language: str,
        selection: ParserSelection,
        options: ParseOptions,
        metadata: dict[str, str],
        extra: dict[str, str],
        dialect: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseRequest: ...

class ParserCandidate:
    backend_id: str
    rejections: list[str]
    available: bool | None
    loadable: bool | None
    probe_fault: str | None
    request_preference: int | None
    profile_preference: int | None
    priority: int
    selected: bool
    def __init__(
        self,
        backend_id: str,
        rejections: list[str],
        priority: int,
        selected: bool,
        available: bool | None = None,
        loadable: bool | None = None,
        probe_fault: str | None = None,
        request_preference: int | None = None,
        profile_preference: int | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserCandidate: ...

class ParserFailure:
    code: str
    message: str
    backend_id: str | None
    native_code: str | None
    native_message: str | None
    source_id: str | None
    selection: SelectionReport | None
    def __init__(
        self,
        code: str,
        message: str,
        backend_id: str | None = None,
        native_code: str | None = None,
        native_message: str | None = None,
        source_id: str | None = None,
        selection: SelectionReport | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserFailure: ...

class ParserProbeRequest:
    language: str
    dialect: str | None
    def __init__(self, language: str, dialect: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserProbeRequest: ...

class ParserProbeResult:
    available: bool
    loadable: bool
    def __init__(self, available: bool, loadable: bool) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserProbeResult: ...

class ParserProviderDescriptor:
    id: str
    family: str
    runtime: str
    package: str
    package_version: str
    parser: str
    parser_version: str
    grammar: str | None
    grammar_version: str | None
    languages: list[str]
    dialects: list[str]
    contracts: list[str]
    capabilities: list[str]
    probe_id: str
    priority: int
    metadata: dict[str, str]
    extensions: list[NativeExtension]
    def __init__(
        self,
        id: str,  # noqa: A002
        family: str,
        runtime: str,
        package: str,
        package_version: str,
        parser: str,
        parser_version: str,
        languages: list[str],
        dialects: list[str],
        contracts: list[str],
        capabilities: list[str],
        probe_id: str,
        priority: int,
        metadata: dict[str, str],
        extensions: list[NativeExtension],
        grammar: str | None = None,
        grammar_version: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserProviderDescriptor: ...

class ParserSelection:
    backend_id: str | None
    preference: list[str]
    required_capabilities: list[str]
    def __init__(
        self,
        preference: list[str],
        required_capabilities: list[str],
        backend_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserSelection: ...

class PolicyReference:
    surface: PolicySurface
    name: str
    def __init__(self, surface: PolicySurface | str, name: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> PolicyReference: ...

class ProbeBatchRequest:
    items: list[ParserProbeRequest]
    def __init__(self, items: list[ParserProbeRequest]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ProbeBatchRequest: ...

class ProbeBatchResult:
    items: list[ParserProbeResult]
    def __init__(self, items: list[ParserProbeResult]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ProbeBatchResult: ...

class RetainedSourceSegment:
    id: str
    source_id: str
    source_role: SourceRole
    source_range: ByteRange
    output_range: ByteRange
    sha256: str
    owner_id: str | None
    def __init__(
        self,
        id: str,  # noqa: A002
        source_id: str,
        source_role: SourceRole | str,
        source_range: ByteRange,
        output_range: ByteRange,
        sha256: str,
        owner_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> RetainedSourceSegment: ...

class ReviewDiagnosticDetail:
    request_id: str | None
    action: ReviewDecisionAction | None
    reason: ReviewDiagnosticReason | None
    payload_kind: str | None
    expected_family: str | None
    provided_family: str | None
    def __init__(
        self,
        request_id: str | None = None,
        action: ReviewDecisionAction | str | None = None,
        reason: ReviewDiagnosticReason | str | None = None,
        payload_kind: str | None = None,
        expected_family: str | None = None,
        provided_family: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ReviewDiagnosticDetail: ...

class SelectionReport:
    requested: ParserSelection
    generation: int
    digest: str
    candidates: list[ParserCandidate]
    selected_backend: str | None
    def __init__(
        self,
        requested: ParserSelection,
        generation: int,
        digest: str,
        candidates: list[ParserCandidate],
        selected_backend: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SelectionReport: ...

class SourceDescriptor:
    source_id: str
    role: SourceRole
    byte_length: int
    sha256: str
    encoding: SourceEncoding
    bom: bool
    line_endings: LineEndings
    final_newline: bool
    def __init__(
        self,
        source_id: str,
        role: SourceRole | str,
        byte_length: int,
        sha256: str,
        encoding: SourceEncoding | str,
        bom: bool,
        line_endings: LineEndings,
        final_newline: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceDescriptor: ...

class SourceEditLimits:
    max_input_bytes: int
    max_output_bytes: int
    max_edits: int
    def __init__(self, max_input_bytes: int, max_output_bytes: int, max_edits: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceEditLimits: ...

class SourceEditRequest:
    request_id: str
    source: SourceInput
    edits: list[ExplicitSourceEdit]
    def __init__(
        self,
        request_id: str,
        source: SourceInput,
        edits: list[ExplicitSourceEdit],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceEditRequest: ...

class SourceEditResult:
    request_id: str
    source: SourceDescriptor
    output: str
    edit_count: int
    def __init__(
        self,
        request_id: str,
        source: SourceDescriptor,
        output: str,
        edit_count: int,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceEditResult: ...

class SourceInput:
    descriptor: SourceDescriptor
    bytes: builtins.bytes
    def __init__(
        self,
        descriptor: SourceDescriptor,
        bytes: builtins.bytes,  # noqa: A002
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceInput: ...

class SourcePoint:
    row: int
    column: int
    def __init__(self, row: int, column: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourcePoint: ...

class SourceSpan:
    range: ByteRange
    start_point: SourcePoint
    end_point: SourcePoint
    def __init__(
        self,
        range: ByteRange,  # noqa: A002
        start_point: SourcePoint,
        end_point: SourcePoint,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceSpan: ...

class OperationControl:
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    @staticmethod
    def new() -> OperationControl: ...

class AttachmentHint:
    LEADING: AttachmentHint = ...
    INLINE: AttachmentHint = ...
    TRAILING: AttachmentHint = ...
    PREAMBLE: AttachmentHint = ...
    POSTLUDE: AttachmentHint = ...
    ORPHAN: AttachmentHint = ...
    UNKNOWN: AttachmentHint = ...
    def __init__(self, value: int | str) -> None: ...

class ConflictAlternativeState:
    PRESENT: ConflictAlternativeState = ...
    ABSENT: ConflictAlternativeState = ...
    def __init__(self, value: int | str) -> None: ...

class CrisprLimitOperator:
    EQUAL: CrisprLimitOperator = ...
    NOT_EQUAL: CrisprLimitOperator = ...
    AT_MOST: CrisprLimitOperator = ...
    AT_LEAST: CrisprLimitOperator = ...
    LESS_THAN: CrisprLimitOperator = ...
    GREATER_THAN: CrisprLimitOperator = ...
    def __init__(self, value: int | str) -> None: ...

class DiagnosticCategory:
    PARSE_ERROR: DiagnosticCategory = ...
    DESTINATION_PARSE_ERROR: DiagnosticCategory = ...
    UNSUPPORTED_FEATURE: DiagnosticCategory = ...
    FALLBACK_APPLIED: DiagnosticCategory = ...
    AMBIGUITY: DiagnosticCategory = ...
    MERGE_CONFLICT: DiagnosticCategory = ...
    KIND_MISMATCH: DiagnosticCategory = ...
    UNSUPPORTED_VERSION: DiagnosticCategory = ...
    ASSUMED_DEFAULT: DiagnosticCategory = ...
    CONFIGURATION_ERROR: DiagnosticCategory = ...
    REPLAY_REJECTED: DiagnosticCategory = ...
    def __init__(self, value: int | str) -> None: ...

class DiagnosticSeverity:
    INFO: DiagnosticSeverity = ...
    WARNING: DiagnosticSeverity = ...
    ERROR: DiagnosticSeverity = ...
    def __init__(self, value: int | str) -> None: ...

class NodeRole:
    STRUCTURAL: NodeRole = ...
    TOKEN: NodeRole = ...
    TRIVIA: NodeRole = ...
    COMMENT: NodeRole = ...
    DELIMITER: NodeRole = ...
    SEPARATOR: NodeRole = ...
    VIRTUAL: NodeRole = ...
    ERROR: NodeRole = ...
    OPAQUE: NodeRole = ...
    def __init__(self, value: int | str) -> None: ...

class ParseSeverity:
    INFO: ParseSeverity = ...
    WARNING: ParseSeverity = ...
    ERROR: ParseSeverity = ...
    def __init__(self, value: int | str) -> None: ...

class PolicySurface:
    FALLBACK: PolicySurface = ...
    ARRAY: PolicySurface = ...
    def __init__(self, value: int | str) -> None: ...

class ReviewDecisionAction:
    ACCEPT_DEFAULT_CONTEXT: ReviewDecisionAction = ...
    PROVIDE_EXPLICIT_CONTEXT: ReviewDecisionAction = ...
    APPLY_DELEGATED_CHILD_GROUP: ReviewDecisionAction = ...
    def __init__(self, value: int | str) -> None: ...

class ReviewDiagnosticReason:
    MISSING_REQUIRED_PAYLOAD: ReviewDiagnosticReason = ...
    FAMILY_MISMATCH: ReviewDiagnosticReason = ...
    REQUEST_NOT_FOUND: ReviewDiagnosticReason = ...
    def __init__(self, value: int | str) -> None: ...

class SourceEncoding:
    UTF8: SourceEncoding = ...
    BINARY: SourceEncoding = ...
    def __init__(self, value: int | str) -> None: ...

class SourceRevision:
    BASE: SourceRevision = ...
    OURS: SourceRevision = ...
    THEIRS: SourceRevision = ...
    def __init__(self, value: int | str) -> None: ...

class SourceRole:
    SOURCE: SourceRole = ...
    BEFORE: SourceRole = ...
    AFTER: SourceRole = ...
    INCOMING: SourceRole = ...
    CURRENT: SourceRole = ...
    BASE: SourceRole = ...
    OURS: SourceRole = ...
    THEIRS: SourceRole = ...
    OUTPUT: SourceRole = ...
    def __init__(self, value: int | str) -> None: ...

class ThreeWayMergeOutcome:
    CLEAN: ThreeWayMergeOutcome = ...
    CONFLICT: ThreeWayMergeOutcome = ...
    ERROR: ThreeWayMergeOutcome = ...
    def __init__(self, value: int | str) -> None: ...

def apply_explicit_source_edits(
    request: SourceEditRequest,
    limits: SourceEditLimits,
) -> SourceEditResult: ...

def create_operation_control() -> OperationControl: ...
def merge_python_declarations(
    requests: list[ParseRequest],
    limits: ParseLimits,
) -> NativeMergeResult: ...

def merge_python_declarations_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> NativeMergeResult: ...

def merge_yaml_mapping(requests: list[ParseRequest], limits: ParseLimits) -> NativeMergeResult: ...
def merge_yaml_mapping_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> NativeMergeResult: ...

def native_merge_profiles() -> list[NativeMergeProfile]: ...
def parse_sources(requests: list[ParseRequest], limits: ParseLimits) -> list[CoreParseResult]: ...
def parse_sources_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> list[CoreParseResult]: ...

def register_parser_host(host: object) -> None: ...
def report_structural_boundary() -> CrisprBoundaryReport: ...
def report_structural_destination(request: CrisprDestinationRequest) -> CrisprDestinationReport: ...
def report_structural_limit(request: CrisprLimitRequest) -> CrisprLimitReport: ...
def report_structural_match(request: CrisprMatchRequest) -> CrisprMatchReport: ...
def report_structural_operations(
    requests: list[CrisprOperationRequest],
) -> CrisprBatchOperationReport: ...

def report_structural_selection(request: CrisprSelectionRequest) -> CrisprSelectionReport: ...
def unregister_parser_host(
    id: str,  # noqa: A002
) -> None: ...
