# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc5a98b0bf295c487b004c062555daceb9c884fd2ea01dd75c13366f6f9ea1ea
# To regenerate: alef generate
# To verify freshness: alef verify
"""Public API for conversion."""

import json
from typing import Any, TypeVar, TypedDict, cast, overload

import structuredmerge_core._native as _rust

from ._native import CoreParseResult, ParseLimits, ParserHost
from .options import ParseOptions, ParseRequest

_E = TypeVar("_E")

def _pascal_to_snake(value: str) -> str:
    """Convert PascalCase/camelCase to snake_case (AtxClosed -> atx_closed)."""
    out_chars: list[str] = []
    for index, ch in enumerate(value):
        if ch.isupper() and index > 0 and (value[index - 1].islower() or (index + 1 < len(value) and value[index + 1].islower())):
            out_chars.append("_")
        out_chars.append(ch.lower())
    return "".join(out_chars)


def _coerce_enum(enum_cls: type[_E], value: object) -> _E:
    """Coerce a string/alias value into the matching pyclass enum instance."""
    if isinstance(value, enum_cls):
        return value
    if value is None:
        msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
        raise ValueError(msg)
    s = str(value).replace("-", "_").replace(" ", "_")
    snake = _pascal_to_snake(s)
    candidates = (
        s,
        s.upper(),
        s.lower(),
        snake,
        snake.upper(),
        "".join(part.capitalize() for part in s.split("_")),
        "".join(part.capitalize() for part in snake.split("_")),
    )
    for candidate in candidates:
        attr = getattr(enum_cls, candidate, None)
        if isinstance(attr, enum_cls):
            return attr
    msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
    raise ValueError(msg)


@overload
def _to_rust_parse_options(value: None) -> None: ...


@overload
def _to_rust_parse_options(value: ParseOptions | dict[str, Any] | str) -> _rust.ParseOptions: ...
def _to_rust_parse_options(value: ParseOptions | dict[str, Any] | str | None) -> _rust.ParseOptions | None:
    """Convert Python ParseOptions to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = ParseOptions(**value)
    if value is None:
        return None
    value = cast(ParseOptions, value)
    return _rust.ParseOptions(
        comments=value.comments,
        tokens=value.tokens,
        diagnostics=value.diagnostics,
        native_extensions=value.native_extensions,
    )


@overload
def _to_rust_parse_request(value: None) -> None: ...


@overload
def _to_rust_parse_request(value: ParseRequest | dict[str, Any] | str) -> _rust.ParseRequest: ...
def _to_rust_parse_request(value: ParseRequest | dict[str, Any] | str | None) -> _rust.ParseRequest | None:
    """Convert Python ParseRequest to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "options" in value and value["options"] is not None:
            value["options"] = _to_rust_parse_options(value["options"])
        value = ParseRequest(**value)
    if value is None:
        return None
    value = cast(ParseRequest, value)
    return _rust.ParseRequest(
        schema=value.schema,
        request_id=value.request_id,
        source=value.source,
        language=value.language,
        dialect=value.dialect,
        selection=value.selection,
        options=_to_rust_parse_options(value.options),
        metadata=value.metadata,
        extra=value.extra,
    )


def parse_sources(requests: list[ParseRequest], limits: ParseLimits) -> list[CoreParseResult]:
    """Parse sources."""
    _rust_requests = [_to_rust_parse_request(__item) for __item in requests]

    return _rust.parse_sources(requests=_rust_requests, limits=limits)


def register_parser_host(host: object) -> None:
    """Register parser host."""
    _rust.register_parser_host(host=host)


def unregister_parser_host(
    id: str,  # noqa: A002
) -> None:
    """Unregister parser host."""
    _rust.unregister_parser_host(id=id)
