# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:47258fb96ebc3f5563579fd93c6b09ac3943ea76877671cda98452fda7dec194
# To regenerate: alef generate
# To verify freshness: alef verify
"""Public API for conversion."""

import json
from typing import Any, TypeVar, TypedDict, cast, overload

import structuredmerge_core._native as _rust

from ._native import CoreParseResult, CrisprBatchOperationReport, CrisprOperationRequest, NativeMergeProfile, NativeMergeResult, OperationControl, ParseLimits, ParserHost, SourceEditLimits, SourceEditRequest, SourceEditResult
from .options import ParseOptions, ParseRequest

_E = TypeVar("_E")

def _pascal_to_snake(value: str) -> str:
    """Convert PascalCase/camelCase to snake_case (AtxClosed -> atx_closed)."""
    out_chars: list[str] = []
    for index, ch in enumerate(value):
        if ch.isupper() and index > 0 and (value[index - 1].islower() or (index + 1 < len(value) and value[index + 1].islower())):
            out_chars.append("_")
        out_chars.append(ch.lower())
    return "".join(out_chars)


def _coerce_enum(enum_cls: type[_E], value: object) -> _E:
    """Coerce a string/alias value into the matching pyclass enum instance."""
    if isinstance(value, enum_cls):
        return value
    if value is None:
        msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
        raise ValueError(msg)
    s = str(value).replace("-", "_").replace(" ", "_")
    snake = _pascal_to_snake(s)
    candidates = (
        s,
        s.upper(),
        s.lower(),
        snake,
        snake.upper(),
        "".join(part.capitalize() for part in s.split("_")),
        "".join(part.capitalize() for part in snake.split("_")),
    )
    for candidate in candidates:
        attr = getattr(enum_cls, candidate, None)
        if isinstance(attr, enum_cls):
            return attr
    msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
    raise ValueError(msg)


@overload
def _to_rust_parse_options(value: None) -> None: ...


@overload
def _to_rust_parse_options(value: ParseOptions | dict[str, Any] | str) -> _rust.ParseOptions: ...
def _to_rust_parse_options(value: ParseOptions | dict[str, Any] | str | None) -> _rust.ParseOptions | None:
    """Convert Python ParseOptions to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = ParseOptions(**value)
    if value is None:
        return None
    value = cast(ParseOptions, value)
    return _rust.ParseOptions(
        comments=value.comments,
        tokens=value.tokens,
        diagnostics=value.diagnostics,
        native_extensions=value.native_extensions,
    )


@overload
def _to_rust_parse_request(value: None) -> None: ...


@overload
def _to_rust_parse_request(value: ParseRequest | dict[str, Any] | str) -> _rust.ParseRequest: ...
def _to_rust_parse_request(value: ParseRequest | dict[str, Any] | str | None) -> _rust.ParseRequest | None:
    """Convert Python ParseRequest to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "options" in value and value["options"] is not None:
            value["options"] = _to_rust_parse_options(value["options"])
        value = ParseRequest(**value)
    if value is None:
        return None
    value = cast(ParseRequest, value)
    return _rust.ParseRequest(
        schema=value.schema,
        request_id=value.request_id,
        source=value.source,
        language=value.language,
        dialect=value.dialect,
        selection=value.selection,
        options=_to_rust_parse_options(value.options),
        metadata=value.metadata,
        extra=value.extra,
    )


def apply_explicit_source_edits(
    request: SourceEditRequest,
    limits: SourceEditLimits,
) -> _rust.SourceEditResult:
    """Apply caller-selected UTF-8 byte edits atomically using the shared renderer. Invalid, ove."""
    return _rust.apply_explicit_source_edits(request=request, limits=limits)


def create_operation_control() -> _rust.OperationControl:
    """Create operation control."""
    return _rust.create_operation_control()


def merge_python_declarations(
    requests: list[ParseRequest],
    limits: ParseLimits,
) -> _rust.NativeMergeResult:
    """Rust derives Python owners from LibCST facts and uses the same shared merge engine as YAM."""
    _rust_requests = [_to_rust_parse_request(__item) for __item in requests]

    return _rust.merge_python_declarations(requests=_rust_requests, limits=limits)


def merge_python_declarations_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> _rust.NativeMergeResult:
    """Merge python declarations controlled."""
    _rust_requests = [_to_rust_parse_request(__item) for __item in requests]

    return _rust.merge_python_declarations_controlled(requests=_rust_requests, limits=limits, control=control)


def merge_yaml_mapping(
    requests: list[ParseRequest],
    limits: ParseLimits,
) -> _rust.NativeMergeResult:
    """Experimental block-mapping profile. Native hosts provide syntax only; YAML analysis and s."""
    _rust_requests = [_to_rust_parse_request(__item) for __item in requests]

    return _rust.merge_yaml_mapping(requests=_rust_requests, limits=limits)


def merge_yaml_mapping_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> _rust.NativeMergeResult:
    """Merge yaml mapping controlled."""
    _rust_requests = [_to_rust_parse_request(__item) for __item in requests]

    return _rust.merge_yaml_mapping_controlled(requests=_rust_requests, limits=limits, control=control)


def native_merge_profiles() -> list[NativeMergeProfile]:
    """Does not load or probe parsers. A declared profile may be unavailable in a host until a c."""
    return _rust.native_merge_profiles()


def parse_sources(requests: list[ParseRequest], limits: ParseLimits) -> list[CoreParseResult]:
    """Parse sources."""
    _rust_requests = [_to_rust_parse_request(__item) for __item in requests]

    return _rust.parse_sources(requests=_rust_requests, limits=limits)


def parse_sources_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> list[CoreParseResult]:
    """Parse sources controlled."""
    _rust_requests = [_to_rust_parse_request(__item) for __item in requests]

    return _rust.parse_sources_controlled(requests=_rust_requests, limits=limits, control=control)


def register_parser_host(host: object) -> None:
    """Register parser host."""
    _rust.register_parser_host(host=host)


def report_structural_operations(
    requests: list[CrisprOperationRequest],
) -> _rust.CrisprBatchOperationReport:
    """Describe structural operation profiles in input order using ast-crispr's shared classific."""
    return _rust.report_structural_operations(requests=requests)


def unregister_parser_host(
    id: str,  # noqa: A002
) -> None:
    """Unregister parser host."""
    _rust.unregister_parser_host(id=id)
