# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:750f9ce91da274e3eff792701359123c843aba3897c80ed863fbf003890d5ff9
# To regenerate: alef generate
# To verify freshness: alef verify
"""Public API for conversion."""

from typing import Any, TypeVar

import structuredmerge_core._native as _rust

from ._native import CoreParseResult, CrisprBatchOperationReport, CrisprBoundaryReport, CrisprDestinationReport, CrisprDestinationRequest, CrisprLimitReport, CrisprLimitRequest, CrisprMatchReport, CrisprMatchRequest, CrisprOperationRequest, CrisprSelectionReport, CrisprSelectionRequest, NativeDiffRequest, NativeDiffResult, NativeMergeProfile, NativeMergeResult, OperationControl, OperationRequest, OperationResult, ParseLimits, ParseRequest, ParserHost, SourceEditLimits, SourceEditRequest, SourceEditResult, TemplateProfileRequest, TemplateSessionOptions, TemplateSessionPlanReport, TemplateSessionRequestReport

_E = TypeVar("_E")

def _pascal_to_snake(value: str) -> str:
    """Convert PascalCase/camelCase to snake_case (AtxClosed -> atx_closed)."""
    out_chars: list[str] = []
    for index, ch in enumerate(value):
        if ch.isupper() and index > 0 and (value[index - 1].islower() or (index + 1 < len(value) and value[index + 1].islower())):
            out_chars.append("_")
        out_chars.append(ch.lower())
    return "".join(out_chars)


def _coerce_enum(enum_cls: type[_E], value: object) -> _E:
    """Coerce a string/alias value into the matching pyclass enum instance."""
    if isinstance(value, enum_cls):
        return value
    if value is None:
        msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
        raise ValueError(msg)
    s = str(value).replace("-", "_").replace(" ", "_")
    snake = _pascal_to_snake(s)
    candidates = (
        s,
        s.upper(),
        s.lower(),
        snake,
        snake.upper(),
        "".join(part.capitalize() for part in s.split("_")),
        "".join(part.capitalize() for part in snake.split("_")),
    )
    for candidate in candidates:
        attr = getattr(enum_cls, candidate, None)
        if isinstance(attr, enum_cls):
            return attr
    msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
    raise ValueError(msg)


def apply_explicit_source_edits(
    request: SourceEditRequest,
    limits: SourceEditLimits,
) -> _rust.SourceEditResult:
    """Apply caller-selected UTF-8 byte edits atomically using the shared renderer. Invalid, ove."""
    return _rust.apply_explicit_source_edits(request=request, limits=limits)


def create_operation_control() -> _rust.OperationControl:
    """Create operation control."""
    return _rust.create_operation_control()


def diff_native_owners(request: NativeDiffRequest, limits: ParseLimits) -> _rust.NativeDiffResult:
    """Diff native owners."""
    return _rust.diff_native_owners(request=request, limits=limits)


def diff_native_owners_controlled(
    request: NativeDiffRequest,
    limits: ParseLimits,
    control: OperationControl,
) -> _rust.NativeDiffResult:
    """Diff native owners controlled."""
    return _rust.diff_native_owners_controlled(request=request, limits=limits, control=control)


def execute_operation(request: OperationRequest, limits: ParseLimits) -> _rust.OperationResult:
    """Execute operation."""
    return _rust.execute_operation(request=request, limits=limits)


def execute_operation_controlled(
    request: OperationRequest,
    limits: ParseLimits,
    control: OperationControl,
) -> _rust.OperationResult:
    """The deadline covers normalization, registry selection, parsing, Rust analysis/merge and v."""
    return _rust.execute_operation_controlled(request=request, limits=limits, control=control)


def merge_python_declarations(
    requests: list[ParseRequest],
    limits: ParseLimits,
) -> _rust.NativeMergeResult:
    """Rust derives Python owners from LibCST facts and uses the same shared merge engine as YAM."""
    return _rust.merge_python_declarations(requests=requests, limits=limits)


def merge_python_declarations_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> _rust.NativeMergeResult:
    """Merge python declarations controlled."""
    return _rust.merge_python_declarations_controlled(requests=requests, limits=limits, control=control)


def merge_yaml_mapping(
    requests: list[ParseRequest],
    limits: ParseLimits,
) -> _rust.NativeMergeResult:
    """Experimental block-mapping profile. Native hosts provide syntax only; YAML analysis and s."""
    return _rust.merge_yaml_mapping(requests=requests, limits=limits)


def merge_yaml_mapping_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> _rust.NativeMergeResult:
    """Merge yaml mapping controlled."""
    return _rust.merge_yaml_mapping_controlled(requests=requests, limits=limits, control=control)


def native_merge_profiles() -> list[NativeMergeProfile]:
    """Does not load or probe parsers. A declared profile may be unavailable in a host until a c."""
    return _rust.native_merge_profiles()


def parse_sources(requests: list[ParseRequest], limits: ParseLimits) -> list[CoreParseResult]:
    """Parse sources."""
    return _rust.parse_sources(requests=requests, limits=limits)


def parse_sources_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> list[CoreParseResult]:
    """Parse sources controlled."""
    return _rust.parse_sources_controlled(requests=requests, limits=limits, control=control)


def plan_template_directory(options: TemplateSessionOptions) -> _rust.TemplateSessionPlanReport:
    """Read local template/destination directories and return a plan. No apply API is exposed he."""
    return _rust.plan_template_directory(options=options)


def register_parser_host(host: object) -> None:
    """Register parser host."""
    _rust.register_parser_host(host=host)


def report_structural_boundary() -> _rust.CrisprBoundaryReport:
    """Historical package responsibilities and coordinates, not supported-runtime declarations o."""
    return _rust.report_structural_boundary()


def report_structural_destination(
    request: CrisprDestinationRequest,
) -> _rust.CrisprDestinationReport:
    """Describe destination policy without resolving or mutating a destination."""
    return _rust.report_structural_destination(request=request)


def report_structural_limit(request: CrisprLimitRequest) -> _rust.CrisprLimitReport:
    """Report structural limit."""
    return _rust.report_structural_limit(request=request)


def report_structural_match(request: CrisprMatchRequest) -> _rust.CrisprMatchReport:
    """Describe match vocabulary without matching or selecting any source."""
    return _rust.report_structural_match(request=request)


def report_structural_operations(
    requests: list[CrisprOperationRequest],
) -> _rust.CrisprBatchOperationReport:
    """Describe structural operation profiles in input order using ast-crispr's shared classific."""
    return _rust.report_structural_operations(requests=requests)


def report_structural_selection(request: CrisprSelectionRequest) -> _rust.CrisprSelectionReport:
    """Describe selection vocabulary without executing a structural selector."""
    return _rust.report_structural_selection(request=request)


def report_template_options(options: TemplateSessionOptions) -> _rust.TemplateSessionRequestReport:
    """Report template options."""
    return _rust.report_template_options(options=options)


def report_template_profile(request: TemplateProfileRequest) -> _rust.TemplateSessionRequestReport:
    """Report template profile."""
    return _rust.report_template_profile(request=request)


def unregister_parser_host(
    id: str,  # noqa: A002
) -> None:
    """Unregister parser host."""
    _rust.unregister_parser_host(id=id)
