# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4b076bbb20ef0b2ee70db7a58ad7132dba8b22fd7a21d0943df30965fa99f16
# To regenerate: alef generate
# To verify freshness: alef verify
"""Configuration options for the conversion API."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from ._native import (
    DiagnosticCategory,  # noqa: TC001
    DiagnosticSeverity,  # noqa: TC001
    DirectorySessionMode,  # noqa: TC001
    ThreeWayMergeOutcome,  # noqa: TC001
)


class AttachmentHint(str, Enum):
    """Attachment hint."""

    leading = "leading"

    inline = "inline"

    trailing = "trailing"

    preamble = "preamble"

    postlude = "postlude"

    orphan = "orphan"

    unknown = "unknown"


class ConflictAlternativeState(str, Enum):
    """Conflict alternative state."""

    present = "present"

    absent = "absent"


class CrisprLimitOperator(str, Enum):
    """Crispr limit operator."""

    equal = "equal"

    not_equal = "not_equal"

    at_most = "at_most"

    at_least = "at_least"

    less_than = "less_than"

    greater_than = "greater_than"


class NodeRole(str, Enum):
    """Node role."""

    structural = "structural"

    token = "token"

    trivia = "trivia"

    comment = "comment"

    delimiter = "delimiter"

    separator = "separator"

    virtual = "virtual"

    error = "error"

    opaque = "opaque"


class OwnerChangeKind(str, Enum):
    """Owner change kind."""

    added = "added"

    deleted = "deleted"

    edited = "edited"


class ParseSeverity(str, Enum):
    """Parse severity."""

    info = "info"

    warning = "warning"

    error = "error"


class PolicySurface(str, Enum):
    """Policy surface."""

    fallback = "fallback"

    array = "array"


class ReviewDecisionAction(str, Enum):
    """Review decision action."""

    accept_default_context = "accept_default_context"

    provide_explicit_context = "provide_explicit_context"

    apply_delegated_child_group = "apply_delegated_child_group"


class ReviewDiagnosticReason(str, Enum):
    """Review diagnostic reason."""

    missing_required_payload = "missing_required_payload"

    family_mismatch = "family_mismatch"

    request_not_found = "request_not_found"


class SourceEncoding(str, Enum):
    """Source encoding."""

    utf8 = "utf8"

    binary = "binary"


class SourceRevision(str, Enum):
    """Source revision."""

    base = "base"

    ours = "ours"

    theirs = "theirs"


class SourceRole(str, Enum):
    """Source role."""

    source = "source"

    before = "before"

    after = "after"

    incoming = "incoming"

    current = "current"

    base = "base"

    ours = "ours"

    theirs = "theirs"

    output = "output"


class TemplateDirectoryPlanStatus(str, Enum):
    """Template directory plan status."""

    create = "create"

    update = "update"

    keep = "keep"

    blocked = "blocked"

    omitted = "omitted"


class TemplateExecutionAction(str, Enum):
    """Template execution action."""

    blocked = "blocked"

    omit = "omit"

    keep = "keep"

    raw_copy = "raw_copy"

    write_prepared_content = "write_prepared_content"

    merge_prepared_content = "merge_prepared_content"


class TemplateStrategy(str, Enum):
    """Template strategy."""

    merge = "merge"

    accept_template = "accept_template"

    keep_destination = "keep_destination"

    raw_copy = "raw_copy"


class TemplateTreeRunStatus(str, Enum):
    """Template tree run status."""

    created = "created"

    updated = "updated"

    kept = "kept"

    blocked = "blocked"

    omitted = "omitted"
