# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0bea433e3890dd6b68c6a644fdae3af42a327c25aa9d2b449c1eb17f6d54a8ad
# To regenerate: alef generate
# To verify freshness: alef verify
"""Configuration options for the conversion API."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any

from ._native import (
    DiagnosticCategory,  # noqa: TC001
    DiagnosticSeverity,  # noqa: TC001
    ThreeWayMergeOutcome,  # noqa: TC001
)
from . import _native

if TYPE_CHECKING:
    from ._native import (
        ParserSelection,  # noqa: F401
        SourceInput,  # noqa: F401
    )


class AttachmentHint(str, Enum):
    """Attachment hint."""

    leading = "leading"

    inline = "inline"

    trailing = "trailing"

    preamble = "preamble"

    postlude = "postlude"

    orphan = "orphan"

    unknown = "unknown"


class ConflictAlternativeState(str, Enum):
    """Conflict alternative state."""

    present = "present"

    absent = "absent"


class NodeRole(str, Enum):
    """Node role."""

    structural = "structural"

    token = "token"

    trivia = "trivia"

    comment = "comment"

    delimiter = "delimiter"

    separator = "separator"

    virtual = "virtual"

    error = "error"

    opaque = "opaque"


class ParseSeverity(str, Enum):
    """Parse severity."""

    info = "info"

    warning = "warning"

    error = "error"


class PolicySurface(str, Enum):
    """Policy surface."""

    fallback = "fallback"

    array = "array"


class ReviewDecisionAction(str, Enum):
    """Review decision action."""

    accept_default_context = "accept_default_context"

    provide_explicit_context = "provide_explicit_context"

    apply_delegated_child_group = "apply_delegated_child_group"


class ReviewDiagnosticReason(str, Enum):
    """Review diagnostic reason."""

    missing_required_payload = "missing_required_payload"

    family_mismatch = "family_mismatch"

    request_not_found = "request_not_found"


class SourceEncoding(str, Enum):
    """Source encoding."""

    utf8 = "utf8"

    binary = "binary"


class SourceRevision(str, Enum):
    """Source revision."""

    base = "base"

    ours = "ours"

    theirs = "theirs"


class SourceRole(str, Enum):
    """Source role."""

    source = "source"

    before = "before"

    after = "after"

    incoming = "incoming"

    current = "current"

    base = "base"

    ours = "ours"

    theirs = "theirs"

    output = "output"


@dataclass(frozen=True, slots=True)
class ParseOptions:
    """Parse options."""

    comments: bool = False

    tokens: bool = False

    diagnostics: bool = False

    native_extensions: bool = False

    @staticmethod
    def from_json(json_str: str) -> ParseOptions:
        """Build a ParseOptions from a JSON string, via the native binding."""
        return _from_native_parse_options(_native.ParseOptions.from_json(json_str))


@dataclass(frozen=True, slots=True)
class ParseRequest:
    """Parse request."""

    schema: str

    request_id: str

    source: SourceInput

    language: str

    selection: ParserSelection

    options: ParseOptions

    metadata: dict[str, str]

    extra: dict[str, str]

    dialect: str | None = None

    @staticmethod
    def from_json(json_str: str) -> ParseRequest:
        """Build a ParseRequest from a JSON string, via the native binding."""
        return _from_native_parse_request(_native.ParseRequest.from_json(json_str))


def _from_native_parse_options(native: Any) -> ParseOptions:
    """Build the public `ParseOptions` dataclass from the native binding object."""
    return ParseOptions(
        comments=native.comments,
        tokens=native.tokens,
        diagnostics=native.diagnostics,
        native_extensions=native.native_extensions,
    )


def _from_native_parse_request(native: Any) -> ParseRequest:
    """Build the public `ParseRequest` dataclass from the native binding object."""
    return ParseRequest(
        schema=native.schema,
        request_id=native.request_id,
        source=native.source,
        language=native.language,
        dialect=native.dialect,
        selection=native.selection,
        options=_from_native_parse_options(native.options),
        metadata=native.metadata,
        extra=native.extra,
    )
