# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d6fc57bbcce4c50eb56fe7ce81b99e7b397a46b5f491b489bd56b2ebc3c4775
# To regenerate: alef generate
# To verify freshness: alef verify
"""Configuration options for the conversion API."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any

from ._native import (
    DiagnosticCategory,  # noqa: TC001
    DiagnosticSeverity,  # noqa: TC001
    SourceEncoding,  # noqa: TC001
    SourceRole,  # noqa: TC001
    ThreeWayMergeOutcome,  # noqa: TC001
)
from . import _native

if TYPE_CHECKING:
    from ._native import (
        NativeExtension,  # noqa: F401
        ParseComment,  # noqa: F401
        ParseDiagnostic,  # noqa: F401
        ParseNode,  # noqa: F401
        ParserSelection,  # noqa: F401
        SourceInput,  # noqa: F401
    )


class AttachmentHint(str, Enum):
    """Attachment hint."""

    leading = "leading"

    inline = "inline"

    trailing = "trailing"

    preamble = "preamble"

    postlude = "postlude"

    orphan = "orphan"

    unknown = "unknown"


class ConflictAlternativeState(str, Enum):
    """Conflict alternative state."""

    present = "present"

    absent = "absent"


class NodeRole(str, Enum):
    """Node role."""

    structural = "structural"

    token = "token"

    trivia = "trivia"

    comment = "comment"

    delimiter = "delimiter"

    separator = "separator"

    virtual = "virtual"

    error = "error"

    opaque = "opaque"


class ParseSeverity(str, Enum):
    """Parse severity."""

    info = "info"

    warning = "warning"

    error = "error"


class PolicySurface(str, Enum):
    """Policy surface."""

    fallback = "fallback"

    array = "array"


class ReviewDecisionAction(str, Enum):
    """Review decision action."""

    accept_default_context = "accept_default_context"

    provide_explicit_context = "provide_explicit_context"

    apply_delegated_child_group = "apply_delegated_child_group"


class ReviewDiagnosticReason(str, Enum):
    """Review diagnostic reason."""

    missing_required_payload = "missing_required_payload"

    family_mismatch = "family_mismatch"

    request_not_found = "request_not_found"


class SourceRevision(str, Enum):
    """Source revision."""

    base = "base"

    ours = "ours"

    theirs = "theirs"


@dataclass(frozen=True, slots=True)
class LineEndings:
    """Line endings."""

    lf: int = 0

    crlf: int = 0

    bare_cr: int = 0

    @staticmethod
    def from_json(json_str: str) -> LineEndings:
        """Build a LineEndings from a JSON string, via the native binding."""
        return _from_native_line_endings(_native.LineEndings.from_json(json_str))


@dataclass(frozen=True, slots=True)
class ParseOptions:
    """Parse options."""

    comments: bool = False

    tokens: bool = False

    diagnostics: bool = False

    native_extensions: bool = False

    @staticmethod
    def from_json(json_str: str) -> ParseOptions:
        """Build a ParseOptions from a JSON string, via the native binding."""
        return _from_native_parse_options(_native.ParseOptions.from_json(json_str))


@dataclass(frozen=True, slots=True)
class ParseOutput:
    """Parser payload. TreeHaver's service adds validated backend and selection evidence. It is ."""

    request_id: str

    source: SourceDescriptor

    ok: bool

    nodes: list[ParseNode]

    comments: list[ParseComment]

    diagnostics: list[ParseDiagnostic]

    extensions: list[NativeExtension]

    metadata: dict[str, str]

    extra: dict[str, str]

    root_id: str | None = None

    @staticmethod
    def from_json(json_str: str) -> ParseOutput:
        """Build a ParseOutput from a JSON string, via the native binding."""
        return _from_native_parse_output(_native.ParseOutput.from_json(json_str))


@dataclass(frozen=True, slots=True)
class ParseRequest:
    """Parse request."""

    schema: str

    request_id: str

    source: SourceInput

    language: str

    selection: ParserSelection

    options: ParseOptions

    metadata: dict[str, str]

    extra: dict[str, str]

    dialect: str | None = None

    @staticmethod
    def from_json(json_str: str) -> ParseRequest:
        """Build a ParseRequest from a JSON string, via the native binding."""
        return _from_native_parse_request(_native.ParseRequest.from_json(json_str))


@dataclass(frozen=True, slots=True)
class SourceDescriptor:
    """Source descriptor."""

    source_id: str

    role: SourceRole | str

    byte_length: int

    sha256: str

    encoding: SourceEncoding | str

    bom: bool

    line_endings: LineEndings

    final_newline: bool

    @staticmethod
    def from_json(json_str: str) -> SourceDescriptor:
        """Build a SourceDescriptor from a JSON string, via the native binding."""
        return _from_native_source_descriptor(_native.SourceDescriptor.from_json(json_str))


def _from_native_line_endings(native: Any) -> LineEndings:
    """Build the public `LineEndings` dataclass from the native binding object."""
    return LineEndings(
        lf=native.lf,
        crlf=native.crlf,
        bare_cr=native.bare_cr,
    )


def _from_native_parse_options(native: Any) -> ParseOptions:
    """Build the public `ParseOptions` dataclass from the native binding object."""
    return ParseOptions(
        comments=native.comments,
        tokens=native.tokens,
        diagnostics=native.diagnostics,
        native_extensions=native.native_extensions,
    )


def _from_native_parse_output(native: Any) -> ParseOutput:
    """Build the public `ParseOutput` dataclass from the native binding object."""
    return ParseOutput(
        request_id=native.request_id,
        source=_from_native_source_descriptor(native.source),
        ok=native.ok,
        root_id=native.root_id,
        nodes=native.nodes,
        comments=native.comments,
        diagnostics=native.diagnostics,
        extensions=native.extensions,
        metadata=native.metadata,
        extra=native.extra,
    )


def _from_native_parse_request(native: Any) -> ParseRequest:
    """Build the public `ParseRequest` dataclass from the native binding object."""
    return ParseRequest(
        schema=native.schema,
        request_id=native.request_id,
        source=native.source,
        language=native.language,
        dialect=native.dialect,
        selection=native.selection,
        options=_from_native_parse_options(native.options),
        metadata=native.metadata,
        extra=native.extra,
    )


def _from_native_source_descriptor(native: Any) -> SourceDescriptor:
    """Build the public `SourceDescriptor` dataclass from the native binding object."""
    return SourceDescriptor(
        source_id=native.source_id,
        role=native.role,
        byte_length=native.byte_length,
        sha256=native.sha256,
        encoding=native.encoding,
        bom=native.bom,
        line_endings=_from_native_line_endings(native.line_endings),
        final_newline=native.final_newline,
    )
