# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8d98763b53b71a72e5fe0353c2a5ff6900709b2a261d8f36e19ff4b0ddf1fd5b
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'bash_common_merge3' do

  it 'bash_merge3_conflict: Shared typed Bash merge3 contract: bash_merge3_conflict' do
    result = NativeMergeFixture.run_bash_common_merge3("x=1\n", "x=2\n", "x=3\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)

  end


  it 'bash_merge3_independent: Shared typed Bash merge3 contract: bash_merge3_independent' do
    result = NativeMergeFixture.run_bash_common_merge3("x=1\ny=1\n", "x=2\ny=1\n", "x=1\ny=2\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("x=2\ny=2\n")
    expect(result.verification.base_participated).to be(true)

  end


  it 'bash_merge3_noop: Shared typed Bash merge3 contract: bash_merge3_noop' do
    result = NativeMergeFixture.run_bash_common_merge3("\# é\nx=1", "\# é\nx=1", "\# é\nx=1")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("\# é\nx=1")
    expect(result.verification.output_reparsed).to be(true)

  end

end
