# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0108d9e76e9454f90a818aef6493005555fe41fa62ab185a2497c84b650aaa6
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'bash_common_analyze' do

  it 'bash_analysis: Shared typed Bash analyze contract: bash_analysis' do
    result = NativeMergeFixture.run_bash_common_analyze("\# é\nx=1\n\nf() { :; }\n")
    expect(result.ok).to be(true)
    expect(result.analysis.extra["owners"].to_s).to include('/function:f')
    expect(result.analysis.extra["owners"].to_s).to include('node_ids')

  end


  it 'bash_analysis_rejected: Shared typed Bash analyze contract: bash_analysis_rejected' do
    result = NativeMergeFixture.run_bash_common_analyze("echo unsupported\n")
    expect(result.ok).to be(false)
    expect(result.analysis).to eq(nil)

  end

end
