# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1f3cbafe0ad525a1ff9af940efb79e9dd1f0dc5d450b4893d58ac2dddbd4e758
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'bash_common_diff' do

  it 'bash_diff_owner: Shared typed Bash diff contract: bash_diff_owner' do
    result = NativeMergeFixture.run_bash_common_diff("x=1\nf() { :; }\n", "x=2\nf() { :; }\n")
    expect(result.ok).to be(true)
    expect(result.changes[0].path.to_s).to eq('/variable:x')
    expect(result.changes.length).to eq(2)

  end


  it 'bash_diff_trivia: Shared typed Bash diff contract: bash_diff_trivia' do
    result = NativeMergeFixture.run_bash_common_diff("\# before\nx=1\n", "\# after\nx=1\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(1)
    expect(result.changes[0].subject_ref.to_s).to eq('document')

  end

end
