# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c67a3cadc9ffd8c2844cc16ce9fd363d78a0e337061628905d0ddba2e789bbd0
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'git_common_merge3' do

  it 'git_clean_json: Typed Git common-profile contract: git_clean_json' do
    result = NativeMergeFixture.run_git_common_merge3('json', '{"x":0,"y":0}', '{"x":1,"y":0}', '{"x":0,"y":2}', 7, 'ours')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq('{"x":1,"y":2}')
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'git_clean_json5: Typed Git common-profile contract: git_clean_json5' do
    result = NativeMergeFixture.run_git_common_merge3('json5', "{x:'é',}\r\n", "{x:'é',}\r\n", "{x:'雪',}\r\n", 7, 'ours')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("{x:'雪',}\r\n")

  end


  it 'git_clean_jsonc: Typed Git common-profile contract: git_clean_jsonc' do
    result = NativeMergeFixture.run_git_common_merge3('jsonc', '{/*é*/"x":0}', '{/*é*/"x":0}', '{/*é*/"x":2}', 7, 'ours')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq('{/*é*/"x":2}')
    expect(result.verification.base_participated).to be(true)

  end


  it 'git_conflict_absent: Deleted ours owner remains unresolved with an empty-side appended review block, not merged output' do
    result = NativeMergeFixture.run_git_common_merge3('json', '{"x":0}', '{}', '{"x":2}', 7, 'ours')
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicted_output.to_s).to eq("{}\n<<<<<<< ours\n||||||| base\n{\"x\":0}\n=======\n{\"x\":2}\n>>>>>>> theirs\n")
    expect(result.conflicts.length).to eq(1)
    expect(result.render_report["strategy"].to_s).to include('git-absent-owner-conflict-review')

  end


  it 'git_conflict_custom: Typed Git common-profile contract: git_conflict_custom' do
    result = NativeMergeFixture.run_git_common_merge3('json', "{\r\n\"x\":0\r\n}\r\n", "{\r\n\"x\":1\r\n}\r\n", "{\r\n\"x\":2\r\n}\r\n", 9, 'local-é')
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicted_output.to_s).to include("<<<<<<<<< local-é\n")
    expect(result.conflicted_output.to_s).to include("\"x\":1\r\n")
    expect(result.verification.output_reparsed).to eq(nil)
    expect(result.conflicts[0].canonical.alternatives.length).to eq(3)
    expect(result.render_report["outside_conflicts"].to_s).to include('ours-not-partially-merged')

  end


  it 'git_conflict_mixed: Typed Git common-profile contract: git_conflict_mixed' do
    result = NativeMergeFixture.run_git_common_merge3('json', "{\n\"x\":0,\n\"other\":0\n}\n", "{\n\"x\":1,\n\"other\":0\n}\n", "{\n\"x\":2,\n\"other\":9\n}\n", 7, 'ours')
    expect(result.ok).to be(false)
    expect(result.conflicted_output.to_s).to include("\"other\":0\n}\n")
    expect(result.render_report["artifact_kind"].to_s).to include('unresolved-conflict-review')

  end


  it 'git_conflict_overlap: Typed Git common-profile contract: git_conflict_overlap' do
    result = NativeMergeFixture.run_git_common_merge3('json', '{"x":0,"y":0}', '{"x":1,"y":1}', '{"x":2,"y":2}', 7, 'ours')
    expect(result.ok).to be(false)
    expect(result.conflicted_output).to eq(nil)
    expect(result.conflicts.length).to eq(2)
    expect(result.render_report["render_error"].to_s).to include('overlaps')

  end


  it 'git_invalid_label: Typed Git common-profile contract: git_invalid_label' do
    result = NativeMergeFixture.run_git_common_merge3('json', '{}', '{}', '{}', 7, "bad\nlabel")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.verification.classification_reached).to be(false)

  end


  it 'git_invalid_width: Typed Git common-profile contract: git_invalid_width' do
    result = NativeMergeFixture.run_git_common_merge3('json', '{}', '{}', '{}', 1025, 'ours')
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)

  end

end
