# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc7046accf3ccfaaa355dc579f762374a3551dbf937ce43ac573abaf4a6893e6
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'go_common_diff' do

  it 'go_diff_header: Shared typed Go diff contract: go_diff_header' do
    result = NativeMergeFixture.run_go_common_diff("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n", "package other\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(1)
    expect(result.changes[0].subject_ref.to_s).to eq('document')

  end


  it 'go_diff_owner: Shared typed Go diff contract: go_diff_owner' do
    result = NativeMergeFixture.run_go_common_diff("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n", "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(2)
    expect(result.changes[0].path.to_s).to eq('/function:f')

  end

end
