# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d00ce66563609a5dd08bb6615c4b30f1dca3597728b4e21a05e8efcb5515aee4
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'go_common_merge2' do

  it 'go_merge2_comments: Shared typed Go merge2 contract: go_merge2_comments' do
    result = NativeMergeFixture.run_go_common_merge2("package main\n\n// é new\nfunc added() {}\nfunc f() {}\n", "// module\npackage main\n\n// f\nfunc f() {}\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("// module\npackage main\n\n// é new\nfunc added() {}\n\n// f\nfunc f() {}\n// footer\n")

  end


  it 'go_merge2_current: Shared typed Go merge2 contract: go_merge2_current' do
    result = NativeMergeFixture.run_go_common_merge2("package main\nfunc f() { println(1) }\nfunc g() {}\n", "package main\nfunc f() { println(9) }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("package main\nfunc f() { println(9) }\nfunc g() {}\n")
    expect(result.verification.directional_roles_preserved).to be(true)
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'go_merge2_import_rejected: Shared typed Go merge2 contract: go_merge2_import_rejected' do
    result = NativeMergeFixture.run_go_common_merge2("package main\nimport \"fmt\"\nfunc g() { fmt.Println(1) }\n", "package main\nfunc f() {}\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)

  end


  it 'go_merge2_package_only: Shared typed Go merge2 contract: go_merge2_package_only' do
    result = NativeMergeFixture.run_go_common_merge2("package main\n// f\nfunc f() {}\n", "package main\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("package main\n// f\nfunc f() {}\n// footer\n")
    expect(result.verification.output_reparsed).to be(true)

  end

end
