# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:80d3d1c6f5c4a065d28c90fda5ab764d41623c9e0434c1c95aa9514148613d48
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'json_common_merge3' do

  it 'json_merge3_conflict: Overlapping JSON edits retain a canonical conflict with all revision alternatives.' do
    result = NativeMergeFixture.run_json_common_merge3('json', '{"a":1}', '{"a":2}', '{"a":3}')
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)
    expect(result.conflicts[0].canonical.alternatives.length).to eq(3)

  end


  it 'json_merge3_independent: Independent JSON changes merge in Rust and require output verification.' do
    result = NativeMergeFixture.run_json_common_merge3('json', '{"a":1,"b":2}', '{"a":3,"b":2}', '{"a":1,"b":4}')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq('{"a":3,"b":4}')
    expect(result.verification.base_participated).to be(true)
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'json_merge3_selected_bytes: Selected JSON5 input retains Unicode, comment, CRLF and no-final-newline bytes.' do
    result = NativeMergeFixture.run_json_common_merge3('json5', '{x:1}', '{x:1}', "// chosen\r\n{x:'é'}")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("// chosen\r\n{x:'é'}")
    expect(result.verification.output_reparsed).to be(true)

  end

end
