# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:45ad6b8d44248d18de4af00f2867c9d74f2312518a720ac6ed23750fec71a17f
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'json_common_diff' do

  it 'json_diff_nested: Repeated identical fragments retain the changed nested owner path.' do
    result = NativeMergeFixture.run_json_common_diff('json', '{"a":{"x":1},"b":{"x":1}}', '{"a":{"x":1},"b":{"x":2}}')
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(4)
    expect(result.changes[3].path.to_s).to eq('/b/x')
    expect(result.changes[3].classification.to_s).to eq('edited')
    expect(result.output).to eq(nil)

  end


  it 'json_diff_noop: Identical Unicode JSON documents report no changes.' do
    result = NativeMergeFixture.run_json_common_diff('json', '{"é":1}', '{"é":1}')
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(0)
    expect(result.output).to eq(nil)

  end


  it 'json_diff_trivia: Document comparison covers comment and newline edits outside syntax owners.' do
    result = NativeMergeFixture.run_json_common_diff('json5', "// before\n{}", "// after\n{}\r\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(1)
    expect(result.changes[0].subject_ref.to_s).to eq('json.document')
    expect(result.output).to eq(nil)

  end

end
