# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dbded6e0897b6db28fe923e3ff0fc8517cf844f24e78bc69a8c8e60bc1594be6
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'native_profiles' do

  it 'native_profiles_are_explicitly_experimental: Scoped Rust merge profiles expose their identity and do not claim default approval.' do
    result = NativeMergeFixture.native_merge_profiles()
    expect(result.length).to eq(2)
    expect(result[0].id.to_s).to eq('kernel.python.native_declarations.v1')
    expect(result[1].id.to_s).to eq('kernel.yaml.native_mapping.v1')
    expect(result[0].semantic_runtime.to_s).to eq('rust')
    expect(result[1].semantic_runtime.to_s).to eq('rust')
    expect(result[0].experimental).to be(true)
    expect(result[1].experimental).to be(true)
    expect(result[0].approved_as_default).to be(false)
    expect(result[1].approved_as_default).to be(false)

  end

end
