# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f60817eb23d7a14280bb86e6d1adda67cfc939d5c7ac65553fa54fd366c6ff18
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'rust_common_merge3' do

  it 'rust_merge3_conflict: Shared typed Rust merge3: merge3_conflict' do
    result = NativeMergeFixture.run_rust_common_merge3("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 3 }\nfn g() -> i32 { 1 }\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)

  end


  it 'rust_merge3_guard: Shared typed Rust merge3: merge3_guard' do
    result = NativeMergeFixture.run_rust_common_merge3("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\nfn added() {}\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)
    expect(result.conflicts[0].canonical.code.to_s).to eq('rust.membership_with_owner_edit')
    expect(result.conflicts[0].canonical.subject.whole_document).to be(true)
    expect(result.conflicts[0].canonical.decision_ids.length).to eq(0)
    expect(result.verification.base_participated).to be(true)

  end


  it 'rust_merge3_guard_shortcut: Shared typed Rust merge3: merge3_guard_shortcut' do
    result = NativeMergeFixture.run_rust_common_merge3("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\nfn added() {}\n", "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts[0].canonical.code.to_s).to eq('rust.membership_with_owner_edit')
    expect(result.conflicts[0].canonical.decision_ids.length).to eq(0)

  end


  it 'rust_merge3_independent: Shared typed Rust merge3: merge3_independent' do
    result = NativeMergeFixture.run_rust_common_merge3("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 2 }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 2 }\n")
    expect(result.verification.output_reparsed).to be(true)
    expect(result.verification.base_participated).to be(true)

  end


  it 'rust_merge3_noop: Shared typed Rust merge3: merge3_noop' do
    result = NativeMergeFixture.run_rust_common_merge3("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n")
    expect(result.verification.output_reparsed).to be(true)

  end

end
