# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:18d03a87054925aa0ee592bf26fae6759179b8b39fc4001ea51fcd1d9479eb4d
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'rust_common_analyze' do

  it 'rust_analysis: Shared typed Rust analyze: analysis' do
    result = NativeMergeFixture.run_rust_common_analyze("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n")
    expect(result.ok).to be(true)
    expect(result.analysis.extra["owners"].to_s).to include('/function:f')
    expect(result.analysis.extra["owners"].to_s).to include('node_ids')

  end


  it 'rust_analysis_rejected: Shared typed Rust analyze: analysis_rejected' do
    result = NativeMergeFixture.run_rust_common_analyze("\#[test]\nfn f() {}\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)

  end

end
