# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ade983b12017d6e5554d8418cdf9258c26d16094a42b84b0578cda131132ee95
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'rust_common_merge2' do

  it 'rust_merge2_current: Shared typed Rust merge2: merge2_current' do
    result = NativeMergeFixture.run_rust_common_merge2("fn f() { incoming(); }\nfn g() {}\n", "fn f() { current(); }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("fn f() { current(); }\nfn g() {}\n")
    expect(result.verification.output_reparsed).to be(true)
    expect(result.verification.directional_roles_preserved).to be(true)

  end


  it 'rust_merge2_docs: Shared typed Rust merge2: merge2_docs' do
    result = NativeMergeFixture.run_rust_common_merge2("//! incoming module\n/// é added\nfn added() {}\nfn f() {}\n", "//! current module\n/// current f\nfn f() {} // inline\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("//! current module\n/// é added\nfn added() {}\n/// current f\nfn f() {} // inline\n// footer\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'rust_merge2_empty: Shared typed Rust merge2: merge2_empty' do
    result = NativeMergeFixture.run_rust_common_merge2("struct T;\n", '')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("struct T;\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'rust_merge2_interleaved: Shared typed Rust merge2: merge2_interleaved' do
    result = NativeMergeFixture.run_rust_common_merge2("fn f() {}\nuse std::fmt;\n// added\nfn g() {}\n", "use std::fmt;\nfn f() { current(); }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("use std::fmt;\nfn f() { current(); }\n// added\nfn g() {}\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'rust_merge2_use_only: Shared typed Rust merge2: merge2_use_only' do
    result = NativeMergeFixture.run_rust_common_merge2("use std::fmt;\n/// first\nfn f() {}\n", "use std::fmt;\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("use std::fmt;\n/// first\nfn f() {}\n// footer\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'rust_merge2_use_rejected: Shared typed Rust merge2: merge2_use_rejected' do
    result = NativeMergeFixture.run_rust_common_merge2("use std::io;\nfn g() {}\n", "use std::fmt;\nfn f() {}\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)

  end

end
