# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3a05a107bcb6ea83659dec9a03fee39ae12b0d595e73b9bb2d23f94fd9f623a3
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'typescript_common_analyze' do

  it 'tsx_analysis: Shared typed tsx analyze: analysis' do
    result = NativeMergeFixture.run_typescript_common_analyze('tsx', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.analysis.extra["owners"].to_s).to include('/function:f')
    expect(result.analysis.extra["owners"].to_s).to include('node_ids')

  end


  it 'tsx_analysis_rejected: Shared typed tsx analyze: analysis_rejected' do
    result = NativeMergeFixture.run_typescript_common_analyze('tsx', "export const v = 1;\n")
    expect(result.ok).to be(false)

  end


  it 'tsx_jsx_analysis: Shared tsx grammar jsx_analysis' do
    result = NativeMergeFixture.run_typescript_common_analyze('tsx', "function View() { return <div/>; }\n")
    expect(result.ok).to be(true)
    expect(result.analysis.extra["owners"].to_s).to include('/function:View')

  end


  it 'typescript_analysis: Shared typed typescript analyze: analysis' do
    result = NativeMergeFixture.run_typescript_common_analyze('typescript', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.analysis.extra["owners"].to_s).to include('/function:f')
    expect(result.analysis.extra["owners"].to_s).to include('node_ids')

  end


  it 'typescript_analysis_rejected: Shared typed typescript analyze: analysis_rejected' do
    result = NativeMergeFixture.run_typescript_common_analyze('typescript', "export const v = 1;\n")
    expect(result.ok).to be(false)

  end


  it 'typescript_jsx_rejected: Shared typescript grammar jsx_rejected' do
    result = NativeMergeFixture.run_typescript_common_analyze('typescript', "function View() { return <div/>; }\n")
    expect(result.ok).to be(false)

  end

end
