# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:810554e4c2e76042e391cb3ecafcbca4ff9cd415e9983bb69c377f30d3712376
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'typescript_common_diff' do

  it 'tsx_diff_import: Shared typed tsx diff: diff_import' do
    result = NativeMergeFixture.run_typescript_common_diff('tsx', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'y';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(1)
    expect(result.changes[0].subject_ref.to_s).to eq('document')

  end


  it 'tsx_diff_owner: Shared typed tsx diff: diff_owner' do
    result = NativeMergeFixture.run_typescript_common_diff('tsx', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(2)
    expect(result.changes[0].path.to_s).to eq('/function:f')

  end


  it 'typescript_diff_import: Shared typed typescript diff: diff_import' do
    result = NativeMergeFixture.run_typescript_common_diff('typescript', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'y';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(1)
    expect(result.changes[0].subject_ref.to_s).to eq('document')

  end


  it 'typescript_diff_owner: Shared typed typescript diff: diff_owner' do
    result = NativeMergeFixture.run_typescript_common_diff('typescript', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(2)
    expect(result.changes[0].path.to_s).to eq('/function:f')

  end

end
