# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27536da858efadde312ba9b49419195698805e1a44322cdfbc5ce3651469ff8b
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'typescript_common_merge2' do

  it 'tsx_jsx_merge2: Shared tsx grammar jsx_merge2' do
    result = NativeMergeFixture.run_typescript_common_merge2('tsx', "function View() { return <div/>; }\n", '')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("function View() { return <div/>; }\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'tsx_merge2_comments: Shared typed tsx merge2: merge2_comments' do
    result = NativeMergeFixture.run_typescript_common_merge2('tsx', "import { x } from 'x';\n/** é added */\nexport class C {}\n", "// module\nimport { x } from 'x';\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("// module\nimport { x } from 'x';\n/** é added */\nexport class C {}\n// footer\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'tsx_merge2_current: Shared typed tsx merge2: merge2_current' do
    result = NativeMergeFixture.run_typescript_common_merge2('tsx', "function f() { incoming(); }\nfunction g() {}\n", "function f() { current(); }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("function f() { current(); }\nfunction g() {}\n")
    expect(result.verification.output_reparsed).to be(true)
    expect(result.verification.directional_roles_preserved).to be(true)

  end


  it 'tsx_merge2_header: Shared typed tsx merge2: merge2_header' do
    result = NativeMergeFixture.run_typescript_common_merge2('tsx', "// incoming header\nexport function added() {}\nfunction f() {}\n", "// @ts-nocheck\nfunction f() {}\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("// @ts-nocheck\nexport function added() {}\nfunction f() {}\n// footer\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'tsx_merge2_interleaved: Shared typed tsx merge2: merge2_interleaved' do
    result = NativeMergeFixture.run_typescript_common_merge2('tsx', "function f() {}\nimport { x } from 'x';\n// added\nconst added = 1;\n", "import { x } from 'x';\nfunction f() {}\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("import { x } from 'x';\nfunction f() {}\n// added\nconst added = 1;\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'tsx_merge2_rejected: Shared typed tsx merge2: merge2_rejected' do
    result = NativeMergeFixture.run_typescript_common_merge2('tsx', "import { x } from 'x';\nfunction added() {}\n", "import { x } from 'y';\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)

  end


  it 'typescript_merge2_comments: Shared typed typescript merge2: merge2_comments' do
    result = NativeMergeFixture.run_typescript_common_merge2('typescript', "import { x } from 'x';\n/** é added */\nexport class C {}\n", "// module\nimport { x } from 'x';\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("// module\nimport { x } from 'x';\n/** é added */\nexport class C {}\n// footer\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'typescript_merge2_current: Shared typed typescript merge2: merge2_current' do
    result = NativeMergeFixture.run_typescript_common_merge2('typescript', "function f() { incoming(); }\nfunction g() {}\n", "function f() { current(); }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("function f() { current(); }\nfunction g() {}\n")
    expect(result.verification.output_reparsed).to be(true)
    expect(result.verification.directional_roles_preserved).to be(true)

  end


  it 'typescript_merge2_header: Shared typed typescript merge2: merge2_header' do
    result = NativeMergeFixture.run_typescript_common_merge2('typescript', "// incoming header\nexport function added() {}\nfunction f() {}\n", "// @ts-nocheck\nfunction f() {}\n// footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("// @ts-nocheck\nexport function added() {}\nfunction f() {}\n// footer\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'typescript_merge2_interleaved: Shared typed typescript merge2: merge2_interleaved' do
    result = NativeMergeFixture.run_typescript_common_merge2('typescript', "function f() {}\nimport { x } from 'x';\n// added\nconst added = 1;\n", "import { x } from 'x';\nfunction f() {}\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("import { x } from 'x';\nfunction f() {}\n// added\nconst added = 1;\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'typescript_merge2_rejected: Shared typed typescript merge2: merge2_rejected' do
    result = NativeMergeFixture.run_typescript_common_merge2('typescript', "import { x } from 'x';\nfunction added() {}\n", "import { x } from 'y';\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)

  end

end
