# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37121cc896ed5f82142f3a267358f63edcbfcfe6e9f60dcd0fc2a7ce2bf38159
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'yaml_common_diff' do

  it 'yaml_common_diff: Common typed diff through the installed binding, using native parser facts and Rust-owned semantics.' do
    result = NativeMergeFixture.run_yaml_common_diff("alpha: one\nbeta: two\n", "alpha: ours\nbeta: two\n")
    expect(result.schema.to_s).to eq('https://structuredmerge.org/schemas/provider-result/v1.json')
    expect(result.request_id.to_s).to eq('typed-common-diff2')
    expect(result.provider.provider_id.to_s).to eq('kernel.yaml')
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(1)
    expect(result.conflicts.length).to eq(0)

  end

end
