# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0eab5f7fde6647d5372a765dbe0930107b9b993c0a8c8ae6941ddebc6cf88f66
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'yaml_common_analyze' do

  it 'yaml_common_analyze: Common typed analyze through the installed binding, using native parser facts and Rust-owned semantics.' do
    result = NativeMergeFixture.run_yaml_common_analyze("alpha: one\nbeta: two\n")
    expect(result.schema.to_s).to eq('https://structuredmerge.org/schemas/provider-result/v1.json')
    expect(result.request_id.to_s).to eq('typed-common-analyze')
    expect(result.provider.provider_id.to_s).to eq('kernel.yaml')
    expect(result.ok).to be(true)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(0)

  end


  it 'yaml_common_syntax_failure: Common typed analyze through the installed binding, using native parser facts and Rust-owned semantics.' do
    result = NativeMergeFixture.run_yaml_common_analyze("alpha: [\n")
    expect(result.schema.to_s).to eq('https://structuredmerge.org/schemas/provider-result/v1.json')
    expect(result.request_id.to_s).to eq('typed-common-analyze')
    expect(result.provider.provider_id.to_s).to eq('kernel.yaml')
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.diagnostics.length).to eq(1)

  end

end
