# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:efb41cfbbc0846dce328b0e43c7d747f47dc00090b62c9e2962d8c0d416234a9
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'yaml_native_merge' do

  it 'yaml_native_conflicting_entry: Concurrent edits to one mapping entry retain a conflict without rendered output.' do
    result = NativeMergeFixture.run_yaml_native_merge("alpha: one\n", "alpha: ours\n", "alpha: theirs\n")
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)
    expect(result.input_parses.length).to eq(3)
    expect(result.source_segments.length).to eq(0)

  end


  it 'yaml_native_independent_entries: Psych supplies parse facts; Rust combines independent mapping edits.' do
    result = NativeMergeFixture.run_yaml_native_merge("alpha: one\nbeta: two\n", "alpha: ours\nbeta: two\n", "alpha: one\nbeta: theirs\n")
    expect(result.profile_id.to_s).to eq('kernel.yaml.native_mapping.v1')
    expect(result.output.to_s).to eq("alpha: ours\nbeta: theirs\n")
    expect(result.input_parses.length).to eq(3)
    expect(result.conflicts.length).to eq(0)

  end


  it 'yaml_native_syntax_failure: Psych syntax rejection retains input parse evidence without rendered output.' do
    result = NativeMergeFixture.run_yaml_native_merge("alpha: one\n", "alpha: [\n", "alpha: theirs\n")
    expect(result.output).to eq(nil)
    expect(result.input_parses.length).to eq(3)
    expect(result.source_segments.length).to eq(0)
    expect(result.rejected_parse.parsed.ok).to be(false)

  end


  it 'yaml_native_unsupported_sequence: A valid top-level sequence fails closed in the explicitly scoped mapping profile.' do
    result = NativeMergeFixture.run_yaml_native_merge("alpha: one\n", "- unsupported\n", "alpha: theirs\n")
    expect(result.output).to eq(nil)
    expect(result.rejected_parse).to eq(nil)
    expect(result.input_parses.length).to eq(3)
    expect(result.analysis_rejections.length).to eq(1)

  end


  it 'yaml_native_utf8_bom_crlf_no_final_newline: Mapping edits preserve BOM, Unicode, CRLF, comments, and absent final newline.' do
    result = NativeMergeFixture.run_yaml_native_merge("﻿\# header\r\né: 'one'  \# stable\r\nbeta: two", "﻿\# header\r\né: 'ours'  \# stable\r\nbeta: two", "﻿\# header\r\né: 'one'  \# stable\r\nbeta: theirs")
    expect(result.output.to_s).to eq("﻿\# header\r\né: 'ours'  \# stable\r\nbeta: theirs")
    expect(result.output_source.bom).to be(true)
    expect(result.output_source.final_newline).to be(false)
    expect(result.output_source.line_endings.crlf).to eq(2)

  end

end
