//! Pure build identity rendering, shared with tests. No Git/package discovery.
use std::collections::BTreeMap;

pub fn render(environment: &BTreeMap<String, String>) -> Result<String, String> {
    let required = |name: &str| {
        environment
            .get(name)
            .filter(|s| !s.is_empty())
            .ok_or_else(|| format!("missing Cargo build variable {name}"))
    };
    let mut output = String::from("// Generated by smorg build.rs; do not edit.\n");
    for (name, variable) in [
        ("TARGET", "TARGET"),
        ("HOST", "HOST"),
        ("PROFILE", "PROFILE"),
        ("OPT_LEVEL", "OPT_LEVEL"),
        ("DEBUG", "DEBUG"),
    ] {
        output.push_str(&format!("pub const {name}: &str = {:?};\n", required(variable)?));
    }
    let revision = environment.get("SMORG_BUILD_REVISION");
    if let Some(value) = revision {
        if ![40, 64].contains(&value.len())
            || !value.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        {
            return Err(
                "SMORG_BUILD_REVISION must be a full lowercase 40/64-character Git object ID"
                    .into(),
            );
        }
    }
    let state =
        environment.get("SMORG_BUILD_SOURCE_STATE").map(String::as_str).unwrap_or("unknown");
    if !["unknown", "clean", "dirty"].contains(&state) || (state != "unknown" && revision.is_none())
    {
        return Err("source state must be unknown, or clean/dirty with an explicit revision".into());
    }
    output.push_str(&format!("pub const SOURCE_REVISION: Option<&str> = {revision:?};\n"));
    output.push_str(&format!("pub const SOURCE_STATE: &str = {state:?};\n"));
    // These are exact Cargo feature environment keys, not a dependency-feature
    // inventory or guessed reversal of Cargo's hyphen/underscore normalization.
    let features: Vec<_> = environment
        .iter()
        .filter(|(key, value)| key.starts_with("CARGO_FEATURE_") && *value == "1")
        .map(|(key, _)| key.as_str())
        .collect();
    output.push_str(&format!("pub const CARGO_FEATURE_FLAGS: &[&str] = &{features:?};\n"));
    let mut target_features: Vec<_> = environment
        .get("CARGO_CFG_TARGET_FEATURE")
        .map(String::as_str)
        .unwrap_or("")
        .split(',')
        .filter(|s| !s.is_empty())
        .collect();
    target_features.sort_unstable();
    target_features.dedup();
    output.push_str(&format!("pub const TARGET_FEATURES: &[&str] = &{target_features:?};\n"));
    Ok(output)
}
