# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f9c3df17a2dc17900bb31e906f84336c40f8518a5864ac9e98c9febd8ed95107
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "rbconfig"

extension_name = "structuredmerge_core_rb"
# Ruby may expose more than one shared-library extension via DLEXT/DLEXT2.
dlexts = [RbConfig::CONFIG["DLEXT"], RbConfig::CONFIG["DLEXT2"]].compact.uniq
ruby_abi = RbConfig::CONFIG.fetch("ruby_version")

library_candidates = dlexts.flat_map do |dlext|
  [
    File.join(__dir__, "..", extension_name, ruby_abi, "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", extension_name, ruby_abi, "lib#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "lib#{extension_name}.#{dlext}"),
  ]
end

expanded_candidates = library_candidates.map { |path| File.expand_path(path) }
native_extension = expanded_candidates.find { |path| File.file?(path) }

unless native_extension
  raise(
    LoadError,
    "cannot find #{extension_name} native extension for Ruby ABI #{ruby_abi}; " \
      "searched: #{expanded_candidates.join(", ")}"
  )
end

require native_extension
