# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:240a0d61e593c8f34a017ecfd2efff8f5718ced78c132d7e8030a43dfd4ce745
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "rbconfig"

extension_name = "structuredmerge_core_rb"
# Ruby may expose more than one shared-library extension via DLEXT/DLEXT2.
dlexts = [RbConfig::CONFIG["DLEXT"], RbConfig::CONFIG["DLEXT2"]].compact.uniq
ruby_abi = RbConfig::CONFIG.fetch("ruby_version")

library_candidates = dlexts.flat_map do |dlext|
  [
    File.join(__dir__, "..", extension_name, ruby_abi, "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", extension_name, ruby_abi, "lib#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "lib#{extension_name}.#{dlext}"),
  ]
end

expanded_candidates = library_candidates.map { |path| File.expand_path(path) }
native_extension = expanded_candidates.find { |path| File.file?(path) }

unless native_extension
  raise(
    LoadError,
    "cannot find #{extension_name} native extension for Ruby ABI #{ruby_abi}; " \
      "searched: #{expanded_candidates.join(", ")}"
  )
end

require native_extension
module StructuredmergeCore
  # The operation discriminator determines the policy type, not argument order.
  module OperationPolicy
    extend T::Helpers
    extend T::Sig

    interface!

    # Dispatch from a Hash to the appropriate variant constructor.
    # @param hash [Hash] with discriminator field and variant-specific fields
    # @return [variant_class] an instance of the appropriate variant
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T.untyped) }
    def self.from_hash(hash)
      discriminator = hash[:operation] || hash["operation"]
      case discriminator
      when "analyze" then OperationPolicyAnalyze.from_hash(hash)
      when "diff2" then OperationPolicyDiff2.from_hash(hash)
      when "merge2" then OperationPolicyMerge2.from_hash(hash)
      when "merge3" then OperationPolicyMerge3.from_hash(hash)
      else raise "Unknown discriminator: #{discriminator}"
      end
    end
  end
  ## Variant OperationPolicyAnalyze of the OperationPolicy sum type.
  OperationPolicyAnalyze = Data.define(:value) do
    include OperationPolicy
    extend T::Sig

    # @return [AnalyzePolicy]
    sig { returns(AnalyzePolicy) }
    def value = Data.instance_method(:to_h).bind_call(self).fetch(:value)
    sig { returns(T::Boolean) }
    def analyze? = true
    sig { returns(T::Boolean) }
    def diff2? = false
    sig { returns(T::Boolean) }
    def merge2? = false
    sig { returns(T::Boolean) }
    def merge3? = false
    # @param hash [Hash] deserialized from the native extension
    # @return [self]
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T.attached_class) }
    def self.from_hash(hash)
      new(value: hash[:policy] || hash["policy"])
    end
  end
  ## Variant OperationPolicyDiff2 of the OperationPolicy sum type.
  OperationPolicyDiff2 = Data.define(:value) do
    include OperationPolicy
    extend T::Sig

    # @return [DiffPolicy]
    sig { returns(DiffPolicy) }
    def value = Data.instance_method(:to_h).bind_call(self).fetch(:value)
    sig { returns(T::Boolean) }
    def analyze? = false
    sig { returns(T::Boolean) }
    def diff2? = true
    sig { returns(T::Boolean) }
    def merge2? = false
    sig { returns(T::Boolean) }
    def merge3? = false
    # @param hash [Hash] deserialized from the native extension
    # @return [self]
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T.attached_class) }
    def self.from_hash(hash)
      new(value: hash[:policy] || hash["policy"])
    end
  end
  ## Variant OperationPolicyMerge2 of the OperationPolicy sum type.
  OperationPolicyMerge2 = Data.define(:value) do
    include OperationPolicy
    extend T::Sig

    # @return [DirectionalMergePolicy]
    sig { returns(DirectionalMergePolicy) }
    def value = Data.instance_method(:to_h).bind_call(self).fetch(:value)
    sig { returns(T::Boolean) }
    def analyze? = false
    sig { returns(T::Boolean) }
    def diff2? = false
    sig { returns(T::Boolean) }
    def merge2? = true
    sig { returns(T::Boolean) }
    def merge3? = false
    # @param hash [Hash] deserialized from the native extension
    # @return [self]
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T.attached_class) }
    def self.from_hash(hash)
      new(value: hash[:policy] || hash["policy"])
    end
  end
  ## Variant OperationPolicyMerge3 of the OperationPolicy sum type.
  OperationPolicyMerge3 = Data.define(:value) do
    include OperationPolicy
    extend T::Sig

    # @return [ThreeWayMergePolicy]
    sig { returns(ThreeWayMergePolicy) }
    def value = Data.instance_method(:to_h).bind_call(self).fetch(:value)
    sig { returns(T::Boolean) }
    def analyze? = false
    sig { returns(T::Boolean) }
    def diff2? = false
    sig { returns(T::Boolean) }
    def merge2? = false
    sig { returns(T::Boolean) }
    def merge3? = true
    # @param hash [Hash] deserialized from the native extension
    # @return [self]
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T.attached_class) }
    def self.from_hash(hash)
      new(value: hash[:policy] || hash["policy"])
    end
  end
end
