# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4f3ee1475602a51e35bbdf4f05d9edcf21a448f8238bcd9c4ceef61d23784cd
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module StructuredmergeCore
  ## The version string for this package.
  VERSION = "0.2.0"
end
