# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6b808109581c151323cc22667efd63282d8d887a7d3199ee183107aa820ea51c
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module StructuredmergeCore
  ## The version string for this package.
  VERSION = "0.2.1"
end
