# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d72758a3f27ac5056a0f075c1515bfb193a0b7cc8be12dcbf1e832245af6fbf9
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

require "mkmf"
require "rb_sys/mkmf"

default_profile = ENV.fetch("CARGO_PROFILE", "release")

create_rust_makefile("structuredmerge_core_rb") do |config|
  config.profile = default_profile.to_sym
  # extconf.rb and Cargo.toml are siblings under ext/structuredmerge_core_rb/native/; rb_sys interprets
  # ext_dir relative to extconf.rb, so "." finds the sibling Cargo.toml. "native" would
  # resolve to native/native/Cargo.toml and break `gem install` on end-user machines.
  config.ext_dir = "."
end
