# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:43ab101cb230e625e9a98755049448adb92c10fc2017152ad373fba4b4bbb519
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: native_profiles."""

from native_merge_fixture import native_merge_profiles


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_native_profiles_are_explicitly_experimental() -> None:
    """Scoped Rust merge profiles expose their identity and do not claim default approval."""
    result = native_merge_profiles()
    assert len(result) == 2
    assert _alef_e2e_text(result[0].id).lower() == "kernel.python.native_declarations.v1".lower()
    assert result[1].id == "kernel.yaml.native_mapping.v1"
    assert _alef_e2e_text(result[0].semantic_runtime).lower() == "rust".lower()
    assert result[1].semantic_runtime == "rust"
    assert result[0].experimental is True
    assert result[1].experimental is True
    assert result[0].approved_as_default is False
    assert result[1].approved_as_default is False
