# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2af1f7af40c7e270a645093eb9f64486a92aee29acab5c08fbf17a74385757f9
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: rust_common_analyze."""

from native_merge_fixture import run_rust_common_analyze


def test_rust_analysis() -> None:
    """Shared typed Rust analyze: analysis."""
    source = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_analyze(source)
    assert result.ok is True
    assert "/function:f" in (result.analysis.extra.get("owners") if result.analysis else None)
    assert "node_ids" in (result.analysis.extra.get("owners") if result.analysis else None)


def test_rust_analysis_rejected() -> None:
    """Shared typed Rust analyze: analysis_rejected."""
    source = "#[test]\nfn f() {}\n"

    result = run_rust_common_analyze(source)
    assert result.ok is False
    assert result.output is None
