# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a707c82a74326b2f8e891000deeaea0a22e8d502f49abf91a1b1846f0a4fc422
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: bash_common_diff."""

from native_merge_fixture import run_bash_common_diff


def test_bash_diff_owner() -> None:
    """Shared typed Bash diff contract: bash_diff_owner."""
    before = "x=1\nf() { :; }\n"
    after = "x=2\nf() { :; }\n"

    result = run_bash_common_diff(before, after)
    assert result.ok is True
    assert result.changes[0].path == "/variable:x"
    assert len(result.changes) == 2


def test_bash_diff_trivia() -> None:
    """Shared typed Bash diff contract: bash_diff_trivia."""
    before = "# before\nx=1\n"
    after = "# after\nx=1\n"

    result = run_bash_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert result.changes[0].subject_ref == "document"
