# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:104164e60513c77fe9d91434d4ca5c0dd2f112e0c4dba7704f0184e2db61e3cd
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: capability_manifest."""

from native_merge_fixture import run_capability_manifest


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_capability_bash() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.bash.owners.v1"
    operation = "merge3"
    dialect = "bash"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.bash.owners.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "bash".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_git() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.git.json.v1"
    operation = "merge3"
    dialect = "jsonc"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.git.json.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "json5".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_git_analyze() -> None:
    """Undeclared scope remains unprobed, with unknown eligibility and no default approval."""
    profile = "kernel.git.json.v1"
    operation = "analyze"
    dialect = "json"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.git.json.v1".lower()
    assert result.observations[0].operation_declared is False
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is None
    assert result.observations[0].parser_request is None
    assert result.observations[0].parser_report is None


def test_capability_go() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.go.owners.v1"
    operation = "merge3"
    dialect = "go"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.go.owners.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "go".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_json() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.json.nested.v1"
    operation = "analyze"
    dialect = "json5"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.json.nested.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "json5".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_python() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.python.native_declarations.v1"
    operation = "merge3"
    dialect = ""

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.python.native_declarations.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "python".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_python_dialect() -> None:
    """Undeclared scope remains unprobed, with unknown eligibility and no default approval."""
    profile = "kernel.python.native_declarations.v1"
    operation = "merge3"
    dialect = "python"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.python.native_declarations.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is False
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is None
    assert result.observations[0].parser_request is None
    assert result.observations[0].parser_report is None


def test_capability_rust() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.rust.owners.v1"
    operation = "merge3"
    dialect = "rust"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.rust.owners.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "rust".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_typescript() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.typescript.owners.v1"
    operation = "merge3"
    dialect = "tsx"

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.typescript.owners.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "tsx".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_yaml() -> None:
    """Declared profile scope does not imply an eligible parser or default approval."""
    profile = "kernel.yaml.native_mapping.v1"
    operation = "merge3"
    dialect = ""

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.yaml.native_mapping.v1".lower()
    assert result.observations[0].operation_declared is True
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is False
    assert _alef_e2e_text(result.observations[0].parser_request.language).lower() == "yaml".lower()
    assert result.observations[0].parser_report.selected_backend is None


def test_capability_yaml_merge2() -> None:
    """Undeclared scope remains unprobed, with unknown eligibility and no default approval."""
    profile = "kernel.yaml.native_mapping.v1"
    operation = "merge2"
    dialect = ""

    result = run_capability_manifest(profile, operation, dialect)
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.observations) == 1
    assert _alef_e2e_text(result.observations[0].query.profile_id).lower() == "kernel.yaml.native_mapping.v1".lower()
    assert result.observations[0].operation_declared is False
    assert result.observations[0].dialect_declared is True
    assert result.observations[0].approved_as_default is False
    assert result.observations[0].parser_eligible is None
    assert result.observations[0].parser_request is None
    assert result.observations[0].parser_report is None
