# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c9467d32eed86389a6240dd88e301f7b42975029e0e0ad7602c35b0078f45b4
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: typescript_common_diff."""

from native_merge_fixture import run_typescript_common_diff


def test_tsx_diff_import() -> None:
    """Shared typed tsx diff: diff_import."""
    dialect = "tsx"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'y';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert result.changes[0].subject_ref == "document"


def test_tsx_diff_owner() -> None:
    """Shared typed tsx diff: diff_owner."""
    dialect = "tsx"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert result.changes[0].path == "/function:f"


def test_typescript_diff_import() -> None:
    """Shared typed typescript diff: diff_import."""
    dialect = "typescript"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'y';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert result.changes[0].subject_ref == "document"


def test_typescript_diff_owner() -> None:
    """Shared typed typescript diff: diff_owner."""
    dialect = "typescript"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert result.changes[0].path == "/function:f"
