# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:55cdb85687e3f9019fd7e3e3db527f6fcb54b1b6600851ab8b88401d166d567f
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: bash_common_merge2."""

from native_merge_fixture import run_bash_common_merge2


def test_bash_merge2_comments() -> None:
    """Shared typed Bash merge2 contract: bash_merge2_comments."""
    incoming = "x=1\n# é new\ny=2 # inline\nz=3\n"
    current = "x=9 # keep\n# current z\nz=8\n# footer\n"

    result = run_bash_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "x=9 # keep\n# é new\ny=2 # inline\n# current z\nz=8\n# footer\n"


def test_bash_merge2_current() -> None:
    """Shared typed Bash merge2 contract: bash_merge2_current."""
    incoming = "x=1\ny=2\n"
    current = "x=9\n"

    result = run_bash_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "x=9\ny=2\n"
    assert result.verification.directional_roles_preserved is True
    assert result.verification.output_reparsed is True


def test_bash_merge2_empty() -> None:
    """Shared typed Bash merge2 contract: bash_merge2_empty."""
    incoming = "x=1\n"
    current = ""

    result = run_bash_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "x=1\n"


def test_bash_merge2_reordered() -> None:
    """Shared typed Bash merge2 contract: bash_merge2_reordered."""
    incoming = "b=2\nnew=3\na=1\n"
    current = "a=9\nb=8\n"

    result = run_bash_common_merge2(incoming, current)
    assert result.ok is False
    assert result.output is None
