# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4737758e91b1bb3ef64ce1fa4440da9e97bf42a3bbaeeecbf08ae91a401cf1c1
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: go_common_analyze."""

from native_merge_fixture import run_go_common_analyze


def test_go_analysis() -> None:
    """Shared typed Go analyze contract: go_analysis."""
    source = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"

    result = run_go_common_analyze(source)
    assert result.ok is True
    assert "/function:f" in (result.analysis.extra.get("owners") if result.analysis else None)
    assert "node_ids" in (result.analysis.extra.get("owners") if result.analysis else None)


def test_go_analysis_rejected() -> None:
    """Shared typed Go analyze contract: go_analysis_rejected."""
    source = "package main\nvar x=1\n"

    result = run_go_common_analyze(source)
    assert result.ok is False
    assert result.analysis is None
