# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:503a442ae82bd1a1a55f2e46280fc387be58ec618ea62987724cdd338816c83c
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: python_common_diff."""

from native_merge_fixture import run_python_common_diff


def test_python_common_diff() -> None:
    """Common typed diff through the installed binding, using native parser facts and Rust-owned semantics."""
    before = "alpha = 1\nbeta = 2\n"
    after = "alpha = 10\nbeta = 2\n"

    result = run_python_common_diff(before, after)
    assert result.schema == "https://structuredmerge.org/schemas/provider-result/v1.json"
    assert result.request_id == "typed-common-diff2"
    assert result.provider.provider_id == "kernel.python"
    assert result.ok is True
    assert len(result.changes) == 1
    assert len(result.conflicts) == 0
