# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d1dd8a60df177fb79bbdccd8fb6265ce96ebaaf1a6d5322a53c86fad1d27e42
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: go_common_merge3."""

from native_merge_fixture import run_go_common_merge3


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_go_merge3_conflict() -> None:
    """Shared typed Go merge3 contract: go_merge3_conflict."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    ours = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"
    theirs = "package main\n// é\nfunc f() { println(3) }\nfunc g() { println(1) }\n"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1


def test_go_merge3_guard() -> None:
    """Shared typed Go merge3 contract: go_merge3_guard."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    ours = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"
    theirs = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\nfunc added() {}\n"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1
    assert _alef_e2e_text(result.conflicts[0].canonical.code).lower() == "go.membership_with_owner_edit".lower()
    assert result.conflicts[0].canonical.subject.whole_document is True
    assert len(result.conflicts[0].canonical.decision_ids) == 0
    assert result.verification.base_participated is True


def test_go_merge3_independent() -> None:
    """Shared typed Go merge3 contract: go_merge3_independent."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    ours = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"
    theirs = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(2) }\n"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(2) }\n"
    assert result.verification.output_reparsed is True
    assert result.verification.base_participated is True


def test_go_merge3_noop() -> None:
    """Shared typed Go merge3 contract: go_merge3_noop."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"
    ours = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"
    theirs = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"
    assert result.verification.output_reparsed is True
