# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:765ab97e87fa5f2f5eb941f39639397a6e3d5386aa9ddddf87722a4f5bb16ed0
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: go_common_diff."""

from native_merge_fixture import run_go_common_diff


def test_go_diff_header() -> None:
    """Shared typed Go diff contract: go_diff_header."""
    before = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    after = "package other\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"

    result = run_go_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert result.changes[0].subject_ref == "document"


def test_go_diff_owner() -> None:
    """Shared typed Go diff contract: go_diff_owner."""
    before = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    after = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"

    result = run_go_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert result.changes[0].path == "/function:f"
