# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c621c47dfee0026e548baf1845812c4ff1bc3c15017ba23b49ed3b963d2b229a
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: python_common_analyze."""

from native_merge_fixture import run_python_common_analyze


def test_python_common_analyze() -> None:
    """Common typed analyze through the installed binding, using native parser facts and Rust-owned semantics."""
    source = "alpha = 1\nbeta = 2\n"

    result = run_python_common_analyze(source)
    assert result.schema == "https://structuredmerge.org/schemas/provider-result/v1.json"
    assert result.request_id == "typed-common-analyze"
    assert result.provider.provider_id == "kernel.python"
    assert result.ok is True
    assert result.output is None
    assert len(result.conflicts) == 0


def test_python_common_syntax_failure() -> None:
    """Common typed analyze through the installed binding, using native parser facts and Rust-owned semantics."""
    source = "alpha = (\n"

    result = run_python_common_analyze(source)
    assert result.schema == "https://structuredmerge.org/schemas/provider-result/v1.json"
    assert result.request_id == "typed-common-analyze"
    assert result.provider.provider_id == "kernel.python"
    assert result.ok is False
    assert result.output is None
    assert len(result.diagnostics) == 1
