# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61a9c5c0ce7c31025e819256e4e7b2ee7b8f5207d93476ad819c0c2cebc5afa7
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: go_common_merge3."""

from native_merge_fixture import run_go_common_merge3


def test_go_merge3_conflict() -> None:
    """Shared typed Go merge3 contract: go_merge3_conflict."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    ours = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"
    theirs = "package main\n// é\nfunc f() { println(3) }\nfunc g() { println(1) }\n"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1


def test_go_merge3_guard() -> None:
    """Shared typed Go merge3 contract: go_merge3_guard."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    ours = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"
    theirs = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\nfunc added() {}\n"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1
    assert result.conflicts[0].canonical.code == "go.membership_with_owner_edit"
    assert result.conflicts[0].canonical.subject.whole_document is True
    assert len(result.conflicts[0].canonical.decision_ids) == 0
    assert result.verification.base_participated is True


def test_go_merge3_independent() -> None:
    """Shared typed Go merge3 contract: go_merge3_independent."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    ours = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"
    theirs = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(2) }\n"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(2) }\n"
    assert result.verification.output_reparsed is True
    assert result.verification.base_participated is True


def test_go_merge3_noop() -> None:
    """Shared typed Go merge3 contract: go_merge3_noop."""
    base = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"
    ours = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"
    theirs = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"

    result = run_go_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }"
    assert result.verification.output_reparsed is True
