# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec02dcd241050743a063617e02ed444d1899611b5176b669e2f4fb7f2a996d96
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: native_profiles."""

from native_merge_fixture import native_merge_profiles


def test_native_profiles_are_explicitly_experimental() -> None:
    """Scoped Rust merge profiles expose their identity and do not claim default approval."""
    result = native_merge_profiles()
    assert len(result) == 2
    assert result[0].id == "kernel.python.native_declarations.v1"
    assert result[1].id == "kernel.yaml.native_mapping.v1"
    assert result[0].semantic_runtime == "rust"
    assert result[1].semantic_runtime == "rust"
    assert result[0].experimental is True
    assert result[1].experimental is True
    assert result[0].approved_as_default is False
    assert result[1].approved_as_default is False
