# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a53d3d5371c070d2beb291faabfcb832c9b694c045b4e858583944b3a9ce382d
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: python_native_merge."""

from native_merge_fixture import run_python_native_merge


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_python_native_conflicting_assignment() -> None:
    """Concurrent edits to one assignment retain a conflict without rendered output."""
    base = "alpha = 1\n"
    ours = "alpha = 2\n"
    theirs = "alpha = 3\n"

    result = run_python_native_merge(base, ours, theirs)
    assert result.output is None
    assert len(result.conflicts) == 1
    assert len(result.input_parses) == 3
    assert len(result.source_segments) == 0


def test_python_native_independent_assignments() -> None:
    """LibCST supplies parse facts; Rust combines independent assignment edits."""
    base = "alpha = 1\nbeta = 2\n"
    ours = "alpha = 10\nbeta = 2\n"
    theirs = "alpha = 1\nbeta = 20\n"

    result = run_python_native_merge(base, ours, theirs)
    assert result.profile_id == "kernel.python.native_declarations.v1"
    assert result.output == "alpha = 10\nbeta = 20\n"
    assert len(result.input_parses) == 3
    assert len(result.conflicts) == 0


def test_python_native_syntax_failure() -> None:
    """A LibCST syntax failure retains all input parse evidence and exposes no output."""
    base = "alpha = 1\n"
    ours = "alpha = (\n"
    theirs = "alpha = 3\n"

    result = run_python_native_merge(base, ours, theirs)
    assert result.output is None
    assert len(result.input_parses) == 3
    assert len(result.source_segments) == 0
    assert len(result.analysis_rejections) == 0
    assert (result.rejected_parse.parsed.ok if result.rejected_parse else None) is False


def test_python_native_unsupported_import_owner() -> None:
    """Syntactically valid imports fail closed in the explicitly scoped declarations profile."""
    base = "alpha = 1\n"
    ours = "import os\n"
    theirs = "alpha = 3\n"

    result = run_python_native_merge(base, ours, theirs)
    assert result.output is None
    assert result.rejected_parse is None
    assert len(result.input_parses) == 3
    assert len(result.analysis_rejections) == 1
    assert _alef_e2e_text(result.analysis_rejections[0].code).lower() == "analysis.unsupported_profile".lower()


def test_python_native_utf8_bom_crlf_no_final_newline() -> None:
    """Independent edits preserve UTF-8 BOM, Unicode, CRLF, comments, and absent final newline."""
    base = "﻿# header\r\né = 'one'  # stable\r\nbeta = 2"
    ours = "﻿# header\r\né = 'ours'  # stable\r\nbeta = 2"
    theirs = "﻿# header\r\né = 'one'  # stable\r\nbeta = 3"

    result = run_python_native_merge(base, ours, theirs)
    assert result.output == "﻿# header\r\né = 'ours'  # stable\r\nbeta = 3"
    assert (result.output_source.bom if result.output_source else None) is True
    assert (result.output_source.final_newline if result.output_source else None) is False
    assert (result.output_source.line_endings.crlf if result.output_source else None) == 2
    assert len(result.conflicts) == 0
