# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4d64ff008a528583351bda56ddf398f711b727da1829b5526642f10f7fb60ec3
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: typescript_common_merge3."""

from native_merge_fixture import run_typescript_common_merge3


def test_tsx_jsx_merge3() -> None:
    """Shared tsx grammar jsx_merge3."""
    dialect = "tsx"
    base = "function View() { return <div>one</div>; }\nfunction f() { return 1; }\n"
    ours = "function View() { return <div>two</div>; }\nfunction f() { return 1; }\n"
    theirs = "function View() { return <div>one</div>; }\nfunction f() { return 2; }\n"

    result = run_typescript_common_merge3(dialect, base, ours, theirs)
    assert result.ok is True
    assert result.output == "function View() { return <div>two</div>; }\nfunction f() { return 2; }\n"
    assert result.verification.output_reparsed is True


def test_tsx_merge3_conflict() -> None:
    """Shared typed tsx merge3: merge3_conflict."""
    dialect = "tsx"
    base = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    ours = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"
    theirs = "import { x } from 'x';\n// é\nexport function f() { return 3; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_merge3(dialect, base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1


def test_tsx_merge3_independent() -> None:
    """Shared typed tsx merge3: merge3_independent."""
    dialect = "tsx"
    base = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    ours = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"
    theirs = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 2; }\n"

    result = run_typescript_common_merge3(dialect, base, ours, theirs)
    assert result.ok is True
    assert result.output == "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 2; }\n"
    assert result.verification.output_reparsed is True
    assert result.verification.base_participated is True


def test_tsx_merge3_noop() -> None:
    """Shared typed tsx merge3: merge3_noop."""
    dialect = "tsx"
    base = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    ours = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    theirs = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_merge3(dialect, base, ours, theirs)
    assert result.ok is True
    assert result.output == "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    assert result.verification.output_reparsed is True


def test_typescript_merge3_conflict() -> None:
    """Shared typed typescript merge3: merge3_conflict."""
    dialect = "typescript"
    base = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    ours = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"
    theirs = "import { x } from 'x';\n// é\nexport function f() { return 3; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_merge3(dialect, base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1


def test_typescript_merge3_independent() -> None:
    """Shared typed typescript merge3: merge3_independent."""
    dialect = "typescript"
    base = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    ours = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"
    theirs = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 2; }\n"

    result = run_typescript_common_merge3(dialect, base, ours, theirs)
    assert result.ok is True
    assert result.output == "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 2; }\n"
    assert result.verification.output_reparsed is True
    assert result.verification.base_participated is True


def test_typescript_merge3_noop() -> None:
    """Shared typed typescript merge3: merge3_noop."""
    dialect = "typescript"
    base = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    ours = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    theirs = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_merge3(dialect, base, ours, theirs)
    assert result.ok is True
    assert result.output == "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    assert result.verification.output_reparsed is True
