# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ee8b5d786e39839564672caefab71739412ad356d186bba852e671cb10fa8d71
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: capability_inventory."""

from native_merge_fixture import run_capability_inventory


def test_capability_inventory() -> None:
    """An empty query list exposes declarations, not successful probes or default authority."""
    result = run_capability_inventory()
    assert result.schema == "structuredmerge.typed-capability-manifest/v1"
    assert len(result.profiles.profiles) == 8
    assert len(result.observations) == 0
