# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:42c1804886a3aac602fd9fb7be61d6d5eb415308ac134b388469a5dc0ddf0299
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: rust_common_diff."""

from native_merge_fixture import run_rust_common_diff


def test_rust_diff_owner() -> None:
    """Shared typed Rust diff: diff_owner."""
    before = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    after = "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert result.changes[0].path == "/function:f"


def test_rust_diff_use() -> None:
    """Shared typed Rust diff: diff_use."""
    before = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    after = "use std::io;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert result.changes[0].subject_ref == "document"
