# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7f441c1cd74d5045e863905831be3c5104d2c908907ed70af7e9b662aeb0a8d4
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "structuredmerge-core"
  spec.version = "0.2.1"
  spec.authors       = ["Peter Boling"]
  spec.summary       = "Typed polyglot StructuredMerge kernel"
  spec.description   = "Typed polyglot StructuredMerge kernel"
  spec.homepage      = "https://github.com/structuredmerge/structuredmerge"

  spec.licenses      = ["AGPL-3.0-only", "PolyForm-Small-Business-1.0.0"]

  spec.required_ruby_version = ">= 3.2.0"
  spec.metadata["rubygems_mfa_required"] = "true"

  # Keep sibling packages and retained legacy inputs out of this gem's archive.
  candidate_files    = Dir.glob(%W[README* LICENSE* lib/structuredmerge_core.rb lib/structuredmerge_core/**/* ext/structuredmerge_core_rb/**/* sig/**/* Steepfile]).select { |f| File.file?(f) }
  spec.files         = candidate_files.grep_v(%r{/(?:target|tmp)/|\.(?:bundle|so|dylib|dll|o|a|log)\z|\.dSYM/})
  spec.require_paths = ["lib"]
  spec.extensions    = ["ext/structuredmerge_core_rb/native/extconf.rb"]

  spec.add_dependency "rb_sys", ">= 0.9.130", "< 0.10"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
