# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df05ea5b92d2037aa1b169ec062a123ebcf0c7800ecf485fac25ce6802e2a57e
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "structuredmerge-core"
  spec.version = "0.2.0"
  spec.authors       = ["Peter Boling"]
  spec.summary       = "Typed polyglot StructuredMerge kernel"
  spec.description   = "Typed polyglot StructuredMerge kernel"
  spec.homepage      = "https://github.com/structuredmerge/structuredmerge"

  spec.license       = "AGPL-3.0-only OR PolyForm-Small-Business-1.0.0"

  spec.required_ruby_version = ">= 3.2.0"
  spec.metadata["rubygems_mfa_required"] = "true"

  candidate_files    = Dir.glob(%w[README* LICENSE* lib/**/* ext/**/* sig/**/* Steepfile]).select { |f| File.file?(f) }
  spec.files         = candidate_files.grep_v(%r{/(?:target|tmp)/|\.(?:bundle|so|dylib|dll|o|a|log)\z|\.dSYM/})
  spec.require_paths = ["lib"]
  spec.extensions    = ["ext/structuredmerge_core_rb/native/extconf.rb"]

  spec.add_dependency "rb_sys", ">= 0.9.130", "< 0.10"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
