[package]
name = "ast-crispr"
version = "0.2.1"
repository = "https://github.com/structuredmerge/structuredmerge"
homepage = "https://structuredmerge.org"
authors = ["Peter H. Boling"]
edition = "2024"
description = "Structural edit tooling over Structured Merge AST contracts"
license = "AGPL-3.0-only OR PolyForm-Small-Business-1.0.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
ast-merge = { version = "0.2.1", path = "../ast-merge" }
serde_json = "1.0"

[dev-dependencies]

[lib]
path = "src/lib.rs"
