# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce0116edbfade71398e93b32bb74fcecec3ec7048cbac659457c5f5fb5c6cbdd
# To regenerate: alef generate
# To verify freshness: alef verify
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The structuredmerge_core package is expected to be installed in the current environment.
