# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8a493b224c2946fbce1c1e6ae30df31330bde02a79fab857f29022166a60719f
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: git_common_merge3."""

from native_merge_fixture import run_git_common_merge3


def test_git_clean_json() -> None:
    """Typed Git common-profile contract: git_clean_json."""
    dialect = "json"
    base = '{"x":0,"y":0}'
    ours = '{"x":1,"y":0}'
    theirs = '{"x":0,"y":2}'
    marker_size = 7
    ours_label = "ours"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is True
    assert result.output == '{"x":1,"y":2}'
    assert result.verification.output_reparsed is True


def test_git_clean_json5() -> None:
    """Typed Git common-profile contract: git_clean_json5."""
    dialect = "json5"
    base = "{x:'é',}\r\n"
    ours = "{x:'é',}\r\n"
    theirs = "{x:'雪',}\r\n"
    marker_size = 7
    ours_label = "ours"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is True
    assert result.output == "{x:'雪',}\r\n"


def test_git_clean_jsonc() -> None:
    """Typed Git common-profile contract: git_clean_jsonc."""
    dialect = "jsonc"
    base = '{/*é*/"x":0}'
    ours = '{/*é*/"x":0}'
    theirs = '{/*é*/"x":2}'
    marker_size = 7
    ours_label = "ours"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is True
    assert result.output == '{/*é*/"x":2}'
    assert result.verification.base_participated is True


def test_git_conflict_absent() -> None:
    """Deleted ours owner remains unresolved with an empty-side appended review block, not merged output."""
    dialect = "json"
    base = '{"x":0}'
    ours = "{}"
    theirs = '{"x":2}'
    marker_size = 7
    ours_label = "ours"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is False
    assert result.output is None
    assert result.conflicted_output == '{}\n<<<<<<< ours\n||||||| base\n{"x":0}\n=======\n{"x":2}\n>>>>>>> theirs\n'
    assert len(result.conflicts) == 1
    assert "git-absent-owner-conflict-review" in result.render_report.get("strategy")


def test_git_conflict_custom() -> None:
    """Typed Git common-profile contract: git_conflict_custom."""
    dialect = "json"
    base = '{\r\n"x":0\r\n}\r\n'
    ours = '{\r\n"x":1\r\n}\r\n'
    theirs = '{\r\n"x":2\r\n}\r\n'
    marker_size = 9
    ours_label = "local-é"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is False
    assert result.output is None
    assert result.conflicted_output is not None
    assert "<<<<<<<<< local-é\n" in result.conflicted_output
    assert result.conflicted_output is not None
    assert '"x":1\r\n' in result.conflicted_output
    assert result.verification.output_reparsed is None
    assert len(result.conflicts[0].canonical.alternatives) == 3
    assert "ours-not-partially-merged" in result.render_report.get("outside_conflicts")


def test_git_conflict_mixed() -> None:
    """Typed Git common-profile contract: git_conflict_mixed."""
    dialect = "json"
    base = '{\n"x":0,\n"other":0\n}\n'
    ours = '{\n"x":1,\n"other":0\n}\n'
    theirs = '{\n"x":2,\n"other":9\n}\n'
    marker_size = 7
    ours_label = "ours"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is False
    assert result.conflicted_output is not None
    assert '"other":0\n}\n' in result.conflicted_output
    assert "unresolved-conflict-review" in result.render_report.get("artifact_kind")


def test_git_conflict_overlap() -> None:
    """Typed Git common-profile contract: git_conflict_overlap."""
    dialect = "json"
    base = '{"x":0,"y":0}'
    ours = '{"x":1,"y":1}'
    theirs = '{"x":2,"y":2}'
    marker_size = 7
    ours_label = "ours"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is False
    assert result.conflicted_output is None
    assert len(result.conflicts) == 2
    assert "overlaps" in result.render_report.get("render_error")


def test_git_invalid_label() -> None:
    """Typed Git common-profile contract: git_invalid_label."""
    dialect = "json"
    base = "{}"
    ours = "{}"
    theirs = "{}"
    marker_size = 7
    ours_label = "bad\nlabel"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is False
    assert result.output is None
    assert result.verification.classification_reached is False


def test_git_invalid_width() -> None:
    """Typed Git common-profile contract: git_invalid_width."""
    dialect = "json"
    base = "{}"
    ours = "{}"
    theirs = "{}"
    marker_size = 1025
    ours_label = "ours"

    result = run_git_common_merge3(dialect, base, ours, theirs, marker_size, ours_label)
    assert result.ok is False
    assert result.output is None
