# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f973c53e1ff907bea7a13df3a03fa2e6848a4cdf4af3928e34b75824fd50bd1c
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: json_common_analyze."""

from native_merge_fixture import run_json_common_analyze


def test_json_analysis_duplicate_keys() -> None:
    """Duplicate decoded JSON keys fail closed rather than collapsing owners."""
    dialect = "json"
    source = '{"x":1,"\\u0078":2}'

    result = run_json_common_analyze(dialect, source)
    assert result.ok is False
    assert result.analysis is None
    assert result.output is None
    assert len(result.diagnostics) == 1


def test_json_analysis_jsonc_rejects_json5() -> None:
    """JSONC rejects JSON5-only keys and strings despite sharing its parser grammar."""
    dialect = "jsonc"
    source = "{x:'not-jsonc'}"

    result = run_json_common_analyze(dialect, source)
    assert result.ok is False
    assert result.analysis is None
    assert result.output is None


def test_json_analysis_nested() -> None:
    """Nested JSON5 analysis uses Rust-owned native facts."""
    dialect = "json5"
    source = "// note\r\n{a:{x:'é'},b:[1,2]}\r\n"

    result = run_json_common_analyze(dialect, source)
    assert '"path":"/a/x"' in (result.analysis.extra.get("owners") if result.analysis else None)
    assert '"path":"/b/1"' in (result.analysis.extra.get("owners") if result.analysis else None)
    assert result.ok is True
    assert (result.analysis.schema if result.analysis else None) == "structuredmerge.analysis-result/v1"
    assert result.output is None
    assert result.provider.provider_id == "kernel.json"


def test_json_analysis_unclaimed() -> None:
    """An unattached native comment remains analyzable without a fabricated sibling attachment."""
    dialect = "json5"
    source = "{} /* retained */"

    result = run_json_common_analyze(dialect, source)
    assert '"attachment_resolved":false' in (result.analysis.extra.get("comment_regions") if result.analysis else None)
    assert '"owner_id":"json:"' in (result.analysis.extra.get("comment_regions") if result.analysis else None)
    assert result.ok is True
    assert (result.analysis.schema if result.analysis else None) == "structuredmerge.analysis-result/v1"
    assert result.output is None
