# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a278915d542dc31d1875f42252bb2d0f2306bf1d42fa0677ad7563986e926ca
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: go_common_diff."""

from native_merge_fixture import run_go_common_diff


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_go_diff_header() -> None:
    """Shared typed Go diff contract: go_diff_header."""
    before = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    after = "package other\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"

    result = run_go_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert _alef_e2e_text(result.changes[0].subject_ref).lower() == "document".lower()


def test_go_diff_owner() -> None:
    """Shared typed Go diff contract: go_diff_owner."""
    before = "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n"
    after = "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n"

    result = run_go_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert _alef_e2e_text(result.changes[0].path).lower() == "/function:f".lower()
