# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eb0e759452c7f2ab3e73813795d7c265376f9ca638c294f09ff5530cd27fa3fa
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: json_common_diff."""

from native_merge_fixture import run_json_common_diff


def test_json_diff_nested() -> None:
    """Repeated identical fragments retain the changed nested owner path."""
    dialect = "json"
    before = '{"a":{"x":1},"b":{"x":1}}'
    after = '{"a":{"x":1},"b":{"x":2}}'

    result = run_json_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 4
    assert result.changes[3].path == "/b/x"
    assert result.changes[3].classification == "edited"
    assert result.output is None


def test_json_diff_noop() -> None:
    """Identical Unicode JSON documents report no changes."""
    dialect = "json"
    before = '{"é":1}'
    after = '{"é":1}'

    result = run_json_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 0
    assert result.output is None


def test_json_diff_trivia() -> None:
    """Document comparison covers comment and newline edits outside syntax owners."""
    dialect = "json5"
    before = "// before\n{}"
    after = "// after\n{}\r\n"

    result = run_json_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert result.changes[0].subject_ref == "json.document"
    assert result.output is None
