# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6d2c982243ecdf6b4e78780759f28bc703797ffead94885e6e387fa66da66fd2
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: rust_common_merge2."""

from native_merge_fixture import run_rust_common_merge2


def test_rust_merge2_current() -> None:
    """Shared typed Rust merge2: merge2_current."""
    incoming = "fn f() { incoming(); }\nfn g() {}\n"
    current = "fn f() { current(); }\n"

    result = run_rust_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "fn f() { current(); }\nfn g() {}\n"
    assert result.verification.output_reparsed is True
    assert result.verification.directional_roles_preserved is True


def test_rust_merge2_docs() -> None:
    """Shared typed Rust merge2: merge2_docs."""
    incoming = "//! incoming module\n/// é added\nfn added() {}\nfn f() {}\n"
    current = "//! current module\n/// current f\nfn f() {} // inline\n// footer\n"

    result = run_rust_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "//! current module\n/// é added\nfn added() {}\n/// current f\nfn f() {} // inline\n// footer\n"
    assert result.verification.output_reparsed is True


def test_rust_merge2_empty() -> None:
    """Shared typed Rust merge2: merge2_empty."""
    incoming = "struct T;\n"
    current = ""

    result = run_rust_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "struct T;\n"
    assert result.verification.output_reparsed is True


def test_rust_merge2_interleaved() -> None:
    """Shared typed Rust merge2: merge2_interleaved."""
    incoming = "fn f() {}\nuse std::fmt;\n// added\nfn g() {}\n"
    current = "use std::fmt;\nfn f() { current(); }\n"

    result = run_rust_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "use std::fmt;\nfn f() { current(); }\n// added\nfn g() {}\n"
    assert result.verification.output_reparsed is True


def test_rust_merge2_use_only() -> None:
    """Shared typed Rust merge2: merge2_use_only."""
    incoming = "use std::fmt;\n/// first\nfn f() {}\n"
    current = "use std::fmt;\n// footer\n"

    result = run_rust_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "use std::fmt;\n/// first\nfn f() {}\n// footer\n"
    assert result.verification.output_reparsed is True


def test_rust_merge2_use_rejected() -> None:
    """Shared typed Rust merge2: merge2_use_rejected."""
    incoming = "use std::io;\nfn g() {}\n"
    current = "use std::fmt;\nfn f() {}\n"

    result = run_rust_common_merge2(incoming, current)
    assert result.ok is False
    assert result.output is None
