# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a0d28f6da12ead3e9f500c0bba03666c0767d07999a07cd007ab22b5de769b2
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: rust_common_merge3."""

from native_merge_fixture import run_rust_common_merge3


def test_rust_merge3_conflict() -> None:
    """Shared typed Rust merge3: merge3_conflict."""
    base = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    ours = "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n"
    theirs = "use std::fmt;\n// é\nfn f() -> i32 { 3 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1


def test_rust_merge3_guard() -> None:
    """Shared typed Rust merge3: merge3_guard."""
    base = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    ours = "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n"
    theirs = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\nfn added() {}\n"

    result = run_rust_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1
    assert result.conflicts[0].canonical.code == "rust.membership_with_owner_edit"
    assert result.conflicts[0].canonical.subject.whole_document is True
    assert len(result.conflicts[0].canonical.decision_ids) == 0
    assert result.verification.base_participated is True


def test_rust_merge3_guard_shortcut() -> None:
    """Shared typed Rust merge3: merge3_guard_shortcut."""
    base = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    ours = "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\nfn added() {}\n"
    theirs = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert result.conflicts[0].canonical.code == "rust.membership_with_owner_edit"
    assert len(result.conflicts[0].canonical.decision_ids) == 0


def test_rust_merge3_independent() -> None:
    """Shared typed Rust merge3: merge3_independent."""
    base = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    ours = "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n"
    theirs = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 2 }\n"

    result = run_rust_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 2 }\n"
    assert result.verification.output_reparsed is True
    assert result.verification.base_participated is True


def test_rust_merge3_noop() -> None:
    """Shared typed Rust merge3: merge3_noop."""
    base = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    ours = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    theirs = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    assert result.verification.output_reparsed is True
