# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f005ee1ecaa421ca91a7872dfbe9005d02e7306d621732f0a28a3a438ec57c3f
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: go_common_merge2."""

from native_merge_fixture import run_go_common_merge2


def test_go_merge2_comments() -> None:
    """Shared typed Go merge2 contract: go_merge2_comments."""
    incoming = "package main\n\n// é new\nfunc added() {}\nfunc f() {}\n"
    current = "// module\npackage main\n\n// f\nfunc f() {}\n// footer\n"

    result = run_go_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "// module\npackage main\n\n// é new\nfunc added() {}\n\n// f\nfunc f() {}\n// footer\n"


def test_go_merge2_current() -> None:
    """Shared typed Go merge2 contract: go_merge2_current."""
    incoming = "package main\nfunc f() { println(1) }\nfunc g() {}\n"
    current = "package main\nfunc f() { println(9) }\n"

    result = run_go_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "package main\nfunc f() { println(9) }\nfunc g() {}\n"
    assert result.verification.directional_roles_preserved is True
    assert result.verification.output_reparsed is True


def test_go_merge2_import_rejected() -> None:
    """Shared typed Go merge2 contract: go_merge2_import_rejected."""
    incoming = 'package main\nimport "fmt"\nfunc g() { fmt.Println(1) }\n'
    current = "package main\nfunc f() {}\n"

    result = run_go_common_merge2(incoming, current)
    assert result.ok is False
    assert result.output is None


def test_go_merge2_package_only() -> None:
    """Shared typed Go merge2 contract: go_merge2_package_only."""
    incoming = "package main\n// f\nfunc f() {}\n"
    current = "package main\n// footer\n"

    result = run_go_common_merge2(incoming, current)
    assert result.ok is True
    assert result.output == "package main\n// f\nfunc f() {}\n// footer\n"
    assert result.verification.output_reparsed is True
