# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ddc8c6ad356dfdb96a783767150331c46874eadad6cef2ed8e8d1128a08c8b73
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: typescript_common_analyze."""

from native_merge_fixture import run_typescript_common_analyze


def test_tsx_analysis() -> None:
    """Shared typed tsx analyze: analysis."""
    dialect = "tsx"
    source = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_analyze(dialect, source)
    assert result.ok is True
    assert "/function:f" in (result.analysis.extra.get("owners") if result.analysis else None)
    assert "node_ids" in (result.analysis.extra.get("owners") if result.analysis else None)


def test_tsx_analysis_rejected() -> None:
    """Shared typed tsx analyze: analysis_rejected."""
    dialect = "tsx"
    source = "export const v = 1;\n"

    result = run_typescript_common_analyze(dialect, source)
    assert result.ok is False


def test_tsx_jsx_analysis() -> None:
    """Shared tsx grammar jsx_analysis."""
    dialect = "tsx"
    source = "function View() { return <div/>; }\n"

    result = run_typescript_common_analyze(dialect, source)
    assert result.ok is True
    assert "/function:View" in (result.analysis.extra.get("owners") if result.analysis else None)


def test_typescript_analysis() -> None:
    """Shared typed typescript analyze: analysis."""
    dialect = "typescript"
    source = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_analyze(dialect, source)
    assert result.ok is True
    assert "/function:f" in (result.analysis.extra.get("owners") if result.analysis else None)
    assert "node_ids" in (result.analysis.extra.get("owners") if result.analysis else None)


def test_typescript_analysis_rejected() -> None:
    """Shared typed typescript analyze: analysis_rejected."""
    dialect = "typescript"
    source = "export const v = 1;\n"

    result = run_typescript_common_analyze(dialect, source)
    assert result.ok is False


def test_typescript_jsx_rejected() -> None:
    """Shared typescript grammar jsx_rejected."""
    dialect = "typescript"
    source = "function View() { return <div/>; }\n"

    result = run_typescript_common_analyze(dialect, source)
    assert result.ok is False
