# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:64aeaff7d851b07333ee49e75a963cd54d516a8c081d4a6bb4fc5ebecc86aa20
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: bash_common_diff."""

from native_merge_fixture import run_bash_common_diff


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_bash_diff_owner() -> None:
    """Shared typed Bash diff contract: bash_diff_owner."""
    before = "x=1\nf() { :; }\n"
    after = "x=2\nf() { :; }\n"

    result = run_bash_common_diff(before, after)
    assert result.ok is True
    assert _alef_e2e_text(result.changes[0].path).lower() == "/variable:x".lower()
    assert len(result.changes) == 2


def test_bash_diff_trivia() -> None:
    """Shared typed Bash diff contract: bash_diff_trivia."""
    before = "# before\nx=1\n"
    after = "# after\nx=1\n"

    result = run_bash_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert _alef_e2e_text(result.changes[0].subject_ref).lower() == "document".lower()
