# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7f87fd4b47abdd9b2b8680e3d191e57163b65ad6d7224b4320f28bccf5e468d3
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: json_common_diff."""

from native_merge_fixture import run_json_common_diff


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_json_diff_nested() -> None:
    """Repeated identical fragments retain the changed nested owner path."""
    dialect = "json"
    before = '{"a":{"x":1},"b":{"x":1}}'
    after = '{"a":{"x":1},"b":{"x":2}}'

    result = run_json_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 4
    assert result.changes[3].path == "/b/x"
    assert result.changes[3].classification == "edited"
    assert result.output is None


def test_json_diff_noop() -> None:
    """Identical Unicode JSON documents report no changes."""
    dialect = "json"
    before = '{"é":1}'
    after = '{"é":1}'

    result = run_json_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 0
    assert result.output is None


def test_json_diff_trivia() -> None:
    """Document comparison covers comment and newline edits outside syntax owners."""
    dialect = "json5"
    before = "// before\n{}"
    after = "// after\n{}\r\n"

    result = run_json_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert _alef_e2e_text(result.changes[0].subject_ref).lower() == "json.document".lower()
    assert result.output is None
