# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec7a56f598513d259d25e55c4c2f8d47b8aed9eb16dc1efeec7bac13791285d6
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: python_common_merge."""

from native_merge_fixture import run_python_common_merge


def test_python_common_byte_preservation() -> None:
    """Common typed merge through the installed binding, using native parser facts and Rust-owned semantics."""
    base = "﻿# header\r\né = 'one'  # stable\r\nbeta = 2"
    ours = "﻿# header\r\né = 'ours'  # stable\r\nbeta = 2"
    theirs = "﻿# header\r\né = 'one'  # stable\r\nbeta = 3"

    result = run_python_common_merge(base, ours, theirs)
    assert result.schema == "https://structuredmerge.org/schemas/provider-result/v1.json"
    assert result.request_id == "typed-common-merge3"
    assert result.provider.provider_id == "kernel.python"
    assert result.ok is True
    assert result.output == "﻿# header\r\né = 'ours'  # stable\r\nbeta = 3"
    assert len(result.conflicts) == 0
    assert result.verification.output_reparsed is True


def test_python_common_conflicting_merge() -> None:
    """Common typed merge through the installed binding, using native parser facts and Rust-owned semantics."""
    base = "alpha = 1\n"
    ours = "alpha = 2\n"
    theirs = "alpha = 3\n"

    result = run_python_common_merge(base, ours, theirs)
    assert result.schema == "https://structuredmerge.org/schemas/provider-result/v1.json"
    assert result.request_id == "typed-common-merge3"
    assert result.provider.provider_id == "kernel.python"
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1


def test_python_common_independent_merge() -> None:
    """Common typed merge through the installed binding, using native parser facts and Rust-owned semantics."""
    base = "alpha = 1\nbeta = 2\n"
    ours = "alpha = 10\nbeta = 2\n"
    theirs = "alpha = 1\nbeta = 20\n"

    result = run_python_common_merge(base, ours, theirs)
    assert result.schema == "https://structuredmerge.org/schemas/provider-result/v1.json"
    assert result.request_id == "typed-common-merge3"
    assert result.provider.provider_id == "kernel.python"
    assert result.ok is True
    assert result.output == "alpha = 10\nbeta = 20\n"
    assert len(result.conflicts) == 0
    assert result.verification.output_reparsed is True
