# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7b61b0cce7439aeb53434b80487a4386dd06b8077bbb840aa45a47ca648ac3e4
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: python_common_merge2."""

from native_merge_fixture import run_python_common_merge2


def test_python_common_merge2_current_preferred() -> None:
    """Rust-owned directional merge through the installed common API with native LibCST facts."""
    incoming = "a = 9\n"
    current = "a = 1\nb = 2\n"

    result = run_python_common_merge2(incoming, current)
    assert result.ok is True
    assert result.request_id == "typed-common-merge2"
    assert result.output == "a = 1\nb = 2\n"
    assert result.verification.base_participated is None
    assert len(result.changes) == 0
    assert len(result.conflicts) == 0
    assert result.verification.directional_roles_preserved is True
    assert result.verification.output_reparsed is True
    assert len(result.verification.consumed_source_roles) == 2


def test_python_common_merge2_insert() -> None:
    """Rust-owned directional merge through the installed common API with native LibCST facts."""
    incoming = "a = 1\nb = 2 # new\n"
    current = "﻿a = 9 # keep\r\n# footer"

    result = run_python_common_merge2(incoming, current)
    assert result.ok is True
    assert result.request_id == "typed-common-merge2"
    assert result.output == "﻿a = 9 # keep\r\nb = 2 # new\n# footer"
    assert result.verification.base_participated is None
    assert len(result.changes) == 1
    assert len(result.conflicts) == 0
    assert result.verification.directional_roles_preserved is True
    assert result.verification.output_reparsed is True
    assert len(result.verification.consumed_source_roles) == 2


def test_python_common_merge2_reordered_anchors() -> None:
    """Rust-owned directional merge through the installed common API with native LibCST facts."""
    incoming = "a = 1\nb = 2\nc = 3\n"
    current = "c = 30\na = 10\n"

    result = run_python_common_merge2(incoming, current)
    assert result.ok is False
    assert result.request_id == "typed-common-merge2"
    assert result.output is None
    assert result.verification.base_participated is None
    assert len(result.changes) == 0
    assert len(result.conflicts) == 0
    assert len(result.diagnostics) == 1
