# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c23302c727125a7b26adc0f2ca03b1336d56c3aac48868309718159ce710de22
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: json_common_merge3."""

from native_merge_fixture import run_json_common_merge3


def test_json_merge3_conflict() -> None:
    """Overlapping JSON edits retain a canonical conflict with all revision alternatives."""
    dialect = "json"
    base = '{"a":1}'
    ours = '{"a":2}'
    theirs = '{"a":3}'

    result = run_json_common_merge3(dialect, base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1
    assert len(result.conflicts[0].canonical.alternatives) == 3


def test_json_merge3_independent() -> None:
    """Independent JSON changes merge in Rust and require output verification."""
    dialect = "json"
    base = '{"a":1,"b":2}'
    ours = '{"a":3,"b":2}'
    theirs = '{"a":1,"b":4}'

    result = run_json_common_merge3(dialect, base, ours, theirs)
    assert result.ok is True
    assert result.output == '{"a":3,"b":4}'
    assert result.verification.base_participated is True
    assert result.verification.output_reparsed is True


def test_json_merge3_selected_bytes() -> None:
    """Selected JSON5 input retains Unicode, comment, CRLF and no-final-newline bytes."""
    dialect = "json5"
    base = "{x:1}"
    ours = "{x:1}"
    theirs = "// chosen\r\n{x:'é'}"

    result = run_json_common_merge3(dialect, base, ours, theirs)
    assert result.ok is True
    assert result.output == "// chosen\r\n{x:'é'}"
    assert result.verification.output_reparsed is True
