# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f19e464c0d934e5b0e222c19bf5defbfc4f1fd957810804c4eb219c9eb74f7d
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: rust_common_diff."""

from native_merge_fixture import run_rust_common_diff


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_rust_diff_owner() -> None:
    """Shared typed Rust diff: diff_owner."""
    before = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    after = "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert _alef_e2e_text(result.changes[0].path).lower() == "/function:f".lower()


def test_rust_diff_use() -> None:
    """Shared typed Rust diff: diff_use."""
    before = "use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"
    after = "use std::io;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n"

    result = run_rust_common_diff(before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert _alef_e2e_text(result.changes[0].subject_ref).lower() == "document".lower()
