# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:90aa85dcdddc7d00124478fa6d7b53a22920131ce76e657be3592842988a48ef
# To regenerate: alef generate
# To verify freshness: alef verify
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package() -> None:
    module = importlib.import_module("structuredmerge-core")
    assert module is not None
