# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1227a68f3d237c3b860a7dc53467d875e77a6b0f5427ff9c1696f8b44e42b3f8
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: typescript_common_merge2."""

from native_merge_fixture import run_typescript_common_merge2


def test_tsx_jsx_merge2() -> None:
    """Shared tsx grammar jsx_merge2."""
    dialect = "tsx"
    incoming = "function View() { return <div/>; }\n"
    current = ""

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "function View() { return <div/>; }\n"
    assert result.verification.output_reparsed is True


def test_tsx_merge2_comments() -> None:
    """Shared typed tsx merge2: merge2_comments."""
    dialect = "tsx"
    incoming = "import { x } from 'x';\n/** é added */\nexport class C {}\n"
    current = "// module\nimport { x } from 'x';\n// footer\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "// module\nimport { x } from 'x';\n/** é added */\nexport class C {}\n// footer\n"
    assert result.verification.output_reparsed is True


def test_tsx_merge2_current() -> None:
    """Shared typed tsx merge2: merge2_current."""
    dialect = "tsx"
    incoming = "function f() { incoming(); }\nfunction g() {}\n"
    current = "function f() { current(); }\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "function f() { current(); }\nfunction g() {}\n"
    assert result.verification.output_reparsed is True
    assert result.verification.directional_roles_preserved is True


def test_tsx_merge2_header() -> None:
    """Shared typed tsx merge2: merge2_header."""
    dialect = "tsx"
    incoming = "// incoming header\nexport function added() {}\nfunction f() {}\n"
    current = "// @ts-nocheck\nfunction f() {}\n// footer\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "// @ts-nocheck\nexport function added() {}\nfunction f() {}\n// footer\n"
    assert result.verification.output_reparsed is True


def test_tsx_merge2_interleaved() -> None:
    """Shared typed tsx merge2: merge2_interleaved."""
    dialect = "tsx"
    incoming = "function f() {}\nimport { x } from 'x';\n// added\nconst added = 1;\n"
    current = "import { x } from 'x';\nfunction f() {}\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "import { x } from 'x';\nfunction f() {}\n// added\nconst added = 1;\n"
    assert result.verification.output_reparsed is True


def test_tsx_merge2_rejected() -> None:
    """Shared typed tsx merge2: merge2_rejected."""
    dialect = "tsx"
    incoming = "import { x } from 'x';\nfunction added() {}\n"
    current = "import { x } from 'y';\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is False
    assert result.output is None


def test_typescript_merge2_comments() -> None:
    """Shared typed typescript merge2: merge2_comments."""
    dialect = "typescript"
    incoming = "import { x } from 'x';\n/** é added */\nexport class C {}\n"
    current = "// module\nimport { x } from 'x';\n// footer\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "// module\nimport { x } from 'x';\n/** é added */\nexport class C {}\n// footer\n"
    assert result.verification.output_reparsed is True


def test_typescript_merge2_current() -> None:
    """Shared typed typescript merge2: merge2_current."""
    dialect = "typescript"
    incoming = "function f() { incoming(); }\nfunction g() {}\n"
    current = "function f() { current(); }\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "function f() { current(); }\nfunction g() {}\n"
    assert result.verification.output_reparsed is True
    assert result.verification.directional_roles_preserved is True


def test_typescript_merge2_header() -> None:
    """Shared typed typescript merge2: merge2_header."""
    dialect = "typescript"
    incoming = "// incoming header\nexport function added() {}\nfunction f() {}\n"
    current = "// @ts-nocheck\nfunction f() {}\n// footer\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "// @ts-nocheck\nexport function added() {}\nfunction f() {}\n// footer\n"
    assert result.verification.output_reparsed is True


def test_typescript_merge2_interleaved() -> None:
    """Shared typed typescript merge2: merge2_interleaved."""
    dialect = "typescript"
    incoming = "function f() {}\nimport { x } from 'x';\n// added\nconst added = 1;\n"
    current = "import { x } from 'x';\nfunction f() {}\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == "import { x } from 'x';\nfunction f() {}\n// added\nconst added = 1;\n"
    assert result.verification.output_reparsed is True


def test_typescript_merge2_rejected() -> None:
    """Shared typed typescript merge2: merge2_rejected."""
    dialect = "typescript"
    incoming = "import { x } from 'x';\nfunction added() {}\n"
    current = "import { x } from 'y';\n"

    result = run_typescript_common_merge2(dialect, incoming, current)
    assert result.ok is False
    assert result.output is None
