# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f5c630c16274fedfc47e519908c7be426c2e33119e8ca9decfd59321cc6eca8
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: json_common_merge2."""

from native_merge_fixture import run_json_common_merge2


def test_json_merge2_current_preferred() -> None:
    """Directional JSON merge keeps current values, arrays and exact CRLF bytes without a base."""
    dialect = "json"
    incoming = '{"x":2,"a":[3]}'
    current = '{\r\n "x":1,"a":[1,2]\r\n}'

    result = run_json_common_merge2(dialect, incoming, current)
    assert result.ok is True
    assert result.output == '{\r\n "x":1,"a":[1,2]\r\n}'
    assert result.verification.directional_roles_preserved is True
    assert result.verification.base_participated is None
    assert result.verification.output_reparsed is True
