# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:50f5c8a70ff8f1d905380095575f89b061d395c50965c3fb3964900de011657a
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: typescript_common_diff."""

from native_merge_fixture import run_typescript_common_diff


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def test_tsx_diff_import() -> None:
    """Shared typed tsx diff: diff_import."""
    dialect = "tsx"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'y';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert _alef_e2e_text(result.changes[0].subject_ref).lower() == "document".lower()


def test_tsx_diff_owner() -> None:
    """Shared typed tsx diff: diff_owner."""
    dialect = "tsx"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert _alef_e2e_text(result.changes[0].path).lower() == "/function:f".lower()


def test_typescript_diff_import() -> None:
    """Shared typed typescript diff: diff_import."""
    dialect = "typescript"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'y';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 1
    assert _alef_e2e_text(result.changes[0].subject_ref).lower() == "document".lower()


def test_typescript_diff_owner() -> None:
    """Shared typed typescript diff: diff_owner."""
    dialect = "typescript"
    before = "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n"
    after = "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n"

    result = run_typescript_common_diff(dialect, before, after)
    assert result.ok is True
    assert len(result.changes) == 2
    assert _alef_e2e_text(result.changes[0].path).lower() == "/function:f".lower()
