# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3dafd608ef668dd8e476172af6a02ea719f0b2806d2f079140983fae318f517f
# To regenerate: alef generate
# To verify freshness: alef verify
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package() -> None:
    module = importlib.import_module("structuredmerge_core")
    assert module is not None
