# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d83e65bcdd683e4153b9a1eeb2d934b2d58013e078ff41552b0eeb118f5c359c
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: bash_common_merge3."""

from native_merge_fixture import run_bash_common_merge3


def test_bash_merge3_conflict() -> None:
    """Shared typed Bash merge3 contract: bash_merge3_conflict."""
    base = "x=1\n"
    ours = "x=2\n"
    theirs = "x=3\n"

    result = run_bash_common_merge3(base, ours, theirs)
    assert result.ok is False
    assert result.output is None
    assert len(result.conflicts) == 1


def test_bash_merge3_independent() -> None:
    """Shared typed Bash merge3 contract: bash_merge3_independent."""
    base = "x=1\ny=1\n"
    ours = "x=2\ny=1\n"
    theirs = "x=1\ny=2\n"

    result = run_bash_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "x=2\ny=2\n"
    assert result.verification.base_participated is True


def test_bash_merge3_noop() -> None:
    """Shared typed Bash merge3 contract: bash_merge3_noop."""
    base = "# é\nx=1"
    ours = "# é\nx=1"
    theirs = "# é\nx=1"

    result = run_bash_common_merge3(base, ours, theirs)
    assert result.ok is True
    assert result.output == "# é\nx=1"
    assert result.verification.output_reparsed is True
