# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:400b9b7f4b4fcba47a634af389879ce434b4be21f835618f6dfc4c694ac41e1b
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: bash_common_analyze."""

from native_merge_fixture import run_bash_common_analyze


def test_bash_analysis() -> None:
    """Shared typed Bash analyze contract: bash_analysis."""
    source = "# é\nx=1\n\nf() { :; }\n"

    result = run_bash_common_analyze(source)
    assert result.ok is True
    assert "/function:f" in (result.analysis.extra.get("owners") if result.analysis else None)
    assert "node_ids" in (result.analysis.extra.get("owners") if result.analysis else None)


def test_bash_analysis_rejected() -> None:
    """Shared typed Bash analyze contract: bash_analysis_rejected."""
    source = "echo unsupported\n"

    result = run_bash_common_analyze(source)
    assert result.ok is False
    assert result.analysis is None
