# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ca849e2ca44d77f5e1cac68a9221433f545c29b990383407c3e916d98d98d12
# To regenerate: alef generate
# To verify freshness: alef verify

import builtins

from typing import Any, Literal, TypedDict

class AnalyzePolicy:
    analysis_depth: str | None
    comments: bool | None
    tokens: bool | None
    ownership: bool | None
    native_extensions: bool | None
    extra: dict[str, str]
    def __init__(
        self,
        extra: dict[str, str],
        analysis_depth: str | None = None,
        comments: bool | None = None,
        tokens: bool | None = None,
        ownership: bool | None = None,
        native_extensions: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> AnalyzePolicy: ...

class ByteRange:
    start_byte: int
    end_byte: int
    def __init__(self, start_byte: int, end_byte: int) -> None: ...
    def is_valid(self) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def contains_byte(self, offset: int) -> bool: ...
    @staticmethod
    def from_json(json_str: str) -> ByteRange: ...

class ChildEdge:
    node_id: str
    index: int
    field_name: str | None
    extra: dict[str, str]
    def __init__(
        self,
        node_id: str,
        index: int,
        extra: dict[str, str],
        field_name: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ChildEdge: ...

class ConflictAlternative:
    revision: SourceRevision
    state: ConflictAlternativeState
    regions: list[OwnedSourceRegion]
    def __init__(
        self,
        revision: SourceRevision | str,
        state: ConflictAlternativeState | str,
        regions: list[OwnedSourceRegion],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ConflictAlternative: ...

class ConflictClassification:
    base_participated: bool | None
    change_ids: list[str]
    decision_ids: list[str]
    extra: dict[str, str]
    def __init__(
        self,
        change_ids: list[str],
        decision_ids: list[str],
        extra: dict[str, str],
        base_participated: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ConflictClassification: ...

class ConflictLocalization:
    status: LocalizationStatus
    verified: bool
    output_regions: list[ExactConflictRegion]
    extra: dict[str, str]
    def __init__(
        self,
        status: LocalizationStatus | str,
        verified: bool,
        output_regions: list[ExactConflictRegion],
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ConflictLocalization: ...

class ConflictResolution:
    status: ResolutionStatus
    strategy: ResolutionStrategy
    selected_roles: list[SourceRole]
    decision_id: str | None
    resolver: str | None
    reason: str | None
    extra: dict[str, str]
    def __init__(
        self,
        status: ResolutionStatus | str,
        strategy: ResolutionStrategy | str,
        selected_roles: list[SourceRole],
        extra: dict[str, str],
        decision_id: str | None = None,
        resolver: str | None = None,
        reason: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ConflictResolution: ...

class ConflictSourceAlternative:
    role: SourceRole
    state: AlternativeState
    source_id: str | None
    regions: list[ExactConflictRegion]
    change_ids: list[str]
    extra: dict[str, str]
    def __init__(
        self,
        role: SourceRole | str,
        state: AlternativeState | str,
        regions: list[ExactConflictRegion],
        change_ids: list[str],
        extra: dict[str, str],
        source_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ConflictSourceAlternative: ...

class ConflictSubject:
    structural_path: str | None
    owner_ref: str | None
    node_ref: str | None
    archive_entry: str | None
    binary_region: ResultRange | None
    whole_document: bool | None
    extra: dict[str, str]
    def __init__(
        self,
        extra: dict[str, str],
        structural_path: str | None = None,
        owner_ref: str | None = None,
        node_ref: str | None = None,
        archive_entry: str | None = None,
        binary_region: ResultRange | None = None,
        whole_document: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ConflictSubject: ...

class CoreError:
    code: str
    message: str
    def __init__(self, code: str, message: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CoreError: ...

class CoreParseResult:
    schema: str
    selection: SelectionReport
    backend: ParserProviderDescriptor
    parsed: ParseOutput
    def __init__(
        self,
        schema: str,
        selection: SelectionReport,
        backend: ParserProviderDescriptor,
        parsed: ParseOutput,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CoreParseResult: ...

class CrisprBatchOperationReport:
    operation_count: int
    operation_kinds: list[str]
    operation_profiles: list[CrisprOperationReport]
    def __init__(
        self,
        operation_count: int,
        operation_kinds: list[str],
        operation_profiles: list[CrisprOperationReport],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBatchOperationReport: ...

class CrisprBoundaryImplementation:
    language: str
    package_name: str
    import_path: str | None
    require_path: str | None
    crate_name: str | None
    def __init__(
        self,
        language: str,
        package_name: str,
        import_: str | None = None,
        require: str | None = None,
        crate_: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryImplementation: ...

class CrisprBoundaryMetadata:
    source: str
    decision: str
    def __init__(self, source: str, decision: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryMetadata: ...

class CrisprBoundaryRelationships:
    ast_merge: list[str]
    ast_crispr: list[str]
    provider_packages: list[str]
    ast_template: list[str]
    def __init__(
        self,
        ast_merge: list[str],
        ast_crispr: list[str],
        provider_packages: list[str],
        ast_template: list[str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryRelationships: ...

class CrisprBoundaryReport:
    package: str
    layer: str
    status: str
    base_contract_package: str
    relationship: CrisprBoundaryRelationships
    implementations: list[CrisprBoundaryImplementation]
    initial_exports: list[str]
    future_exports: list[str]
    metadata: CrisprBoundaryMetadata
    def __init__(
        self,
        package: str,
        layer: str,
        status: str,
        base_contract_package: str,
        relationship: CrisprBoundaryRelationships,
        implementations: list[CrisprBoundaryImplementation],
        initial_exports: list[str],
        future_exports: list[str],
        metadata: CrisprBoundaryMetadata,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprBoundaryReport: ...

class CrisprDestinationReport:
    resolution_kind: str
    resolution_family: str
    known_resolution_kind: bool
    resolution_source: str
    resolution_source_family: str
    known_resolution_source: bool
    anchor_boundary: str
    anchor_boundary_family: str
    known_anchor_boundary: bool
    used_if_missing: bool
    append_fallback: bool
    anchored: bool
    def __init__(
        self,
        resolution_kind: str,
        resolution_family: str,
        known_resolution_kind: bool,
        resolution_source: str,
        resolution_source_family: str,
        known_resolution_source: bool,
        anchor_boundary: str,
        anchor_boundary_family: str,
        known_anchor_boundary: bool,
        used_if_missing: bool,
        append_fallback: bool,
        anchored: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprDestinationReport: ...

class CrisprDestinationRequest:
    resolution_kind: str
    resolution_source: str
    anchor_boundary: str
    used_if_missing: bool
    def __init__(
        self,
        resolution_kind: str,
        resolution_source: str,
        anchor_boundary: str,
        used_if_missing: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprDestinationRequest: ...

class CrisprLimitConstraint:
    operator: CrisprLimitOperator
    value: int
    def __init__(self, operator: CrisprLimitOperator | str, value: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprLimitConstraint: ...

class CrisprLimitReport:
    description: str
    counts: list[int]
    allowed: list[bool]
    def __init__(self, description: str, counts: list[int], allowed: list[bool]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprLimitReport: ...

class CrisprLimitRequest:
    constraints: list[CrisprLimitConstraint] | None
    counts: list[int]
    def __init__(
        self,
        counts: list[int],
        constraints: list[CrisprLimitConstraint] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprLimitRequest: ...

class CrisprMatchReport:
    start_boundary: str
    start_boundary_family: str
    known_start_boundary: bool
    end_boundary: str
    end_boundary_family: str
    known_end_boundary: bool
    payload_kind: str
    payload_family: str
    known_payload_kind: bool
    comment_anchored: bool
    trailing_gap_extended: bool
    def __init__(
        self,
        start_boundary: str,
        start_boundary_family: str,
        known_start_boundary: bool,
        end_boundary: str,
        end_boundary_family: str,
        known_end_boundary: bool,
        payload_kind: str,
        payload_family: str,
        known_payload_kind: bool,
        comment_anchored: bool,
        trailing_gap_extended: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprMatchReport: ...

class CrisprMatchRequest:
    start_boundary: str
    end_boundary: str
    payload_kind: str
    def __init__(self, start_boundary: str, end_boundary: str, payload_kind: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprMatchRequest: ...

class CrisprOperationReport:
    operation_kind: str
    operation_family: str
    known_operation_kind: bool
    source_requirement: str
    known_source_requirement: bool
    destination_requirement: str
    known_destination_requirement: bool
    replacement_source: str
    known_replacement_source: bool
    captures_source_text: bool
    supports_if_missing: bool
    selects_source: bool
    requires_source: bool
    supports_destination: bool
    requires_destination: bool
    explicit_replacement: bool
    may_reuse_captured_text: bool
    def __init__(
        self,
        operation_kind: str,
        operation_family: str,
        known_operation_kind: bool,
        source_requirement: str,
        known_source_requirement: bool,
        destination_requirement: str,
        known_destination_requirement: bool,
        replacement_source: str,
        known_replacement_source: bool,
        captures_source_text: bool,
        supports_if_missing: bool,
        selects_source: bool,
        requires_source: bool,
        supports_destination: bool,
        requires_destination: bool,
        explicit_replacement: bool,
        may_reuse_captured_text: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprOperationReport: ...

class CrisprOperationRequest:
    operation_kind: str
    source_requirement: str
    destination_requirement: str
    replacement_source: str
    captures_source_text: bool
    supports_if_missing: bool
    def __init__(
        self,
        operation_kind: str,
        source_requirement: str,
        destination_requirement: str,
        replacement_source: str,
        captures_source_text: bool,
        supports_if_missing: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprOperationRequest: ...

class CrisprSelectionReport:
    owner_scope: str
    owner_selector: str
    owner_selector_family: str
    known_owner_selector: bool
    selector_kind: str
    selector_kind_family: str
    known_selector_kind: bool
    selection_intent: str
    selection_intent_family: str
    known_selection_intent: bool
    comment_region: str | None
    comment_region_family: str
    known_comment_region: bool
    comment_anchored: bool
    include_trailing_gap: bool
    def __init__(
        self,
        owner_scope: str,
        owner_selector: str,
        owner_selector_family: str,
        known_owner_selector: bool,
        selector_kind: str,
        selector_kind_family: str,
        known_selector_kind: bool,
        selection_intent: str,
        selection_intent_family: str,
        known_selection_intent: bool,
        comment_region_family: str,
        known_comment_region: bool,
        comment_anchored: bool,
        include_trailing_gap: bool,
        comment_region: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprSelectionReport: ...

class CrisprSelectionRequest:
    owner_scope: str
    owner_selector: str
    selector_kind: str
    selection_intent: str
    comment_region: str | None
    include_trailing_gap: bool
    def __init__(
        self,
        owner_scope: str,
        owner_selector: str,
        selector_kind: str,
        selection_intent: str,
        include_trailing_gap: bool,
        comment_region: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CrisprSelectionRequest: ...

class Diagnostic:
    severity: DiagnosticSeverity
    category: DiagnosticCategory
    message: str
    path: str | None
    review: ReviewDiagnosticDetail | None
    def __init__(
        self,
        severity: DiagnosticSeverity | str,
        category: DiagnosticCategory | str,
        message: str,
        path: str | None = None,
        review: ReviewDiagnosticDetail | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> Diagnostic: ...

class DiagnosticOrigin:
    layer: DiagnosticLayer
    provider_id: str | None
    backend_id: str | None
    package: str | None
    package_version: str | None
    native_code: str | None
    extra: dict[str, str]
    def __init__(
        self,
        layer: DiagnosticLayer | str,
        extra: dict[str, str],
        provider_id: str | None = None,
        backend_id: str | None = None,
        package: str | None = None,
        package_version: str | None = None,
        native_code: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DiagnosticOrigin: ...

class DiagnosticSourceRef:
    source_id: str
    role: SourceRole
    span: ResultSpan | None
    extra: dict[str, str]
    def __init__(
        self,
        source_id: str,
        role: SourceRole | str,
        extra: dict[str, str],
        span: ResultSpan | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DiagnosticSourceRef: ...

class DiagnosticSubjectRef:
    kind: str
    id: str
    extra: dict[str, str]
    def __init__(
        self,
        kind: str,
        id: str,  # noqa: A002
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DiagnosticSubjectRef: ...

class DiffPolicy:
    comparison_profile: str | None
    equivalence: list[str] | None
    source_preservation_evidence: bool | None
    extra: dict[str, str]
    def __init__(
        self,
        extra: dict[str, str],
        comparison_profile: str | None = None,
        equivalence: list[str] | None = None,
        source_preservation_evidence: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DiffPolicy: ...

class DiffSourceRegion:
    source_id: str
    source_role: SourceRole
    range: ByteRange
    sha256: str
    def __init__(
        self,
        source_id: str,
        source_role: SourceRole | str,
        range: ByteRange,  # noqa: A002
        sha256: str,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DiffSourceRegion: ...

class DirectionalMergePolicy:
    directional_merge: str
    render_policy: str
    fallback_policy: str | None
    extra: dict[str, str]
    def __init__(
        self,
        directional_merge: str,
        render_policy: str,
        extra: dict[str, str],
        fallback_policy: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DirectionalMergePolicy: ...

class DirectorySessionProfile:
    mode: DirectorySessionMode
    context: TemplateDestinationContext
    default_strategy: TemplateStrategy
    overrides: list[TemplateStrategyOverride]
    replacements: dict[str, str]
    allowed_families: list[str] | None
    config: TemplateTokenConfig | None
    def __init__(
        self,
        mode: DirectorySessionMode | str,
        context: TemplateDestinationContext,
        default_strategy: TemplateStrategy | str,
        overrides: list[TemplateStrategyOverride],
        replacements: dict[str, str],
        allowed_families: list[str] | None = None,
        config: TemplateTokenConfig | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DirectorySessionProfile: ...

class ExactConflictRegion:
    range: ResultRange
    byte_length: int
    sha256: str
    extra: dict[str, str]
    def __init__(
        self,
        range: ResultRange,  # noqa: A002
        byte_length: int,
        sha256: str,
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ExactConflictRegion: ...

class ExplicitSourceEdit:
    start_byte: int
    end_byte: int
    replacement: str
    def __init__(self, start_byte: int, end_byte: int, replacement: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ExplicitSourceEdit: ...

class LineEndings:
    lf: int
    crlf: int
    bare_cr: int
    def __init__(self, lf: int = ..., crlf: int = ..., bare_cr: int = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LineEndings: ...

class MergeConflict:
    conflict_id: str
    category: str
    path: str
    fallback_scope: str
    message: str
    alternatives: list[ConflictAlternative]
    def __init__(
        self,
        conflict_id: str,
        category: str,
        path: str,
        fallback_scope: str,
        message: str,
        alternatives: list[ConflictAlternative],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> MergeConflict: ...

class MergeProviderSelection:
    provider_id: str | None
    family: str | None
    dialect: str | None
    profile_id: str | None
    required_capabilities: list[str]
    extra: dict[str, str]
    def __init__(
        self,
        required_capabilities: list[str],
        extra: dict[str, str],
        provider_id: str | None = None,
        family: str | None = None,
        dialect: str | None = None,
        profile_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> MergeProviderSelection: ...

class NativeAnalysisRejection:
    code: str
    source_id: str
    source_role: SourceRole
    message: str
    def __init__(
        self,
        code: str,
        source_id: str,
        source_role: SourceRole | str,
        message: str,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeAnalysisRejection: ...

class NativeDiffRequest:
    request_id: str
    profile_id: str
    parses: list[ParseRequest]
    def __init__(self, request_id: str, profile_id: str, parses: list[ParseRequest]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeDiffRequest: ...

class NativeDiffResult:
    request_id: str
    profile_id: str
    ok: bool
    sources: list[SourceDescriptor]
    diff: OwnerDiff | None
    diagnostics: list[Diagnostic]
    input_parses: list[CoreParseResult]
    input_failure: ParserFailure | None
    analysis_rejections: list[NativeAnalysisRejection]
    def __init__(
        self,
        request_id: str,
        profile_id: str,
        ok: bool,
        sources: list[SourceDescriptor],
        diagnostics: list[Diagnostic],
        input_parses: list[CoreParseResult],
        analysis_rejections: list[NativeAnalysisRejection],
        diff: OwnerDiff | None = None,
        input_failure: ParserFailure | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeDiffResult: ...

class NativeExtension:
    schema: str
    namespace: str
    capabilities: list[str]
    payload: str
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        namespace: str,
        capabilities: list[str],
        payload: str,
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeExtension: ...

class NativeMergeProfile:
    id: str
    family: str
    operation: str
    entry_point: str
    analysis_crate: str
    merge_crate: str
    semantic_runtime: str
    parse_contract: str
    native_extension: str
    syntax_scope: list[str]
    limitations: list[str]
    experimental: bool
    approved_as_default: bool
    def __init__(
        self,
        id: str,  # noqa: A002
        family: str,
        operation: str,
        entry_point: str,
        analysis_crate: str,
        merge_crate: str,
        semantic_runtime: str,
        parse_contract: str,
        native_extension: str,
        syntax_scope: list[str],
        limitations: list[str],
        experimental: bool,
        approved_as_default: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeMergeProfile: ...

class NativeMergeResult:
    profile_id: str
    outcome: ThreeWayMergeOutcome
    diagnostics: list[Diagnostic]
    conflicts: list[MergeConflict]
    output: str | None
    policies: list[PolicyReference]
    rejected_parse: CoreParseResult | None
    input_parses: list[CoreParseResult]
    output_parse: CoreParseResult | None
    verification_failure: ParserFailure | None
    input_failure: ParserFailure | None
    analysis_rejections: list[NativeAnalysisRejection]
    sources: list[SourceDescriptor]
    output_source: SourceDescriptor | None
    source_segments: list[RetainedSourceSegment]
    def __init__(
        self,
        profile_id: str,
        outcome: ThreeWayMergeOutcome | str,
        diagnostics: list[Diagnostic],
        conflicts: list[MergeConflict],
        policies: list[PolicyReference],
        input_parses: list[CoreParseResult],
        analysis_rejections: list[NativeAnalysisRejection],
        sources: list[SourceDescriptor],
        source_segments: list[RetainedSourceSegment],
        output: str | None = None,
        rejected_parse: CoreParseResult | None = None,
        output_parse: CoreParseResult | None = None,
        verification_failure: ParserFailure | None = None,
        input_failure: ParserFailure | None = None,
        output_source: SourceDescriptor | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> NativeMergeResult: ...

class OperationParserSelection:
    backend: str | None
    preference: list[str]
    required_capabilities: list[str]
    profile_id: str | None
    language_version: str | None
    extra: dict[str, str]
    def __init__(
        self,
        preference: list[str],
        required_capabilities: list[str],
        extra: dict[str, str],
        backend: str | None = None,
        profile_id: str | None = None,
        language_version: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OperationParserSelection: ...

class OperationProfileCatalog:
    schema: str
    profiles: list[OperationProfileDeclaration]
    def __init__(self, schema: str, profiles: list[OperationProfileDeclaration]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OperationProfileCatalog: ...

class OperationProfileDeclaration:
    id: str
    provider_id: str
    family: str
    explicit_dialects: list[str]
    operations: list[OperationKind]
    semantic_runtime: str
    parser_contract: str
    required_native_extension: str | None
    parser_available: bool | None
    syntax_scope: list[str]
    limitations: list[str]
    experimental: bool
    approved_as_default: bool
    def __init__(
        self,
        id: str,  # noqa: A002
        provider_id: str,
        family: str,
        explicit_dialects: list[str],
        operations: list[OperationKind],
        semantic_runtime: str,
        parser_contract: str,
        syntax_scope: list[str],
        limitations: list[str],
        experimental: bool,
        approved_as_default: bool,
        required_native_extension: str | None = None,
        parser_available: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OperationProfileDeclaration: ...

class OperationRequest:
    schema: str
    request_id: str
    operation: OperationPolicy
    provider_selection: MergeProviderSelection
    parser_selection: OperationParserSelection
    sources: dict[SourceRole, OperationSource]
    path_name: str | None
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        request_id: str,
        operation: OperationPolicy,
        provider_selection: MergeProviderSelection,
        parser_selection: OperationParserSelection,
        sources: dict[SourceRole, OperationSource],
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        path_name: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OperationRequest: ...

class OperationResult:
    schema: str
    request_id: str
    operation: OperationKind
    ok: bool
    provider: ResultProvider
    profile: ResultProfile
    diagnostics: list[DiagnosticRecord]
    changes: list[ResultChange]
    conflicts: list[ConflictRecord]
    fallbacks: list[dict[str, str]]
    render_report: dict[str, str]
    verification: ResultVerification
    analysis: ResultAnalysis | None
    diff: ResultDiff | None
    output: str | None
    conflicted_output: str | None
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        request_id: str,
        operation: OperationKind | str,
        ok: bool,
        provider: ResultProvider,
        profile: ResultProfile,
        diagnostics: list[DiagnosticRecord],
        changes: list[ResultChange],
        conflicts: list[ConflictRecord],
        fallbacks: list[dict[str, str]],
        render_report: dict[str, str],
        verification: ResultVerification,
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        analysis: ResultAnalysis | None = None,
        diff: ResultDiff | None = None,
        output: str | None = None,
        conflicted_output: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OperationResult: ...

class OperationSource:
    source_id: str
    role: SourceRole
    byte_length: int
    sha256: str
    encoding: str
    content: str | None
    bytes: builtins.bytes | None
    reference: str | None
    bom: bool | None
    line_endings: LineEndings | None
    final_newline: bool | None
    extra: dict[str, str]
    def __init__(
        self,
        source_id: str,
        role: SourceRole | str,
        byte_length: int,
        sha256: str,
        encoding: str,
        extra: dict[str, str],
        content: str | None = None,
        bytes: builtins.bytes | None = None,  # noqa: A002
        reference: str | None = None,
        bom: bool | None = None,
        line_endings: LineEndings | None = None,
        final_newline: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OperationSource: ...

class OwnedSourceRegion:
    node_id: str
    region_kind: str
    start_byte: int
    end_byte: int
    start_line: int
    end_line: int
    def __init__(
        self,
        node_id: str,
        region_kind: str,
        start_byte: int,
        end_byte: int,
        start_line: int,
        end_line: int,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OwnedSourceRegion: ...

class OwnerChange:
    id: str
    owner_id: str
    before_path: str | None
    after_path: str | None
    kind: OwnerChangeKind
    before: DiffSourceRegion | None
    after: DiffSourceRegion | None
    def __init__(
        self,
        id: str,  # noqa: A002
        owner_id: str,
        kind: OwnerChangeKind | str,
        before_path: str | None = None,
        after_path: str | None = None,
        before: DiffSourceRegion | None = None,
        after: DiffSourceRegion | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OwnerChange: ...

class OwnerDiff:
    sources: list[SourceDescriptor]
    changes: list[OwnerChange]
    before_owner_order: list[str]
    after_owner_order: list[str]
    before_layout: list[DiffSourceRegion]
    after_layout: list[DiffSourceRegion]
    def __init__(
        self,
        sources: list[SourceDescriptor],
        changes: list[OwnerChange],
        before_owner_order: list[str],
        after_owner_order: list[str],
        before_layout: list[DiffSourceRegion],
        after_layout: list[DiffSourceRegion],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OwnerDiff: ...

class ParseBatchRequest:
    items: list[ParseRequest]
    def __init__(self, items: list[ParseRequest]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseBatchRequest: ...

class ParseBatchResult:
    items: list[ParseOutput]
    def __init__(self, items: list[ParseOutput]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseBatchResult: ...

class ParseComment:
    node_id: str
    native_kind: str
    attachment_hint: AttachmentHint
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        node_id: str,
        native_kind: str,
        attachment_hint: AttachmentHint | str,
        metadata: dict[str, str],
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseComment: ...

class ParseDiagnostic:
    id: str
    severity: ParseSeverity
    category: str
    code: str | None
    message: str
    source_role: SourceRole
    span: SourceSpan | None
    node_id: str | None
    blocking: bool
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        id: str,  # noqa: A002
        severity: ParseSeverity | str,
        category: str,
        message: str,
        source_role: SourceRole | str,
        blocking: bool,
        metadata: dict[str, str],
        extra: dict[str, str],
        code: str | None = None,
        span: SourceSpan | None = None,
        node_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseDiagnostic: ...

class ParseLimits:
    max_batch_items: int
    max_input_bytes: int
    max_nodes: int
    max_diagnostics: int
    timeout_millis: int | None
    def __init__(
        self,
        max_batch_items: int,
        max_input_bytes: int,
        max_nodes: int,
        max_diagnostics: int,
        timeout_millis: int | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseLimits: ...

class ParseNode:
    id: str
    kind: str
    native_type: str
    role: NodeRole
    named: bool
    missing: bool
    has_error: bool
    span: SourceSpan
    parent_id: str | None
    children: list[ChildEdge]
    semantic_roles: list[str]
    unsupported_features: list[str]
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        id: str,  # noqa: A002
        type: str,  # noqa: A002
        native_type: str,
        role: NodeRole | str,
        named: bool,
        missing: bool,
        has_error: bool,
        span: SourceSpan,
        children: list[ChildEdge],
        semantic_roles: list[str],
        unsupported_features: list[str],
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        parent_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseNode: ...

class ParseOptions:
    comments: bool
    tokens: bool
    diagnostics: bool
    native_extensions: bool
    def __init__(
        self,
        comments: bool = ...,
        tokens: bool = ...,
        diagnostics: bool = ...,
        native_extensions: bool = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseOptions: ...

class ParseOutput:
    request_id: str
    source: SourceDescriptor
    ok: bool
    root_id: str | None
    nodes: list[ParseNode]
    comments: list[ParseComment]
    diagnostics: list[ParseDiagnostic]
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        request_id: str,
        source: SourceDescriptor,
        ok: bool,
        nodes: list[ParseNode],
        comments: list[ParseComment],
        diagnostics: list[ParseDiagnostic],
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        root_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseOutput: ...

class ParseRequest:
    schema: str
    request_id: str
    source: SourceInput
    language: str
    dialect: str | None
    selection: ParserSelection
    options: ParseOptions
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        request_id: str,
        source: SourceInput,
        language: str,
        selection: ParserSelection,
        options: ParseOptions,
        metadata: dict[str, str],
        extra: dict[str, str],
        dialect: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParseRequest: ...

class ParserCandidate:
    backend_id: str
    rejections: list[str]
    available: bool | None
    loadable: bool | None
    probe_fault: str | None
    request_preference: int | None
    profile_preference: int | None
    priority: int
    selected: bool
    def __init__(
        self,
        backend_id: str,
        rejections: list[str],
        priority: int,
        selected: bool,
        available: bool | None = None,
        loadable: bool | None = None,
        probe_fault: str | None = None,
        request_preference: int | None = None,
        profile_preference: int | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserCandidate: ...

class ParserFailure:
    code: str
    message: str
    backend_id: str | None
    native_code: str | None
    native_message: str | None
    source_id: str | None
    selection: SelectionReport | None
    def __init__(
        self,
        code: str,
        message: str,
        backend_id: str | None = None,
        native_code: str | None = None,
        native_message: str | None = None,
        source_id: str | None = None,
        selection: SelectionReport | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserFailure: ...

class ParserProbeRequest:
    language: str
    dialect: str | None
    def __init__(self, language: str, dialect: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserProbeRequest: ...

class ParserProbeResult:
    available: bool
    loadable: bool
    def __init__(self, available: bool, loadable: bool) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserProbeResult: ...

class ParserProviderDescriptor:
    id: str
    family: str
    runtime: str
    package: str
    package_version: str
    parser: str
    parser_version: str
    grammar: str | None
    grammar_version: str | None
    languages: list[str]
    dialects: list[str]
    contracts: list[str]
    capabilities: list[str]
    probe_id: str
    priority: int
    metadata: dict[str, str]
    extensions: list[NativeExtension]
    def __init__(
        self,
        id: str,  # noqa: A002
        family: str,
        runtime: str,
        package: str,
        package_version: str,
        parser: str,
        parser_version: str,
        languages: list[str],
        dialects: list[str],
        contracts: list[str],
        capabilities: list[str],
        probe_id: str,
        priority: int,
        metadata: dict[str, str],
        extensions: list[NativeExtension],
        grammar: str | None = None,
        grammar_version: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserProviderDescriptor: ...

class ParserRegistryInventory:
    schema: str
    generation: int
    descriptor_digest: str
    providers: list[ParserProviderDescriptor]
    def __init__(
        self,
        schema: str,
        generation: int,
        descriptor_digest: str,
        providers: list[ParserProviderDescriptor],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserRegistryInventory: ...

class ParserSelection:
    backend_id: str | None
    preference: list[str]
    required_capabilities: list[str]
    def __init__(
        self,
        preference: list[str],
        required_capabilities: list[str],
        backend_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserSelection: ...

class ParserSelectionRequest:
    language: str
    dialect: str | None
    selection: ParserSelection
    options: ParseOptions
    def __init__(
        self,
        language: str,
        selection: ParserSelection,
        options: ParseOptions,
        dialect: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ParserSelectionRequest: ...

class PolicyReference:
    surface: PolicySurface
    name: str
    def __init__(self, surface: PolicySurface | str, name: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> PolicyReference: ...

class PortableConflict:
    schema: str
    id: str
    operation: OperationKind
    category: ConflictCategory
    code: str
    message: str | None
    subject: ConflictSubject
    roles: list[SourceRole]
    alternatives: list[ConflictSourceAlternative]
    classification: ConflictClassification
    localization: ConflictLocalization
    resolution: ConflictResolution
    diagnostic_ids: list[str]
    change_ids: list[str]
    decision_ids: list[str]
    render_fragment_ids: list[str]
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        id: str,  # noqa: A002
        operation: OperationKind | str,
        category: ConflictCategory | str,
        code: str,
        subject: ConflictSubject,
        roles: list[SourceRole],
        alternatives: list[ConflictSourceAlternative],
        classification: ConflictClassification,
        localization: ConflictLocalization,
        resolution: ConflictResolution,
        diagnostic_ids: list[str],
        change_ids: list[str],
        decision_ids: list[str],
        render_fragment_ids: list[str],
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        message: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> PortableConflict: ...

class PortableDiagnostic:
    schema: str
    id: str
    sequence: int
    severity: DiagnosticSeverity
    category: PortableCategory
    code: str
    message: str
    blocking: bool
    operation: OperationKind | None
    request_id: str | None
    source_refs: list[DiagnosticSourceRef]
    subject_refs: list[DiagnosticSubjectRef] | None
    cause_ids: list[str]
    related_ids: list[str]
    origin: DiagnosticOrigin
    data: dict[str, str]
    extensions: list[NativeExtension]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        schema: str,
        id: str,  # noqa: A002
        sequence: int,
        severity: DiagnosticSeverity | str,
        category: PortableCategory | str,
        code: str,
        message: str,
        blocking: bool,
        source_refs: list[DiagnosticSourceRef],
        cause_ids: list[str],
        related_ids: list[str],
        origin: DiagnosticOrigin,
        data: dict[str, str],
        extensions: list[NativeExtension],
        metadata: dict[str, str],
        extra: dict[str, str],
        operation: OperationKind | str | None = None,
        request_id: str | None = None,
        subject_refs: list[DiagnosticSubjectRef] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> PortableDiagnostic: ...

class PreservationProperty:
    property: str
    required: bool
    status: str
    extra: dict[str, str]
    def __init__(
        self,
        property: str,  # noqa: A002
        required: bool,
        status: str,
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> PreservationProperty: ...

class ProbeBatchRequest:
    items: list[ParserProbeRequest]
    def __init__(self, items: list[ParserProbeRequest]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ProbeBatchRequest: ...

class ProbeBatchResult:
    items: list[ParserProbeResult]
    def __init__(self, items: list[ParserProbeResult]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ProbeBatchResult: ...

class ResultAnalysis:
    schema: str
    extra: dict[str, str]
    def __init__(self, schema: str, extra: dict[str, str]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultAnalysis: ...

class ResultChange:
    id: str
    classification: str
    subject_ref: str | None
    path: str | None
    role_states: dict[str, str]
    source_spans: dict[SourceRole, ResultSpan]
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        id: str,  # noqa: A002
        classification: str,
        role_states: dict[str, str],
        source_spans: dict[SourceRole, ResultSpan],
        metadata: dict[str, str],
        extra: dict[str, str],
        subject_ref: str | None = None,
        path: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultChange: ...

class ResultConflict:
    id: str
    category: str
    subject_ref: str | None
    path: str | None
    roles: list[SourceRole]
    source_regions: list[ResultSourceRegion]
    localized: bool
    resolution: str
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        id: str,  # noqa: A002
        category: str,
        roles: list[SourceRole],
        source_regions: list[ResultSourceRegion],
        localized: bool,
        resolution: str,
        metadata: dict[str, str],
        extra: dict[str, str],
        subject_ref: str | None = None,
        path: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultConflict: ...

class ResultDiagnostic:
    id: str
    severity: str
    category: str
    code: str
    message: str
    blocking: bool
    source_role: SourceRole | None
    span: ResultSpan | None
    metadata: dict[str, str]
    extra: dict[str, str]
    def __init__(
        self,
        id: str,  # noqa: A002
        severity: str,
        category: str,
        code: str,
        message: str,
        blocking: bool,
        metadata: dict[str, str],
        extra: dict[str, str],
        source_role: SourceRole | str | None = None,
        span: ResultSpan | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultDiagnostic: ...

class ResultDiff:
    change_ids: list[str]
    extra: dict[str, str]
    def __init__(self, change_ids: list[str], extra: dict[str, str]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultDiff: ...

class ResultParserSelection:
    requested_backend: str | None
    selected_backend: str | None
    selection_mode: str | None
    extra: dict[str, str]
    def __init__(
        self,
        extra: dict[str, str],
        requested_backend: str | None = None,
        selected_backend: str | None = None,
        selection_mode: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultParserSelection: ...

class ResultPoint:
    row: int
    column: int
    extra: dict[str, str]
    def __init__(self, row: int, column: int, extra: dict[str, str]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultPoint: ...

class ResultProfile:
    profile_id: str | None
    parser: ResultParserSelection | None
    extra: dict[str, str]
    def __init__(
        self,
        extra: dict[str, str],
        profile_id: str | None = None,
        parser: ResultParserSelection | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultProfile: ...

class ResultProvider:
    provider_id: str | None
    family: str | None
    delegation: list[ResultProvider] | None
    extra: dict[str, str]
    def __init__(
        self,
        extra: dict[str, str],
        provider_id: str | None = None,
        family: str | None = None,
        delegation: list[ResultProvider] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultProvider: ...

class ResultRange:
    start_byte: int
    end_byte: int
    extra: dict[str, str]
    def __init__(self, start_byte: int, end_byte: int, extra: dict[str, str]) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultRange: ...

class ResultSourceRegion:
    source_id: str
    source_role: SourceRole
    range: ResultRange
    sha256: str | None
    extra: dict[str, str]
    def __init__(
        self,
        source_id: str,
        source_role: SourceRole | str,
        range: ResultRange,  # noqa: A002
        extra: dict[str, str],
        sha256: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultSourceRegion: ...

class ResultSpan:
    range: ResultRange
    start_point: ResultPoint
    end_point: ResultPoint
    extra: dict[str, str]
    def __init__(
        self,
        range: ResultRange,  # noqa: A002
        start_point: ResultPoint,
        end_point: ResultPoint,
        extra: dict[str, str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultSpan: ...

class ResultVerification:
    consumed_source_roles: list[SourceRole] | None
    directional_roles_preserved: bool | None
    base_participated: bool | None
    classification_reached: bool | None
    output_reparsed: bool | None
    structural_equivalence: bool | None
    preservation: list[PreservationProperty] | None
    retained_source_regions: list[ResultSourceRegion] | None
    extra: dict[str, str]
    def __init__(
        self,
        extra: dict[str, str],
        consumed_source_roles: list[SourceRole] | None = None,
        directional_roles_preserved: bool | None = None,
        base_participated: bool | None = None,
        classification_reached: bool | None = None,
        output_reparsed: bool | None = None,
        structural_equivalence: bool | None = None,
        preservation: list[PreservationProperty] | None = None,
        retained_source_regions: list[ResultSourceRegion] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResultVerification: ...

class RetainedSourceSegment:
    id: str
    source_id: str
    source_role: SourceRole
    source_range: ByteRange
    output_range: ByteRange
    sha256: str
    owner_id: str | None
    def __init__(
        self,
        id: str,  # noqa: A002
        source_id: str,
        source_role: SourceRole | str,
        source_range: ByteRange,
        output_range: ByteRange,
        sha256: str,
        owner_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> RetainedSourceSegment: ...

class ReviewDiagnosticDetail:
    request_id: str | None
    action: ReviewDecisionAction | None
    reason: ReviewDiagnosticReason | None
    payload_kind: str | None
    expected_family: str | None
    provided_family: str | None
    def __init__(
        self,
        request_id: str | None = None,
        action: ReviewDecisionAction | str | None = None,
        reason: ReviewDiagnosticReason | str | None = None,
        payload_kind: str | None = None,
        expected_family: str | None = None,
        provided_family: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ReviewDiagnosticDetail: ...

class SelectionReport:
    requested: ParserSelection
    generation: int
    digest: str
    candidates: list[ParserCandidate]
    selected_backend: str | None
    def __init__(
        self,
        requested: ParserSelection,
        generation: int,
        digest: str,
        candidates: list[ParserCandidate],
        selected_backend: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SelectionReport: ...

class SessionDiagnostic:
    severity: DiagnosticSeverity
    category: DiagnosticCategory
    reason: str
    path: str | None
    family: str | None
    message: str
    def __init__(
        self,
        severity: DiagnosticSeverity | str,
        category: DiagnosticCategory | str,
        reason: str,
        message: str,
        path: str | None = None,
        family: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SessionDiagnostic: ...

class SourceDescriptor:
    source_id: str
    role: SourceRole
    byte_length: int
    sha256: str
    encoding: SourceEncoding
    bom: bool
    line_endings: LineEndings
    final_newline: bool
    def __init__(
        self,
        source_id: str,
        role: SourceRole | str,
        byte_length: int,
        sha256: str,
        encoding: SourceEncoding | str,
        bom: bool,
        line_endings: LineEndings,
        final_newline: bool,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceDescriptor: ...

class SourceEditLimits:
    max_input_bytes: int
    max_output_bytes: int
    max_edits: int
    def __init__(self, max_input_bytes: int, max_output_bytes: int, max_edits: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceEditLimits: ...

class SourceEditRequest:
    request_id: str
    source: SourceInput
    edits: list[ExplicitSourceEdit]
    def __init__(
        self,
        request_id: str,
        source: SourceInput,
        edits: list[ExplicitSourceEdit],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceEditRequest: ...

class SourceEditResult:
    request_id: str
    source: SourceDescriptor
    output: str
    edit_count: int
    def __init__(
        self,
        request_id: str,
        source: SourceDescriptor,
        output: str,
        edit_count: int,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceEditResult: ...

class SourceInput:
    descriptor: SourceDescriptor
    bytes: builtins.bytes
    def __init__(
        self,
        descriptor: SourceDescriptor,
        bytes: builtins.bytes,  # noqa: A002
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceInput: ...

class SourcePoint:
    row: int
    column: int
    def __init__(self, row: int, column: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourcePoint: ...

class SourceSpan:
    range: ByteRange
    start_point: SourcePoint
    end_point: SourcePoint
    def __init__(
        self,
        range: ByteRange,  # noqa: A002
        start_point: SourcePoint,
        end_point: SourcePoint,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SourceSpan: ...

class TemplateDestinationContext:
    project_name: str | None
    def __init__(self, project_name: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDestinationContext: ...

class TemplateDirectoryApplyReport:
    entries: list[TemplateDirectoryApplyReportEntry]
    summary: TemplateDirectoryApplyReportSummary
    def __init__(
        self,
        entries: list[TemplateDirectoryApplyReportEntry],
        summary: TemplateDirectoryApplyReportSummary,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDirectoryApplyReport: ...

class TemplateDirectoryApplyReportEntry:
    template_source_path: str
    logical_destination_path: str
    destination_path: str | None
    execution_action: TemplateExecutionAction
    status: TemplateTreeRunStatus
    written: bool
    def __init__(
        self,
        template_source_path: str,
        logical_destination_path: str,
        execution_action: TemplateExecutionAction | str,
        status: TemplateTreeRunStatus | str,
        written: bool,
        destination_path: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDirectoryApplyReportEntry: ...

class TemplateDirectoryApplyReportSummary:
    created: int
    updated: int
    kept: int
    blocked: int
    omitted: int
    written: int
    def __init__(
        self,
        created: int,
        updated: int,
        kept: int,
        blocked: int,
        omitted: int,
        written: int,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDirectoryApplyReportSummary: ...

class TemplateDirectoryPlanReport:
    entries: list[TemplateDirectoryPlanReportEntry]
    summary: TemplateDirectoryPlanReportSummary
    def __init__(
        self,
        entries: list[TemplateDirectoryPlanReportEntry],
        summary: TemplateDirectoryPlanReportSummary,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDirectoryPlanReport: ...

class TemplateDirectoryPlanReportEntry:
    template_source_path: str
    logical_destination_path: str
    destination_path: str | None
    execution_action: TemplateExecutionAction
    write_action: str
    status: TemplateDirectoryPlanStatus
    previewable: bool
    def __init__(
        self,
        template_source_path: str,
        logical_destination_path: str,
        execution_action: TemplateExecutionAction | str,
        write_action: str,
        status: TemplateDirectoryPlanStatus | str,
        previewable: bool,
        destination_path: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDirectoryPlanReportEntry: ...

class TemplateDirectoryPlanReportSummary:
    create: int
    update: int
    keep: int
    blocked: int
    omitted: int
    def __init__(self, create: int, update: int, keep: int, blocked: int, omitted: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDirectoryPlanReportSummary: ...

class TemplateDirectoryRunnerReport:
    plan_report: TemplateDirectoryPlanReport
    preview: TemplatePreviewResult | None
    run_report: TemplateTreeRunReport | None
    apply_report: TemplateDirectoryApplyReport | None
    def __init__(
        self,
        plan_report: TemplateDirectoryPlanReport,
        preview: TemplatePreviewResult | None = None,
        run_report: TemplateTreeRunReport | None = None,
        apply_report: TemplateDirectoryApplyReport | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateDirectoryRunnerReport: ...

class TemplatePreviewResult:
    result_files: dict[str, str]
    created_paths: list[str]
    updated_paths: list[str]
    kept_paths: list[str]
    blocked_paths: list[str]
    omitted_paths: list[str]
    def __init__(
        self,
        result_files: dict[str, str],
        created_paths: list[str],
        updated_paths: list[str],
        kept_paths: list[str],
        blocked_paths: list[str],
        omitted_paths: list[str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplatePreviewResult: ...

class TemplateProfileRequest:
    profile_name: str
    profiles: dict[str, DirectorySessionProfile]
    options: TemplateSessionOptions
    def __init__(
        self,
        profile_name: str,
        profiles: dict[str, DirectorySessionProfile],
        options: TemplateSessionOptions,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateProfileRequest: ...

class TemplateSessionOptions:
    mode: DirectorySessionMode
    template_root: str
    destination_root: str
    context: TemplateDestinationContext
    default_strategy: TemplateStrategy
    overrides: list[TemplateStrategyOverride]
    replacements: dict[str, str]
    allowed_families: list[str] | None
    config: TemplateTokenConfig | None
    def __init__(
        self,
        mode: DirectorySessionMode | str,
        template_root: str,
        destination_root: str,
        context: TemplateDestinationContext,
        default_strategy: TemplateStrategy | str,
        overrides: list[TemplateStrategyOverride],
        replacements: dict[str, str],
        allowed_families: list[str] | None = None,
        config: TemplateTokenConfig | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateSessionOptions: ...

class TemplateSessionPlanReport:
    mode: DirectorySessionMode
    runner_report: TemplateDirectoryRunnerReport
    def __init__(
        self,
        mode: DirectorySessionMode | str,
        runner_report: TemplateDirectoryRunnerReport,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateSessionPlanReport: ...

class TemplateSessionRequestReport:
    request_kind: str
    profile_name: str | None
    mode: DirectorySessionMode
    ready: bool
    diagnostics: list[SessionDiagnostic]
    resolved_options: TemplateSessionOptions | None
    def __init__(
        self,
        request_kind: str,
        mode: DirectorySessionMode | str,
        ready: bool,
        diagnostics: list[SessionDiagnostic],
        profile_name: str | None = None,
        resolved_options: TemplateSessionOptions | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateSessionRequestReport: ...

class TemplateStrategyOverride:
    path: str
    strategy: TemplateStrategy
    def __init__(self, path: str, strategy: TemplateStrategy | str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateStrategyOverride: ...

class TemplateTokenConfig:
    pre: str
    post: str
    separators: list[str]
    min_segments: int
    max_segments: int | None
    segment_pattern: str
    def __init__(
        self,
        pre: str,
        post: str,
        separators: list[str],
        min_segments: int,
        segment_pattern: str,
        max_segments: int | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateTokenConfig: ...

class TemplateTreeRunReport:
    entries: list[TemplateTreeRunReportEntry]
    summary: TemplateTreeRunReportSummary
    def __init__(
        self,
        entries: list[TemplateTreeRunReportEntry],
        summary: TemplateTreeRunReportSummary,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateTreeRunReport: ...

class TemplateTreeRunReportEntry:
    template_source_path: str
    logical_destination_path: str
    destination_path: str | None
    execution_action: TemplateExecutionAction
    status: TemplateTreeRunStatus
    def __init__(
        self,
        template_source_path: str,
        logical_destination_path: str,
        execution_action: TemplateExecutionAction | str,
        status: TemplateTreeRunStatus | str,
        destination_path: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateTreeRunReportEntry: ...

class TemplateTreeRunReportSummary:
    created: int
    updated: int
    kept: int
    blocked: int
    omitted: int
    def __init__(
        self,
        created: int,
        updated: int,
        kept: int,
        blocked: int,
        omitted: int,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TemplateTreeRunReportSummary: ...

class ThreeWayMergePolicy:
    render_policy: str
    fallback_policy: str | None
    conflict_marker_size: int | None
    labels: dict[str, str] | None
    extra: dict[str, str]
    def __init__(
        self,
        render_policy: str,
        extra: dict[str, str],
        fallback_policy: str | None = None,
        conflict_marker_size: int | None = None,
        labels: dict[str, str] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ThreeWayMergePolicy: ...

class OperationControl:
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    @staticmethod
    def new() -> OperationControl: ...

class AlternativeState:
    PRESENT: AlternativeState = ...
    ABSENT: AlternativeState = ...
    INVALID: AlternativeState = ...
    OPAQUE: AlternativeState = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class AttachmentHint:
    LEADING: AttachmentHint = ...
    INLINE: AttachmentHint = ...
    TRAILING: AttachmentHint = ...
    PREAMBLE: AttachmentHint = ...
    POSTLUDE: AttachmentHint = ...
    ORPHAN: AttachmentHint = ...
    UNKNOWN: AttachmentHint = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ConflictAlternativeState:
    PRESENT: ConflictAlternativeState = ...
    ABSENT: ConflictAlternativeState = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ConflictCategory:
    CONTENT: ConflictCategory = ...
    DELETE_MODIFY: ConflictCategory = ...
    ADD_ADD: ConflictCategory = ...
    MOVE: ConflictCategory = ...
    RENAME: ConflictCategory = ...
    ORDER: ConflictCategory = ...
    IDENTITY: ConflictCategory = ...
    OWNERSHIP: ConflictCategory = ...
    SYNTAX: ConflictCategory = ...
    BINARY_OVERLAP: ConflictCategory = ...
    ARCHIVE_ENTRY: ConflictCategory = ...
    PROVIDER_SPECIFIC: ConflictCategory = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ConflictRecord:
    canonical: PortableConflict | None
    migration: ResultConflict | None
    @staticmethod
    def from_canonical(value: PortableConflict) -> ConflictRecord: ...

    @staticmethod
    def from_migration(value: ResultConflict) -> ConflictRecord: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class CrisprLimitOperator:
    EQUAL: CrisprLimitOperator = ...
    NOT_EQUAL: CrisprLimitOperator = ...
    AT_MOST: CrisprLimitOperator = ...
    AT_LEAST: CrisprLimitOperator = ...
    LESS_THAN: CrisprLimitOperator = ...
    GREATER_THAN: CrisprLimitOperator = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class DiagnosticCategory:
    PARSE_ERROR: DiagnosticCategory = ...
    DESTINATION_PARSE_ERROR: DiagnosticCategory = ...
    UNSUPPORTED_FEATURE: DiagnosticCategory = ...
    FALLBACK_APPLIED: DiagnosticCategory = ...
    AMBIGUITY: DiagnosticCategory = ...
    MERGE_CONFLICT: DiagnosticCategory = ...
    KIND_MISMATCH: DiagnosticCategory = ...
    UNSUPPORTED_VERSION: DiagnosticCategory = ...
    ASSUMED_DEFAULT: DiagnosticCategory = ...
    CONFIGURATION_ERROR: DiagnosticCategory = ...
    REPLAY_REJECTED: DiagnosticCategory = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class DiagnosticLayer:
    TRANSPORT: DiagnosticLayer = ...
    REGISTRY: DiagnosticLayer = ...
    PARSER: DiagnosticLayer = ...
    ANALYSIS: DiagnosticLayer = ...
    PROVIDER: DiagnosticLayer = ...
    RENDERER: DiagnosticLayer = ...
    VERIFIER: DiagnosticLayer = ...
    ADAPTER: DiagnosticLayer = ...
    RUNNER: DiagnosticLayer = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class DiagnosticRecord:
    canonical: PortableDiagnostic | None
    migration: ResultDiagnostic | None
    @staticmethod
    def from_canonical(value: PortableDiagnostic) -> DiagnosticRecord: ...

    @staticmethod
    def from_migration(value: ResultDiagnostic) -> DiagnosticRecord: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class DiagnosticSeverity:
    INFO: DiagnosticSeverity = ...
    WARNING: DiagnosticSeverity = ...
    ERROR: DiagnosticSeverity = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class DirectorySessionMode:
    PLAN: DirectorySessionMode = ...
    APPLY: DirectorySessionMode = ...
    REAPPLY: DirectorySessionMode = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class LocalizationStatus:
    EXACT: LocalizationStatus = ...
    OWNER: LocalizationStatus = ...
    COARSE: LocalizationStatus = ...
    WHOLE_DOCUMENT: LocalizationStatus = ...
    UNAVAILABLE: LocalizationStatus = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class NodeRole:
    STRUCTURAL: NodeRole = ...
    TOKEN: NodeRole = ...
    TRIVIA: NodeRole = ...
    COMMENT: NodeRole = ...
    DELIMITER: NodeRole = ...
    SEPARATOR: NodeRole = ...
    VIRTUAL: NodeRole = ...
    ERROR: NodeRole = ...
    OPAQUE: NodeRole = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class OperationKind:
    ANALYZE: OperationKind = ...
    DIFF2: OperationKind = ...
    MERGE2: OperationKind = ...
    MERGE3: OperationKind = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class OperationPolicyAnalyzeVariant(TypedDict):
    operation: Literal["analyze"]
    policy: AnalyzePolicy

class OperationPolicyDiff2Variant(TypedDict):
    operation: Literal["diff2"]
    policy: DiffPolicy

class OperationPolicyMerge2Variant(TypedDict):
    operation: Literal["merge2"]
    policy: DirectionalMergePolicy

class OperationPolicyMerge3Variant(TypedDict):
    operation: Literal["merge3"]
    policy: ThreeWayMergePolicy

class OperationPolicy:
    operation: str
    analyze: AnalyzePolicy | None
    diff2: DiffPolicy | None
    merge2: DirectionalMergePolicy | None
    merge3: ThreeWayMergePolicy | None
    @staticmethod
    def from_analyze(value: AnalyzePolicy) -> OperationPolicy: ...

    @staticmethod
    def from_diff2(value: DiffPolicy) -> OperationPolicy: ...

    @staticmethod
    def from_merge2(value: DirectionalMergePolicy) -> OperationPolicy: ...

    @staticmethod
    def from_merge3(value: ThreeWayMergePolicy) -> OperationPolicy: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class OwnerChangeKind:
    ADDED: OwnerChangeKind = ...
    DELETED: OwnerChangeKind = ...
    EDITED: OwnerChangeKind = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ParseSeverity:
    INFO: ParseSeverity = ...
    WARNING: ParseSeverity = ...
    ERROR: ParseSeverity = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class PolicySurface:
    FALLBACK: PolicySurface = ...
    ARRAY: PolicySurface = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class PortableCategory:
    PARSE_ERROR: PortableCategory = ...
    DESTINATION_PARSE_ERROR: PortableCategory = ...
    INVALID_REQUEST: PortableCategory = ...
    CONFIGURATION_ERROR: PortableCategory = ...
    SELECTION_ERROR: PortableCategory = ...
    BACKEND_UNAVAILABLE: PortableCategory = ...
    UNSUPPORTED_FEATURE: PortableCategory = ...
    AMBIGUITY: PortableCategory = ...
    ANALYSIS_ERROR: PortableCategory = ...
    MERGE_CONFLICT: PortableCategory = ...
    RENDER_ERROR: PortableCategory = ...
    PRESERVATION_ERROR: PortableCategory = ...
    VERIFICATION_ERROR: PortableCategory = ...
    FALLBACK_APPLIED: PortableCategory = ...
    ASSUMED_DEFAULT: PortableCategory = ...
    CANCELLED: PortableCategory = ...
    DEADLINE_EXCEEDED: PortableCategory = ...
    RESOURCE_LIMIT: PortableCategory = ...
    REPLAY_REJECTED: PortableCategory = ...
    INTERNAL_ERROR: PortableCategory = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ResolutionStatus:
    UNRESOLVED: ResolutionStatus = ...
    RESOLVED: ResolutionStatus = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ResolutionStrategy:
    NONE: ResolutionStrategy = ...
    SELECT_ROLE: ResolutionStrategy = ...
    COMBINE: ResolutionStrategy = ...
    POLICY: ResolutionStrategy = ...
    CUSTOM: ResolutionStrategy = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ReviewDecisionAction:
    ACCEPT_DEFAULT_CONTEXT: ReviewDecisionAction = ...
    PROVIDE_EXPLICIT_CONTEXT: ReviewDecisionAction = ...
    APPLY_DELEGATED_CHILD_GROUP: ReviewDecisionAction = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ReviewDiagnosticReason:
    MISSING_REQUIRED_PAYLOAD: ReviewDiagnosticReason = ...
    FAMILY_MISMATCH: ReviewDiagnosticReason = ...
    REQUEST_NOT_FOUND: ReviewDiagnosticReason = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class SourceEncoding:
    UTF8: SourceEncoding = ...
    BINARY: SourceEncoding = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class SourceRevision:
    BASE: SourceRevision = ...
    OURS: SourceRevision = ...
    THEIRS: SourceRevision = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class SourceRole:
    SOURCE: SourceRole = ...
    BEFORE: SourceRole = ...
    AFTER: SourceRole = ...
    INCOMING: SourceRole = ...
    CURRENT: SourceRole = ...
    BASE: SourceRole = ...
    OURS: SourceRole = ...
    THEIRS: SourceRole = ...
    OUTPUT: SourceRole = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class TemplateDirectoryPlanStatus:
    CREATE: TemplateDirectoryPlanStatus = ...
    UPDATE: TemplateDirectoryPlanStatus = ...
    KEEP: TemplateDirectoryPlanStatus = ...
    BLOCKED: TemplateDirectoryPlanStatus = ...
    OMITTED: TemplateDirectoryPlanStatus = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class TemplateExecutionAction:
    BLOCKED: TemplateExecutionAction = ...
    OMIT: TemplateExecutionAction = ...
    KEEP: TemplateExecutionAction = ...
    RAW_COPY: TemplateExecutionAction = ...
    WRITE_PREPARED_CONTENT: TemplateExecutionAction = ...
    MERGE_PREPARED_CONTENT: TemplateExecutionAction = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class TemplateStrategy:
    MERGE: TemplateStrategy = ...
    ACCEPT_TEMPLATE: TemplateStrategy = ...
    KEEP_DESTINATION: TemplateStrategy = ...
    RAW_COPY: TemplateStrategy = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class TemplateTreeRunStatus:
    CREATED: TemplateTreeRunStatus = ...
    UPDATED: TemplateTreeRunStatus = ...
    KEPT: TemplateTreeRunStatus = ...
    BLOCKED: TemplateTreeRunStatus = ...
    OMITTED: TemplateTreeRunStatus = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ThreeWayMergeOutcome:
    CLEAN: ThreeWayMergeOutcome = ...
    CONFLICT: ThreeWayMergeOutcome = ...
    ERROR: ThreeWayMergeOutcome = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

def apply_explicit_source_edits(
    request: SourceEditRequest,
    limits: SourceEditLimits,
) -> SourceEditResult: ...

def create_operation_control() -> OperationControl: ...
def diff_native_owners(request: NativeDiffRequest, limits: ParseLimits) -> NativeDiffResult: ...
def diff_native_owners_controlled(
    request: NativeDiffRequest,
    limits: ParseLimits,
    control: OperationControl,
) -> NativeDiffResult: ...

def execute_operation(request: OperationRequest, limits: ParseLimits) -> OperationResult: ...
def execute_operation_controlled(
    request: OperationRequest,
    limits: ParseLimits,
    control: OperationControl,
) -> OperationResult: ...

def merge_python_declarations(
    requests: list[ParseRequest],
    limits: ParseLimits,
) -> NativeMergeResult: ...

def merge_python_declarations_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> NativeMergeResult: ...

def merge_yaml_mapping(requests: list[ParseRequest], limits: ParseLimits) -> NativeMergeResult: ...
def merge_yaml_mapping_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> NativeMergeResult: ...

def native_merge_profiles() -> list[NativeMergeProfile]: ...
def operation_profile_catalog() -> OperationProfileCatalog: ...
def parse_sources(requests: list[ParseRequest], limits: ParseLimits) -> list[CoreParseResult]: ...
def parse_sources_controlled(
    requests: list[ParseRequest],
    limits: ParseLimits,
    control: OperationControl,
) -> list[CoreParseResult]: ...

def parser_registry_inventory() -> ParserRegistryInventory: ...
def parser_selection_report(
    request: ParserSelectionRequest,
    limits: ParseLimits,
) -> SelectionReport: ...

def parser_selection_report_controlled(
    request: ParserSelectionRequest,
    limits: ParseLimits,
    control: OperationControl,
) -> SelectionReport: ...

def plan_template_directory(options: TemplateSessionOptions) -> TemplateSessionPlanReport: ...
def register_language_pack_parser(
    id: str,  # noqa: A002
    language: str,
) -> ParserProviderDescriptor: ...

def register_parser_host(host: object) -> None: ...
def replace_parser_host(host: object, expected_generation: int) -> int: ...
def report_structural_boundary() -> CrisprBoundaryReport: ...
def report_structural_destination(request: CrisprDestinationRequest) -> CrisprDestinationReport: ...
def report_structural_limit(request: CrisprLimitRequest) -> CrisprLimitReport: ...
def report_structural_match(request: CrisprMatchRequest) -> CrisprMatchReport: ...
def report_structural_operations(
    requests: list[CrisprOperationRequest],
) -> CrisprBatchOperationReport: ...

def report_structural_selection(request: CrisprSelectionRequest) -> CrisprSelectionReport: ...
def report_template_options(options: TemplateSessionOptions) -> TemplateSessionRequestReport: ...
def report_template_profile(request: TemplateProfileRequest) -> TemplateSessionRequestReport: ...
def unregister_parser_host(
    id: str,  # noqa: A002
) -> None: ...

def unregister_parser_provider(
    id: str,  # noqa: A002
) -> None: ...
