# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de96bfff018ef40e49f9424eb746ee08bb5d84b035ab8b76dd708ad6ed45d0aa
# To regenerate: alef generate
# To verify freshness: alef verify
"""Exception hierarchy (re-exported from the native module)."""
