# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7af711b2a4559d0fd38d5ac3a64506324b09179e74d61c4454c004f03a1fa3e8
# To regenerate: alef generate
# To verify freshness: alef verify
"""Configuration options for the conversion API."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from ._native import (
    ConflictRecord,  # noqa: TC001
    DiagnosticCategory,  # noqa: TC001
    DiagnosticRecord,  # noqa: TC001
    DiagnosticSeverity,  # noqa: TC001
    DirectorySessionMode,  # noqa: TC001
    OperationKind,  # noqa: TC001
    PortableCategory,  # noqa: TC001
    ThreeWayMergeOutcome,  # noqa: TC001
    WorkflowExecutionOwner,  # noqa: TC001
)


class AlternativeState(str, Enum):
    """Alternative state."""

    present = "present"

    absent = "absent"

    invalid = "invalid"

    opaque = "opaque"


class AttachmentHint(str, Enum):
    """Attachment hint."""

    leading = "leading"

    inline = "inline"

    trailing = "trailing"

    preamble = "preamble"

    postlude = "postlude"

    orphan = "orphan"

    unknown = "unknown"


class ConflictAlternativeState(str, Enum):
    """Conflict alternative state."""

    present = "present"

    absent = "absent"


class ConflictCategory(str, Enum):
    """Conflict category."""

    content = "content"

    delete_modify = "delete_modify"

    add_add = "add_add"

    move = "move"

    rename = "rename"

    order = "order"

    identity = "identity"

    ownership = "ownership"

    syntax = "syntax"

    binary_overlap = "binary_overlap"

    archive_entry = "archive_entry"

    provider_specific = "provider_specific"


class CrisprLimitOperator(str, Enum):
    """Crispr limit operator."""

    equal = "equal"

    not_equal = "not_equal"

    at_most = "at_most"

    at_least = "at_least"

    less_than = "less_than"

    greater_than = "greater_than"


class DiagnosticLayer(str, Enum):
    """Diagnostic layer."""

    transport = "transport"

    registry = "registry"

    parser = "parser"

    analysis = "analysis"

    provider = "provider"

    renderer = "renderer"

    verifier = "verifier"

    adapter = "adapter"

    runner = "runner"


class LocalizationStatus(str, Enum):
    """Localization status."""

    exact = "exact"

    owner = "owner"

    coarse = "coarse"

    whole_document = "whole_document"

    unavailable = "unavailable"


class MergeProviderRole(str, Enum):
    """Merge provider role."""

    workflow = "workflow"

    backend = "backend"


class NodeRole(str, Enum):
    """Node role."""

    structural = "structural"

    token = "token"

    trivia = "trivia"

    comment = "comment"

    delimiter = "delimiter"

    separator = "separator"

    virtual = "virtual"

    error = "error"

    opaque = "opaque"


class OwnerChangeKind(str, Enum):
    """Owner change kind."""

    added = "added"

    deleted = "deleted"

    edited = "edited"


class ParseSeverity(str, Enum):
    """Parse severity."""

    info = "info"

    warning = "warning"

    error = "error"


class PolicySurface(str, Enum):
    """Policy surface."""

    fallback = "fallback"

    array = "array"


class ResolutionStatus(str, Enum):
    """Resolution status."""

    unresolved = "unresolved"

    resolved = "resolved"


class ResolutionStrategy(str, Enum):
    """Resolution strategy."""

    none = "none"

    select_role = "select_role"

    combine = "combine"

    policy = "policy"

    custom = "custom"


class ReviewDecisionAction(str, Enum):
    """Review decision action."""

    accept_default_context = "accept_default_context"

    provide_explicit_context = "provide_explicit_context"

    apply_delegated_child_group = "apply_delegated_child_group"


class ReviewDiagnosticReason(str, Enum):
    """Review diagnostic reason."""

    missing_required_payload = "missing_required_payload"

    family_mismatch = "family_mismatch"

    request_not_found = "request_not_found"


class SourceEncoding(str, Enum):
    """Source encoding."""

    utf8 = "utf8"

    binary = "binary"


class SourceRevision(str, Enum):
    """Source revision."""

    base = "base"

    ours = "ours"

    theirs = "theirs"


class SourceRole(str, Enum):
    """Source role."""

    source = "source"

    before = "before"

    after = "after"

    incoming = "incoming"

    current = "current"

    base = "base"

    ours = "ours"

    theirs = "theirs"

    output = "output"


class TemplateDirectoryPlanStatus(str, Enum):
    """Template directory plan status."""

    create = "create"

    update = "update"

    keep = "keep"

    blocked = "blocked"

    omitted = "omitted"


class TemplateExecutionAction(str, Enum):
    """Template execution action."""

    blocked = "blocked"

    omit = "omit"

    keep = "keep"

    raw_copy = "raw_copy"

    write_prepared_content = "write_prepared_content"

    merge_prepared_content = "merge_prepared_content"


class TemplateStrategy(str, Enum):
    """Template strategy."""

    merge = "merge"

    accept_template = "accept_template"

    keep_destination = "keep_destination"

    raw_copy = "raw_copy"


class TemplateTreeRunStatus(str, Enum):
    """Template tree run status."""

    created = "created"

    updated = "updated"

    kept = "kept"

    blocked = "blocked"

    omitted = "omitted"
