# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9dd48720553dad23d5b25725f54f373b54bd7ccc03ca9d40fb2acc48df901b0a
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'bash_common_merge2' do

  it 'bash_merge2_comments: Shared typed Bash merge2 contract: bash_merge2_comments' do
    result = NativeMergeFixture.run_bash_common_merge2("x=1\n\# é new\ny=2 \# inline\nz=3\n", "x=9 \# keep\n\# current z\nz=8\n\# footer\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("x=9 \# keep\n\# é new\ny=2 \# inline\n\# current z\nz=8\n\# footer\n")

  end


  it 'bash_merge2_current: Shared typed Bash merge2 contract: bash_merge2_current' do
    result = NativeMergeFixture.run_bash_common_merge2("x=1\ny=2\n", "x=9\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("x=9\ny=2\n")
    expect(result.verification.directional_roles_preserved).to be(true)
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'bash_merge2_empty: Shared typed Bash merge2 contract: bash_merge2_empty' do
    result = NativeMergeFixture.run_bash_common_merge2("x=1\n", '')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("x=1\n")

  end


  it 'bash_merge2_reordered: Shared typed Bash merge2 contract: bash_merge2_reordered' do
    result = NativeMergeFixture.run_bash_common_merge2("b=2\nnew=3\na=1\n", "a=9\nb=8\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)

  end

end
