# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c2bbf402b78f08fb93b837e7870e9d426e81a2611755e449f82692046f37203b
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'capability_manifest' do

  it 'capability_bash: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.bash.owners.v1', 'merge3', 'bash')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.bash.owners.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('bash')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_git: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.git.json.v1', 'merge3', 'jsonc')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.git.json.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('json5')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_git_analyze: Undeclared scope remains unprobed, with unknown eligibility and no default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.git.json.v1', 'analyze', 'json')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.git.json.v1')
    expect(result.observations[0].operation_declared).to be(false)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to eq(nil)
    expect(result.observations[0].parser_request).to eq(nil)
    expect(result.observations[0].parser_report).to eq(nil)

  end


  it 'capability_go: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.go.owners.v1', 'merge3', 'go')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.go.owners.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('go')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_json: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.json.nested.v1', 'analyze', 'json5')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.json.nested.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('json5')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_python: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.python.native_declarations.v1', 'merge3', '')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.python.native_declarations.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('python')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_python_dialect: Undeclared scope remains unprobed, with unknown eligibility and no default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.python.native_declarations.v1', 'merge3', 'python')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.python.native_declarations.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(false)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to eq(nil)
    expect(result.observations[0].parser_request).to eq(nil)
    expect(result.observations[0].parser_report).to eq(nil)

  end


  it 'capability_rust: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.rust.owners.v1', 'merge3', 'rust')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.rust.owners.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('rust')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_typescript: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.typescript.owners.v1', 'merge3', 'tsx')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.typescript.owners.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('tsx')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_yaml: Declared profile scope does not imply an eligible parser or default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.yaml.native_mapping.v1', 'merge3', '')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.yaml.native_mapping.v1')
    expect(result.observations[0].operation_declared).to be(true)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to be(false)
    expect(result.observations[0].parser_request.language.to_s).to eq('yaml')
    expect(result.observations[0].parser_report.selected_backend).to eq(nil)

  end


  it 'capability_yaml_merge2: Undeclared scope remains unprobed, with unknown eligibility and no default approval.' do
    result = NativeMergeFixture.run_capability_manifest('kernel.yaml.native_mapping.v1', 'merge2', '')
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.observations.length).to eq(1)
    expect(result.observations[0].query.profile_id.to_s).to eq('kernel.yaml.native_mapping.v1')
    expect(result.observations[0].operation_declared).to be(false)
    expect(result.observations[0].dialect_declared).to be(true)
    expect(result.observations[0].approved_as_default).to be(false)
    expect(result.observations[0].parser_eligible).to eq(nil)
    expect(result.observations[0].parser_request).to eq(nil)
    expect(result.observations[0].parser_report).to eq(nil)

  end

end
