# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14aca84fe5386c8c0cc2da68b29afe6e5db2fec163874d81d425fd5993e1a5f8
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'capability_inventory' do

  it 'capability_inventory: An empty query list exposes declarations, not successful probes or default authority.' do
    result = NativeMergeFixture.run_capability_inventory()
    expect(result.schema.to_s).to eq('structuredmerge.typed-capability-manifest/v1')
    expect(result.profiles.profiles.length).to eq(8)
    expect(result.observations.length).to eq(0)

  end

end
