# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5bbdb9867749eaa15eacfea08ae513771638bf32c5be2c8a76103da9291f5735
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'go_common_analyze' do

  it 'go_analysis: Shared typed Go analyze contract: go_analysis' do
    result = NativeMergeFixture.run_go_common_analyze("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n")
    expect(result.ok).to be(true)
    expect(result.analysis.extra["owners"].to_s).to include('/function:f')
    expect(result.analysis.extra["owners"].to_s).to include('node_ids')

  end


  it 'go_analysis_rejected: Shared typed Go analyze contract: go_analysis_rejected' do
    result = NativeMergeFixture.run_go_common_analyze("package main\nvar x=1\n")
    expect(result.ok).to be(false)
    expect(result.analysis).to eq(nil)

  end

end
