# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3254170a7550ca761cea6d560393b9068111c19c83f728a394c0973fe4e6f2bd
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'go_common_merge3' do

  it 'go_merge3_conflict: Shared typed Go merge3 contract: go_merge3_conflict' do
    result = NativeMergeFixture.run_go_common_merge3("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n", "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n", "package main\n// é\nfunc f() { println(3) }\nfunc g() { println(1) }\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)

  end


  it 'go_merge3_guard: Shared typed Go merge3 contract: go_merge3_guard' do
    result = NativeMergeFixture.run_go_common_merge3("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n", "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n", "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\nfunc added() {}\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)
    expect(result.conflicts[0].canonical.code.to_s).to eq('go.membership_with_owner_edit')
    expect(result.conflicts[0].canonical.subject.whole_document).to be(true)
    expect(result.conflicts[0].canonical.decision_ids.length).to eq(0)
    expect(result.verification.base_participated).to be(true)

  end


  it 'go_merge3_independent: Shared typed Go merge3 contract: go_merge3_independent' do
    result = NativeMergeFixture.run_go_common_merge3("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }\n", "package main\n// é\nfunc f() { println(2) }\nfunc g() { println(1) }\n", "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(2) }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("package main\n// é\nfunc f() { println(2) }\nfunc g() { println(2) }\n")
    expect(result.verification.output_reparsed).to be(true)
    expect(result.verification.base_participated).to be(true)

  end


  it 'go_merge3_noop: Shared typed Go merge3 contract: go_merge3_noop' do
    result = NativeMergeFixture.run_go_common_merge3("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }", "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }", "package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("package main\n// é\nfunc f() { println(1) }\nfunc g() { println(1) }")
    expect(result.verification.output_reparsed).to be(true)

  end

end
