# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:981933722402bb5122c3e9d971d8d4e3fd67358f4c7e025d7dc0b8f534f0ce49
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'json_common_merge2' do

  it 'json_merge2_current_preferred: Directional JSON merge keeps current values, arrays and exact CRLF bytes without a base.' do
    result = NativeMergeFixture.run_json_common_merge2('json', '{"x":2,"a":[3]}', "{\r\n \"x\":1,\"a\":[1,2]\r\n}")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("{\r\n \"x\":1,\"a\":[1,2]\r\n}")
    expect(result.verification.directional_roles_preserved).to be(true)
    expect(result.verification.base_participated).to eq(nil)
    expect(result.verification.output_reparsed).to be(true)

  end

end
