# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:203725a35a9e24b286b4e84238a159e3a0e3fbe40be3108136b5c3258e02aa0f
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'json_common_analyze' do

  it 'json_analysis_duplicate_keys: Duplicate decoded JSON keys fail closed rather than collapsing owners.' do
    result = NativeMergeFixture.run_json_common_analyze('json', '{"x":1,"\\u0078":2}')
    expect(result.ok).to be(false)
    expect(result.analysis).to eq(nil)
    expect(result.output).to eq(nil)
    expect(result.diagnostics.length).to eq(1)

  end


  it 'json_analysis_jsonc_rejects_json5: JSONC rejects JSON5-only keys and strings despite sharing its parser grammar.' do
    result = NativeMergeFixture.run_json_common_analyze('jsonc', "{x:'not-jsonc'}")
    expect(result.ok).to be(false)
    expect(result.analysis).to eq(nil)
    expect(result.output).to eq(nil)

  end


  it 'json_analysis_nested: Nested JSON5 analysis uses Rust-owned native facts.' do
    result = NativeMergeFixture.run_json_common_analyze('json5', "// note\r\n{a:{x:'é'},b:[1,2]}\r\n")
    expect(result.analysis.extra["owners"].to_s).to include('"path":"/a/x"')
    expect(result.analysis.extra["owners"].to_s).to include('"path":"/b/1"')
    expect(result.ok).to be(true)
    expect(result.analysis.schema.to_s).to eq('structuredmerge.analysis-result/v1')
    expect(result.output).to eq(nil)
    expect(result.provider.provider_id.to_s).to eq('kernel.json')

  end


  it 'json_analysis_unclaimed: An unattached native comment remains analyzable without a fabricated sibling attachment.' do
    result = NativeMergeFixture.run_json_common_analyze('json5', '{} /* retained */')
    expect(result.analysis.extra["comment_regions"].to_s).to include('"attachment_resolved":false')
    expect(result.analysis.extra["comment_regions"].to_s).to include('"owner_id":"json:"')
    expect(result.ok).to be(true)
    expect(result.analysis.schema.to_s).to eq('structuredmerge.analysis-result/v1')
    expect(result.output).to eq(nil)

  end

end
