# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d5f71684c7b2a0155ea751baa1775071f081f8b0c002711b82669996c8da1e3e
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'structuredmerge_core'
require 'json'

RSpec.describe 'native_profiles' do

  it 'native_profiles_are_explicitly_experimental: Scoped Rust merge profiles expose their identity and do not claim default approval.' do
    result = StructuredmergeCore.native_merge_profiles()
    expect(result.length).to eq(2)
    expect(result[0].id.to_s).to eq('kernel.python.native_declarations.v1')
    expect(result[1].id.to_s).to eq('kernel.yaml.native_mapping.v1')
    expect(result[0].semantic_runtime.to_s).to eq('rust')
    expect(result[1].semantic_runtime.to_s).to eq('rust')
    expect(result[0].experimental).to be(true)
    expect(result[1].experimental).to be(true)
    expect(result[0].approved_as_default).to be(false)
    expect(result[1].approved_as_default).to be(false)

  end

end
