# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f6925684cfefd6e5d3feb32480561f6d64c659018e238c89c69e80d1f11705cf
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'rust_common_diff' do

  it 'rust_diff_owner: Shared typed Rust diff: diff_owner' do
    result = NativeMergeFixture.run_rust_common_diff("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::fmt;\n// é\nfn f() -> i32 { 2 }\nfn g() -> i32 { 1 }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(2)
    expect(result.changes[0].path.to_s).to eq('/function:f')

  end


  it 'rust_diff_use: Shared typed Rust diff: diff_use' do
    result = NativeMergeFixture.run_rust_common_diff("use std::fmt;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n", "use std::io;\n// é\nfn f() -> i32 { 1 }\nfn g() -> i32 { 1 }\n")
    expect(result.ok).to be(true)
    expect(result.changes.length).to eq(1)
    expect(result.changes[0].subject_ref.to_s).to eq('document')

  end

end
