# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e81d93168d6b749c4e85e74491f259d1c5f8d0a3a5ec84b34202ce19a0a6e7d
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'typescript_common_merge3' do

  it 'tsx_jsx_merge3: Shared tsx grammar jsx_merge3' do
    result = NativeMergeFixture.run_typescript_common_merge3('tsx', "function View() { return <div>one</div>; }\nfunction f() { return 1; }\n", "function View() { return <div>two</div>; }\nfunction f() { return 1; }\n", "function View() { return <div>one</div>; }\nfunction f() { return 2; }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("function View() { return <div>two</div>; }\nfunction f() { return 2; }\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'tsx_merge3_conflict: Shared typed tsx merge3: merge3_conflict' do
    result = NativeMergeFixture.run_typescript_common_merge3('tsx', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 3; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)

  end


  it 'tsx_merge3_independent: Shared typed tsx merge3: merge3_independent' do
    result = NativeMergeFixture.run_typescript_common_merge3('tsx', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 2; }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 2; }\n")
    expect(result.verification.output_reparsed).to be(true)
    expect(result.verification.base_participated).to be(true)

  end


  it 'tsx_merge3_noop: Shared typed tsx merge3: merge3_noop' do
    result = NativeMergeFixture.run_typescript_common_merge3('tsx', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'typescript_merge3_conflict: Shared typed typescript merge3: merge3_conflict' do
    result = NativeMergeFixture.run_typescript_common_merge3('typescript', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 3; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)

  end


  it 'typescript_merge3_independent: Shared typed typescript merge3: merge3_independent' do
    result = NativeMergeFixture.run_typescript_common_merge3('typescript', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 2; }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("import { x } from 'x';\n// é\nexport function f() { return 2; }\nfunction g() { return 2; }\n")
    expect(result.verification.output_reparsed).to be(true)
    expect(result.verification.base_participated).to be(true)

  end


  it 'typescript_merge3_noop: Shared typed typescript merge3: merge3_noop' do
    result = NativeMergeFixture.run_typescript_common_merge3('typescript', "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n", "import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("import { x } from 'x';\n// é\nexport function f() { return 1; }\nfunction g() { return 1; }\n")
    expect(result.verification.output_reparsed).to be(true)

  end

end
