# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:86ed453a67ba901c9f2888ce554f1269ba2ac1d85e9d3c9e16c135cbe01f53ee
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require './native_merge_fixture'
require 'json'

RSpec.describe 'yaml_common_merge' do

  it 'yaml_common_byte_preservation: Common typed merge through the installed binding, using native parser facts and Rust-owned semantics.' do
    result = NativeMergeFixture.run_yaml_common_merge("﻿\# header\r\né: 'one'  \# stable\r\nbeta: two", "﻿\# header\r\né: 'ours'  \# stable\r\nbeta: two", "﻿\# header\r\né: 'one'  \# stable\r\nbeta: theirs")
    expect(result.schema.to_s).to eq('https://structuredmerge.org/schemas/provider-result/v1.json')
    expect(result.request_id.to_s).to eq('typed-common-merge3')
    expect(result.provider.provider_id.to_s).to eq('kernel.yaml')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("﻿\# header\r\né: 'ours'  \# stable\r\nbeta: theirs")
    expect(result.conflicts.length).to eq(0)
    expect(result.verification.output_reparsed).to be(true)

  end


  it 'yaml_common_conflicting_merge: Common typed merge through the installed binding, using native parser facts and Rust-owned semantics.' do
    result = NativeMergeFixture.run_yaml_common_merge("alpha: one\n", "alpha: ours\n", "alpha: theirs\n")
    expect(result.schema.to_s).to eq('https://structuredmerge.org/schemas/provider-result/v1.json')
    expect(result.request_id.to_s).to eq('typed-common-merge3')
    expect(result.provider.provider_id.to_s).to eq('kernel.yaml')
    expect(result.ok).to be(false)
    expect(result.output).to eq(nil)
    expect(result.conflicts.length).to eq(1)

  end


  it 'yaml_common_independent_merge: Common typed merge through the installed binding, using native parser facts and Rust-owned semantics.' do
    result = NativeMergeFixture.run_yaml_common_merge("alpha: one\nbeta: two\n", "alpha: ours\nbeta: two\n", "alpha: one\nbeta: theirs\n")
    expect(result.schema.to_s).to eq('https://structuredmerge.org/schemas/provider-result/v1.json')
    expect(result.request_id.to_s).to eq('typed-common-merge3')
    expect(result.provider.provider_id.to_s).to eq('kernel.yaml')
    expect(result.ok).to be(true)
    expect(result.output.to_s).to eq("alpha: ours\nbeta: theirs\n")
    expect(result.conflicts.length).to eq(0)
    expect(result.verification.output_reparsed).to be(true)

  end

end
