# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be465a0e78ed79f5fe98b7cbbd47d8b1963040045efe60e63e94d28c2a87db8d
# To regenerate: alef generate
# To verify freshness: alef verify
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The native_merge_fixture package is expected to be installed in the current environment.
