# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d0da8eb7dc8087997f43e50a8cecfeb9d82328987aa47ae1e3a5c49609e97ad9
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require_relative "structuredmerge_core/version"
require_relative "structuredmerge_core/native"

# Top-level namespace for the StructuredmergeCore Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "structuredmerge_core/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module StructuredmergeCore
  # Re-export all types and functions from native extension
end

# Keep generated types under StructuredmergeCore. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
