# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc9d5a248d4fd5fc6491a5e70dbf6dcd78985922c006747a963bc685aa0ae0ec
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module StructuredmergeHostPrototype
  ## The version string for this package.
  VERSION = "0.2.1"
end
